
package org.tio.sitexxx.service.model.stat;

import org.tio.sitexxx.service.model.stat.base.BaseAreaStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AreaStat extends BaseAreaStat<AreaStat> {
	public static final AreaStat dao = new AreaStat().dao();
}
