
package org.tio.sitexxx.service.model.stat;

import org.tio.sitexxx.service.model.stat.base.BaseGroupStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupStat extends BaseGroupStat<GroupStat> {
	public static final GroupStat dao = new GroupStat().dao();
}
