
package org.tio.sitexxx.service.model.stat;

import org.tio.sitexxx.service.model.stat.base.BaseTioChannelStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TioChannelStat extends BaseTioChannelStat<TioChannelStat> {
	public static final TioChannelStat dao = new TioChannelStat().dao();
}
