
package org.tio.sitexxx.service.model.stat;

import org.tio.sitexxx.service.model.stat.base.BaseTioTokenPathAccessStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TioTokenPathAccessStat extends BaseTioTokenPathAccessStat<TioTokenPathAccessStat> {
	public static final TioTokenPathAccessStat dao = new TioTokenPathAccessStat().dao();
}
