
package org.tio.sitexxx.service.model.stat;

import org.tio.sitexxx.service.model.stat.base.BaseUserTimeLoginStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTimeLoginStat extends BaseUserTimeLoginStat<UserTimeLoginStat> {
	public static final UserTimeLoginStat dao = new UserTimeLoginStat().dao();
}
