# 程序运行模式：1、开发，2、测试，3、生产环境
dev.mode=1

# 是否启动im，1：启动，2：不启动
start.im=1

# 是否启动view，1：启动，2：不启动
start.view=1

# 是否im和wx互通：1：是；2：否
im.connect.wx=1

# 生产环境配成false，开发环境无所谓
tio.setCheckLastVersion = false

# --------------- tio集群配置 start
# 是否使用tio集群，如果是单机请配置为false，程序做了特别的单机优化，如果此值配成false，tio集群的其它配置都将不起作用
use.tio.clu = false
#  集群服务器ip
tio.clu.server.ip=192.168.31.2
tio.clu.server.port=1982
#  集群重连间隔时间，单位：毫秒
tio.clu.client.reconn.time=10000
# client连接数
tio.clu.client.connection.num=1
# IM服务器配成true，后台管理服务器配成false
systemparam.tio.clu.client.as.bsservernode=true
# --------------- tio集群配置 end


#mysql备份存放的目录
mysql.backup.dir=D:/AAA/mysqlbackup

# 是否启动flashpolicyserver，1：启动，2：不启动
#用flash与服务器交互时，会用到，譬如基于flash的播放器
start.flash.policy.server=2

# 系统参数，系统参数以systemparam.开头，系统启动时会自动调用System.setProperty()，譬如：System.setProperty("TIO_MAX_POOL_SIZE_FOR_TIO", 64)
systemparam.TIO_MAX_POOL_SIZE_FOR_TIO = 32
systemparam.TIO_MAX_POOL_SIZE_FOR_GROUP = 256
systemparam.org.freemarker.loggerLibrary = SLF4J


# view项目的模型文件，生产环境和测试环境配成webpack.json，开发环境配成webpack-dev.json
#1、用webpack.json会压缩html、js、css
#2、用webpack.json会无视js中的log()、info()、error()函数；用webpack-dev.json这几个函数分别对应console.log()、console.info()、console.error()
view.model.config.file=webpack.json

# web api工程中，是否启动httpcache表中配置的业务缓存，1：启用，2：不启用
web.api.use.http.cache=1
# web view工程，是否启动httpcache表中配置的业务缓存，1：启用，2：不启用
web.view.use.http.cache=1

# 是否开启自动生成头像:1:开启；2：不开启
use.auto.avatar = 1
# 预加载 1、加载，2、不加载
view.preAccess=2

#敏感过滤开关：true:开启；false:关闭
sensitive.flag=true
# 网站地址
site=192.168.31.2

#上传资源服务器
#1、这个服务器是单纯的nginx服务器，并不经过java
#2、对照upload.tiocloud.com.conf一起理解
# res.server=https://ctr2.atex.cc/
# res.server=https://qingxiao.yourda.cc/
res.server=https://qingxiao.yourda.cc/

#1、用户通过http-api服务器上传的文件会存在这个目录下
#2、用户访问这些资源只通过nginx访问，并不经过http-api服务器
#3、对照nginx/conf/server/res.conf一起理解，此值与res.conf文件的"server -> location -> root"配置值一样
res.root=D:/AAA/upload

#用于维持tio http session的cookie name，可以不用修改
#1、如果开发环境和测试环境的主域名一样，不同环境建议设置不同值，这样同时访问两个环境时cookie不会相互干扰
http.session.cookie.name=tio_session

##    http 配置 start
#监听端口
http.api.port = 6060
http.view.port = 10160

#静态资源目录，包含html, js, css, 图片等
# 视图资源目录，包含html, js, css, 图片等，其中非res目录下的html、js、css是支持freemarker的
# nginx.conf有个配置项：location ~ /res/.+/.*$ {...}
#http.view.page=F:/work/tio-site/src/frontend/all/src/main/resources/config/page
#http.view.page=/home/bs/page
http.view.page=D:/AAA/bs-page

#解码异常时，是否打印日志，开发环境建议开启
http.api.logWhenDecodeError = true
http.view.logWhenDecodeError = true
im.logWhenDecodeError = true
im.ws.logWhenDecodeError = true

#静态资源缓存时间，小于等于0则不缓存静态资源，单位：秒，（3600=1小时，86400=24小时，2592000=30天，15552000=180天）
#1、生产环境的html、js、css是会加载到内存缓存起来的，当你更换这些文件时，并不会立即生效（你可以通过"遥控"下的"清空静态资源"立即生效）
#2、开发环境的配置值，负数表示不缓存，这样就不用频繁的清空缓存了
http.maxLiveTimeOfStaticRes=864000
# 上传文件允许的最大size，单位：KB
http.max_length_of_multi_body = 204800
# POST时允许的最大size，单位：KB
http.max_length_of_post_body = 204800

## cookie域名，生产环境应该是.tiocloud.com
http.cookie.domain=192.168.31.2

## 是否被代理了，如果运行在nginx等的后面，此值要填true
http.isproxied=true

#------------ 数据库配置 start ---------
db.jdbc.pool.initialSize=1
db.jdbc.pool.maxActive=100
db.jdbc.pool.minIdle=1
db.jdbc.driverClassName=com.mysql.cj.jdbc.Driver
#db.jdbc.filters=slf4j,config,stat,wall
db.jdbc.filters=

db.jdbc.validationQuery=SELECT 'x'

#注意格式，必须是tio_site_xxxx格式
db.jdbc.multi.name=tio_site_main,tio_site_stat,tio_site_conf

#业务库
tio_site_main.jdbc.url=jdbc:mysql://192.168.31.148:3306/tio_site_main?connectTimeout=60000&socketTimeout=60000&generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&tcpKeepAlive=true
tio_site_main.jdbc.driverClassName=${db.jdbc.driverClassName}
tio_site_main.jdbc.username=root
tio_site_main.jdbc.password=xMYzHywKAAmrhyCs
tio_site_main.dbType=mysql

tio_site_stat.jdbc.url=jdbc:mysql://192.168.31.148:3306/tio_site_stat?connectTimeout=60000&socketTimeout=60000&generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&tcpKeepAlive=true
tio_site_stat.jdbc.driverClassName=${db.jdbc.driverClassName}
tio_site_stat.jdbc.username=root
tio_site_stat.jdbc.password=xMYzHywKAAmrhyCs
tio_site_stat.dbType=mysql

tio_site_conf.jdbc.url=jdbc:mysql://192.168.31.148:3306/tio_site_conf?connectTimeout=60000&socketTimeout=60000&generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&tcpKeepAlive=true
tio_site_conf.jdbc.driverClassName=${db.jdbc.driverClassName}
tio_site_conf.jdbc.username=root
tio_site_conf.jdbc.password=xMYzHywKAAmrhyCs
tio_site_conf.dbType=mysql
#------------ 数据库配置   end ---------

#启动清空配置缓存-开发模式设置为true;正式环境建议false
clear.cache.flag=true

#------------ redis start ---------
redis.cluster.flag=false
redis.ip=192.168.31.148
redis.port=6379
redis.password=
redis.cluster.address=redis://127.0.0.1:7000,redis://127.0.0.1:7001,redis://127.0.0.1:7002,redis://127.0.0.1:7003,redis://127.0.0.1:7004,redis://127.0.0.1:7005,redis://127.0.0.1:7006,redis://127.0.0.1:7007,redis://127.0.0.1:7008,redis://127.0.0.1:7009,redis://127.0.0.1:7010,redis://127.0.0.1:7011
#------------ redis   end ---------

# QPS
request.permitsPerSecond=4000000
# 清理本阶段警告的时间间隔，参考值1000 * 60 * 60 * 2，单位为ms
request.warnClearInterval=300
# 本阶段最多警告多次数，参考值10
request.maxWarnCount=5000000
# 一共最多警告多次数
request.maxAllWarnCount=200000
#前面多少条消息不计入令牌桶
skip.warn.count = 80000000

#服务端短信验证开关：1:开启；2:关闭（只是服务端不做正确性验证，跟客户端流程无关）
sms.openflag=2
#短信配置 1:短信宝 2:阿里云 3:网易云信
sms.type=1
#短信宝短信配置
sms.smsbao.keyid=jingg168
sms.smsbao.keysecret=${SMSBAO_KEYSECRET}
#短信宝签名
#sms.smsbao.signName=【成通巢讯】
sms.smsbao.signName=【擎霄科技】
#短信宝登录验证模板
sms.smsbao.templateCode.login=您的验证码是{code}。如非本人操作，请忽略本短信
##短信宝注册验证模板
sms.smsbao.templateCode.register=您的验证码是{code}。如非本人操作，请忽略本短信
#短信宝绑定手机号验证模板
sms.smsbao.templateCode.bindphone=您的验证码是{code}。如非本人操作，请忽略本短信
#短信宝修改手机号前的旧手机号验证模板
sms.smsbao.templateCode.oldphonecheck=您的验证码是{code}。如非本人操作，请忽略本短信
#短信宝修改手机号的新手机号验证模板
sms.smsbao.templateCode.bindnewphone=您的验证码是{code}。如非本人操作，请忽略本短信
#短信宝找回密码验证模板
sms.smsbao.templateCode.pwdback=您的验证码是{code}。如非本人操作，请忽略本短信
#短信宝修改密码验证模板
sms.smsbao.templateCode.updatepwd=您的验证码是{code}。如非本人操作，请忽略本短信
#短信宝注册并绑定老邮箱验证模板
sms.smsbao.templateCode.registerbindemail=您的验证码是{code}。如非本人操作，请忽略本短信
#短信宝三方登录绑定手机号验证模板
sms.smsbao.templateCode.thirdbind=您的验证码是{code}。如非本人操作，请忽略本短信
#短信宝找回支付密码
sms.smsbao.templateCode.resetpaypwd=您的验证码是{code}。如非本人操作，请忽略本短信
#短信宝注销
sms.smsbao.templateCode.logout=您的验证码是{code}。如非本人操作，请忽略本短信

#阿里云短信配置
sms.aliyun.keyid=${ALIYUN_ACCESS_KEY_ID}
sms.aliyun.keysecret=${ALIYUN_ACCESS_KEY_SECRET}
sms.aliyun.regionId=cn-hangzhou
#阿里云签名
sms.aliyun.signName=成通巢讯
#阿里云登录验证模板
sms.aliyun.templateCode.login=SMS_314646166
#阿里云注册验证模板
sms.aliyun.templateCode.register=SMS_314646166
#阿里云绑定手机号验证模板
sms.aliyun.templateCode.bindphone=SMS_314646166
#阿里云修改手机号前的旧手机号验证模板
sms.aliyun.templateCode.oldphonecheck=SMS_314646166
#阿里云修改手机号的新手机号验证模板
sms.aliyun.templateCode.bindnewphone=SMS_314646166
#阿里云找回密码验证模板
sms.aliyun.templateCode.pwdback=SMS_314646166
#阿里云修改密码验证模板
sms.aliyun.templateCode.updatepwd=SMS_314646166
#阿里云注册并绑定老邮箱验证模板
sms.aliyun.templateCode.registerbindemail=SMS_314646166
#阿里云三方登录绑定手机号验证模板
sms.aliyun.templateCode.thirdbind=SMS_314646166
#阿里云找回支付密码
sms.aliyun.templateCode.resetpaypwd=SMS_314646166
#阿里云注销
sms.aliyun.templateCode.logout=SMS_314646166

#网易云信短信配置
yun.appkey=46c0c96d306fee3bbda484a8c6b525d9
yun.appsecret=${YUN_APPSECRET}
yun.nonce=123456
yun.templateid=22536649

#每个ip每天最大数量
sms.maxcount.ip.perday=5
#每个设备每天最大数量-扩展字段
sms.maxcount.device.count=5
#每个手机号每天最大数量
sms.maxcount.mobile.perday=5
#极光推送参数:true:开启；false:关闭
Jpush.open.flag=true
JAppKey=e09e4e97149a462165c976b7
JMasterSecret=${JMASTER_SECRET}



#新版同步开启标识：true:新版；false:
syn.newversion.flag=false
#消息已读-焦点高新性能开关：true:开启；false:关闭
msg.read.focus.flag=false


#支付版本:1：新生支付；2：易支付
pay.version.type=3
wallet.open.flag=true
#易支付商户号
#wallet.merchantid=
#新生支付商户号
wallet.merchantid=123321
#新生支付版本的私钥位置
wallet.merchant.pem=classpath:config/wallet/ncount-private-key.pem

#外部登录服务地址
out.service=http:/127.0.0.1:6061

# cloudflare / tencentoss
oss-type=tencentoss

# Cloudflare R2
cloudflare.r2-access-key=88cbe45580fc5725986f0c1ffd1db6e3
cloudflare.r2-secret-key=${CF_R2_SECRET_KEY}
cloudflare.r2-bucket-name=ctcx
cloudflare.r2-endpoint=https://0fd4c030de5520eae6227e1c590a64f4.r2.cloudflarestorage.com


tencentoss.secret-id=${TENCENT_OSS_SECRET_ID}
tencentoss.secret-key=${TENCENT_OSS_SECRET_KEY}
tencentoss.bucket-name=qingm188-1333631480
tencentoss.region=ap-hongkong
