## 有域名则配域名，譬如sub1.tiocloud.com
my.ip=192.168.31.2

## uuid start 
# 1、要保证每台不同的机器，这两个值的搭配值不一样
# 2、取值范围[1-31]
uuid.workerid=2
uuid.datacenter=1
## uuid end

# 下面3个是SSL证书的配置
#https://www.ssleye.com/ssltool/jks_pkcs12.html 这里生成
# file of keystore，如果以classpath:开头，则从classpath中查找，否则从文件路径中查找
#	--例1： classpath:config/ssl/keystore.jks
#	--例2： /ssl/ca/keystore.jks
#ssl.keystore=classpath:config/ssl/tiocloud/certificate.jks
#ssl.truststore=classpath:config/ssl/tiocloud/certificate.jks
#ssl.pwd=2e513f

#独立计划任务执行标识：执行：true；不执行：false，同一个集群中只有一台机器配成true
quartz.open.flag=true
#消息通知处理：执行：true；不执行：false，同一个集群中只有一台机器配成true
msg.topic.flag=true
