
package org.tio.sitexxx.service.model.main;

import org.tio.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("audio", "id", Audio.class);
		arp.addMapping("chatroom_join_leave", "id", ChatroomJoinLeave.class);
		arp.addMapping("demo", "id", Demo.class);
		arp.addMapping("email_send_log", "id", EmailSendLog.class);
		arp.addMapping("file", "id", File.class);
		arp.addMapping("img", "id", Img.class);
		arp.addMapping("ip_info", "id", IpInfo.class);
		arp.addMapping("login_log", "id", LoginLog.class);
		arp.addMapping("login_task_items", "id", LoginTaskItems.class);
		arp.addMapping("oauth2_client", "id", Oauth2Client.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("sms_log", "id", SmsLog.class);
		arp.addMapping("stat_online", "id", StatOnline.class);
		arp.addMapping("tio_thread_logs", "id", TioThreadLogs.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_action_log", "id", UserActionLog.class);
		arp.addMapping("user_address", "id", UserAddress.class);
		arp.addMapping("user_agent", "id", UserAgent.class);
		arp.addMapping("user_base", "id", UserBase.class);
		arp.addMapping("user_info_syn", "id", UserInfoSyn.class);
		arp.addMapping("user_last_login_time", "id", UserLastLoginTime.class);
		arp.addMapping("user_msg", "id", UserMsg.class);
		arp.addMapping("user_role", "id", UserRole.class);
		arp.addMapping("user_third", "id", UserThird.class);
		arp.addMapping("user_third_osc", "id", UserThirdOsc.class);
		arp.addMapping("user_third_qq", "id", UserThirdQq.class);
		arp.addMapping("user_third_weibo", "id", UserThirdWeibo.class);
		arp.addMapping("user_third_wx", "id", UserThirdWx.class);
		// Composite Primary Key order: devicetype,uid
		arp.addMapping("user_token", "devicetype,uid", UserToken.class);
		arp.addMapping("userlog_modify_avatar", "id", UserlogModifyAvatar.class);
		arp.addMapping("userlog_modify_nick", "id", UserlogModifyNick.class);
		arp.addMapping("video", "id", Video.class);
		arp.addMapping("video_oper_log", "id", VideoOperLog.class);
		arp.addMapping("wx_app", "id", WxApp.class);
		arp.addMapping("wx_call_item", "id", WxCallItem.class);
		arp.addMapping("wx_call_log", "id", WxCallLog.class);
		arp.addMapping("wx_chat_del_item", "id", WxChatDelItem.class);
		// Composite Primary Key order: groupid,uid
		arp.addMapping("wx_chat_group_item", "groupid,uid", WxChatGroupItem.class);
		arp.addMapping("wx_chat_items", "id", WxChatItems.class);
		arp.addMapping("wx_chat_items_meta", "id", WxChatItemsMeta.class);
		// Composite Primary Key order: bizid,chatmode,uid
		arp.addMapping("wx_chat_user_item", "bizid,chatmode,uid", WxChatUserItem.class);
		arp.addMapping("wx_friend", "id", WxFriend.class);
		arp.addMapping("wx_friend_apply_items", "id", WxFriendApplyItems.class);
		arp.addMapping("wx_friend_apply_log", "id", WxFriendApplyLog.class);
		arp.addMapping("wx_friend_del_log", "id", WxFriendDelLog.class);
		arp.addMapping("wx_friend_meta", "id", WxFriendMeta.class);
		arp.addMapping("wx_friend_msg", "id", WxFriendMsg.class);
		arp.addMapping("wx_friend_oper_msg", "id", WxFriendOperMsg.class);
		arp.addMapping("wx_group", "id", WxGroup.class);
		arp.addMapping("wx_group_apply", "id", WxGroupApply.class);
		arp.addMapping("wx_group_apply_items", "id", WxGroupApplyItems.class);
		arp.addMapping("wx_group_inblack", "id", WxGroupInblack.class);
		arp.addMapping("wx_group_meta", "id", WxGroupMeta.class);
		arp.addMapping("wx_group_msg", "id", WxGroupMsg.class);
		arp.addMapping("wx_group_msg_user_oper", "id", WxGroupMsgUserOper.class);
		arp.addMapping("wx_group_user", "id", WxGroupUser.class);
		arp.addMapping("wx_group_user_del_log", "id", WxGroupUserDelLog.class);
		arp.addMapping("wx_group_user_invite_log", "id", WxGroupUserInviteLog.class);
		arp.addMapping("wx_jpush_user", "id", WxJpushUser.class);
		arp.addMapping("wx_read_ack", "id", WxReadAck.class);
		arp.addMapping("wx_syn_item", "id", WxSynItem.class);
		arp.addMapping("wx_tag", "id", WxTag.class);
		arp.addMapping("wx_tag_friend", "id", WxTagFriend.class);
		arp.addMapping("wx_task_items", "id", WxTaskItems.class);
		arp.addMapping("wx_user_bank_card", "id", WxUserBankCard.class);
		arp.addMapping("wx_user_black_items", "id", WxUserBlackItems.class);
		arp.addMapping("wx_user_coin", "id", WxUserCoin.class);
		arp.addMapping("wx_user_coin_item", "id", WxUserCoinItem.class);
		arp.addMapping("wx_user_favorites", "id", WxUserFavorites.class);
		arp.addMapping("wx_user_merge_data", "id", WxUserMergeData.class);
		arp.addMapping("wx_user_grab_red_item", "id", WxUserGrabRedItem.class);
		arp.addMapping("wx_user_realname", "id", WxUserRealname.class);
		arp.addMapping("wx_user_recharge_item", "id", WxUserRechargeItem.class);
		arp.addMapping("wx_user_red_packet", "id", WxUserRedPacket.class);
		arp.addMapping("wx_user_red_packet_item", "id", WxUserRedPacketItem.class);
		arp.addMapping("wx_user_report", "id", WxUserReport.class);
		arp.addMapping("wx_user_send_red_item", "id", WxUserSendRedItem.class);
		arp.addMapping("wx_user_wallet", "id", WxUserWallet.class);
		arp.addMapping("wx_user_withhold_count", "id", WxUserWithholdCount.class);
		arp.addMapping("wx_user_withhold_item", "id", WxUserWithholdItem.class);
		arp.addMapping("wx_wallet", "id", WxWallet.class);
		arp.addMapping("wx_wallet_back_red_packet_items", "id", WxWalletBackRedPacketItems.class);
		arp.addMapping("wx_wallet_bank_cards", "id", WxWalletBankCards.class);
		arp.addMapping("wx_wallet_bank_info", "id", WxWalletBankInfo.class);
		arp.addMapping("wx_wallet_coin", "id", WxWalletCoin.class);
		arp.addMapping("wx_wallet_coin_item", "id", WxWalletCoinItem.class);
		arp.addMapping("wx_wallet_grab_red_item", "id", WxWalletGrabRedItem.class);
		arp.addMapping("wx_wallet_info", "id", WxWalletInfo.class);
		arp.addMapping("wx_wallet_recharge_item", "id", WxWalletRechargeItem.class);
		arp.addMapping("wx_wallet_red_packet_random", "id", WxWalletRedPacketRandom.class);
		arp.addMapping("wx_wallet_send_red_packet", "id", WxWalletSendRedPacket.class);
		arp.addMapping("wx_wallet_withhold_count", "id", WxWalletWithholdCount.class);
		arp.addMapping("wx_wallet_withhold_items", "id", WxWalletWithholdItems.class);

        arp.addMapping("mg_discovery_page", "id", MgDiscoveryPage.class);
		arp.addMapping("default_friends", "id", DefaultFriends.class);
		arp.addMapping("default_friends_config", "id", DefaultFriendsConfig.class);
		arp.addMapping("wx_local_wallet_recharge_item", "id", WxLocalWalletRechargeItem.class);
		arp.addMapping("payment_img", "id", PaymentImg.class);
		arp.addMapping("wallet_item_local", "id", WalletItemLocal.class);
		arp.addMapping("user_payment_img", "id", UserPaymentImg.class);


		arp.addMapping("wx_user_coin_local", "id", WxUserCoinLocal.class);
		arp.addMapping("wx_user_coin_item_local", "id", WxUserCoinItemLocal.class);
		arp.addMapping("wx_user_grab_red_item_local", "id", WxUserGrabRedItemLocal.class);
		arp.addMapping("wx_user_recharge_item_local", "id", WxUserRechargeItemLocal.class);
		arp.addMapping("wx_user_red_packet_local", "id", WxUserRedPacketLocal.class);
		arp.addMapping("wx_user_red_packet_item_local", "id", WxUserRedPacketItemLocal.class);
		arp.addMapping("wx_user_send_red_item_local", "id", WxUserSendRedItemLocal.class);
		arp.addMapping("wx_user_wallet_local", "id", WxUserWalletLocal.class);
		arp.addMapping("wx_user_withhold_count_local", "id", WxUserWithholdCountLocal.class);
		arp.addMapping("wx_user_withhold_item_local", "id", WxUserWithholdItemLocal.class);
		arp.addMapping("wx_wallet_local", "id", WxWalletLocal.class);
		arp.addMapping("wx_wallet_back_red_packet_items_local", "id", WxWalletBackRedPacketItemsLocal.class);
		arp.addMapping("wx_wallet_bank_cards_local", "id", WxWalletBankCardsLocal.class);
//		arp.addMapping("wx_wallet_bank_info_local", "id", WxWalletBankInfoLocal.class);
		arp.addMapping("wx_wallet_coin_local", "id", WxWalletCoinLocal.class);
		arp.addMapping("wx_wallet_coin_item_local", "id", WxWalletCoinItemLocal.class);
		arp.addMapping("wx_wallet_grab_red_item_local", "id", WxWalletGrabRedItemLocal.class);
		arp.addMapping("wx_wallet_info_local", "id", WxWalletInfoLocal.class);
		arp.addMapping("wx_wallet_recharge_item_local", "id", WxWalletRechargeItemLocal.class);
		arp.addMapping("wx_wallet_red_packet_random_local", "id", WxWalletRedPacketRandomLocal.class);
		arp.addMapping("wx_wallet_send_red_packet_local", "id", WxWalletSendRedPacketLocal.class);
		arp.addMapping("wx_wallet_withhold_count_local", "id", WxWalletWithholdCountLocal.class);
		arp.addMapping("wx_wallet_withhold_items_local", "id", WxWalletWithholdItemsLocal.class);

		arp.addMapping("real_name_certification", "id", RealNameCertification.class);


		arp.addMapping("sign_item", "id", SignItem.class);
		arp.addMapping("sign_task", "id", SignTask.class);
		arp.addMapping("sign_role", "id", SignRole.class);
		arp.addMapping("notice", "id", Notice.class);

		arp.addMapping("collect", "id", Collect.class);

		arp.addMapping("moments", "id", Moments.class);
		arp.addMapping("moments_comments", "id", MomentsComments.class);
		arp.addMapping("moments_likes", "id", MomentsLikes.class);
		arp.addMapping("temp_user_key", "id", TempUserKey.class);

		arp.addMapping("stranger_remark_name", "id", StrangerRemarkName.class);

		arp.addMapping("circle", "id", Circle.class);
		arp.addMapping("circle_apply", "id", CircleApply.class);
		arp.addMapping("circle_article", "id", CircleArticle.class);
		arp.addMapping("circle_article_comment", "id", CircleArticleComment.class);
		arp.addMapping("circle_article_like", "id", CircleArticleLike.class);
		arp.addMapping("circle_member", "id", CircleMember.class);
		arp.addMapping("circle_member_apply", "id", CircleMemberApply.class);
		arp.addMapping("circle_member_invite_code", "id", CircleMemberInviteCode.class);

		arp.addMapping("city", "id", City.class);
		arp.addMapping("provincial", "id", Provincial.class);

		arp.addMapping("circle_uid_circleid_setting", "id", CircleUidCircleidSetting.class);
		arp.addMapping("circle_uid_cityid_setting", "id", CircleUidCityidSetting.class);

		arp.addMapping("circle_view_setting", "id", CircleViewSetting.class);

		arp.addMapping("circle_msg", "id", CircleMsg.class);
		arp.addMapping("circle_complaint", "id", CircleComplaint.class);
		arp.addMapping("circle_log", "id", CircleLog.class);

		arp.addMapping("album", "id", Album.class);
		arp.addMapping("album_photo", "id", AlbumPhoto.class);
		arp.addMapping("request_add_friend_record", "id", RequestAddFriendRecord.class);
		arp.addMapping("wx_group_notice", "id", WxGroupNotice.class);
		arp.addMapping("wx_group_sign", "id", WxGroupSign.class);
		arp.addMapping("default_group", "id", DefaultGroup.class);
		arp.addMapping("label", "id", Label.class);
		arp.addMapping("group_msg", "id", GroupMsg.class);

	}
}


