
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseCircleUidCircleidSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleUidCircleidSetting extends BaseCircleUidCircleidSetting<CircleUidCircleidSetting> {
	public static final CircleUidCircleidSetting dao = new CircleUidCircleidSetting().dao();
}
