
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseCircleMemberApply;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleMemberApply extends BaseCircleMemberApply<CircleMemberApply> {
	public static final CircleMemberApply dao = new CircleMemberApply().dao();

	private List<CircleMemberInviteCode> inviteCodeList;
	private Circle circleInfo;
	private String applyNick;

	public String getApplyNick() {
		return applyNick;
	}

	public void setApplyNick(String applyNick) {
		this.applyNick = applyNick;
	}

	public List<CircleMemberInviteCode> getInviteCodeList() {
		return inviteCodeList;
	}

	public void setInviteCodeList(List<CircleMemberInviteCode> inviteCodeList) {
		this.inviteCodeList = inviteCodeList;
	}

	public Circle getCircleInfo() {
		return circleInfo;
	}

	public void setCircleInfo(Circle circleInfo) {
		this.circleInfo = circleInfo;
	}
}
