
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseCircleMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleMember extends BaseCircleMember<CircleMember> {
	public static final CircleMember dao = new CircleMember().dao();

	private String pinyin;

	private String shoupin;

	public String getShoupin() {
		return shoupin;
	}

	public void setShoupin(String shoupin) {
		this.shoupin = shoupin;
	}

	public String getPinyin() {
		return pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}
}
