
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseCircleMsg;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleMsg extends BaseCircleMsg<CircleMsg> {
	public static final CircleMsg dao = new CircleMsg().dao();
}
