
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseCircle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Circle extends BaseCircle<Circle> {
	public static final Circle dao = new Circle().dao();
}
