
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseCircleMemberInviteCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleMemberInviteCode extends BaseCircleMemberInviteCode<CircleMemberInviteCode> {
	public static final CircleMemberInviteCode dao = new CircleMemberInviteCode().dao();
	private String inviteNick;

	public String getInviteNick() {
		return inviteNick;
	}

	public void setInviteNick(String inviteNick) {
		this.inviteNick = inviteNick;
	}
}
