
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseCircleLog;

import java.util.List;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleLog extends BaseCircleLog<CircleLog> {
	List<User> inviteUsers;

	public List<User> getInviteUsers() {
		return inviteUsers;
	}

	public void setInviteUsers(List<User> inviteUsers) {
		this.inviteUsers = inviteUsers;
	}

	public static final CircleLog dao = new CircleLog().dao();
}
