
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseCollect;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collect extends BaseCollect<Collect> {
	public static final Collect dao = new Collect().dao();
}
