
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseGroupMsg;

import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupMsg extends BaseGroupMsg<GroupMsg> {
	public static final GroupMsg dao = new GroupMsg().dao();

	private String nicks = "";
	private String groups = "";
	private Integer num;

	private List<Map<String, String>> info;

	public List<Map<String, String>> getInfo() {
		return info;
	}

	public void setInfo(List<Map<String, String>> info) {
		this.info = info;
	}

	public String getGroups() {
		return groups;
	}

	public void setGroups(String groups) {
		this.groups = groups;
	}

	public String getNicks() {
		return nicks;
	}

	public void setNicks(String nicks) {
		this.nicks = nicks;
	}

	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}
}
