
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Img extends BaseImg<Img> {
	public static final Img dao = new Img().dao();

	public static interface Status {
		/**
		 * 正常
		 */
		short NORMAL = 1;

		/**
		 * 违规
		 */
		short INVALID = 2;
	}

	public static interface ComeFrom {
		/**
		 * IM上传
		 */
		short IM_UPLOAD = 1;

		/**
		 * 博客上传
		 */
		short BLOG_UPLOAD = 2;

		/**
		 * 修改头像
		 */
		short MODIFY_AVATAR = 3;

		/**
		 * 案例提交上传
		 */
		short	CASE_UPLOAD	= 4;
		/**
		 * Wx上传
		 */
		short	WX_UPLOAD	= 5;

	}
}
