
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseIpInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IpInfo extends BaseIpInfo<IpInfo> {
	public static final IpInfo dao = new IpInfo().dao();
}
