
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseLoginTaskItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginTaskItems extends BaseLoginTaskItems<LoginTaskItems> {
	public static final LoginTaskItems dao = new LoginTaskItems().dao();
}
