
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseMoments;

import java.util.List;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Moments extends BaseMoments<Moments> {
	public static final Moments dao = new Moments().dao();

	private Map<String,String> publisherInfo;

	public String getNick() {
		return nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getAvatar() {
		return avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	public String getRemarkName() {
		return remarkName;
	}

	public void setRemarkName(String remarkName) {
		this.remarkName = remarkName;
	}

	private String nick;
	private String avatar;
	private String remarkName;

	private List<MomentsComments> comments;
	private List<MomentsLikes> likes;

	private Integer likesCount;

	public Map<String, String> getPublisherInfo() {
		return publisherInfo;
	}

	public void setPublisherInfo(Map<String, String> publisherInfo) {
		this.publisherInfo = publisherInfo;
	}


	public List<MomentsComments> getComments() {
		return comments;
	}

	public void setComments(List<MomentsComments> comments) {
		this.comments = comments;
	}

	public List<MomentsLikes> getLikes() {
		return likes;
	}

	public void setLikes(List<MomentsLikes> likes) {
		this.likes = likes;
	}

	public Integer getLikesCount() {
		return likesCount;
	}

	public void setLikesCount(Integer likesCount) {
		this.likesCount = likesCount;
	}
}
