
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseMomentsComments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MomentsComments extends BaseMomentsComments<MomentsComments> {
	public static final MomentsComments dao = new MomentsComments().dao();

	private String nick;
	private String remarkName;

	public String getNick() {
		return nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getRemarkName() {
		return remarkName;
	}

	public void setRemarkName(String remarkName) {
		this.remarkName = remarkName;
	}
}
