
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseMomentsLikes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MomentsLikes extends BaseMomentsLikes<MomentsLikes> {
	public static final MomentsLikes dao = new MomentsLikes().dao();

	private String nick;
	private String remarkName;

	public String getNick() {
		return nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public String getRemarkName() {
		return remarkName;
	}

	public void setRemarkName(String remarkName) {
		this.remarkName = remarkName;
	}
}
