
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseOauth2Client;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Oauth2Client extends BaseOauth2Client<Oauth2Client> {
	public static final Oauth2Client dao = new Oauth2Client().dao();
}
