
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseProvincial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Provincial extends BaseProvincial<Provincial> {
	public static final Provincial dao = new Provincial().dao();
}
