
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseRealNameCertification;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RealNameCertification extends BaseRealNameCertification<RealNameCertification> {
	public static final RealNameCertification dao = new RealNameCertification().dao();
}
