
package org.tio.sitexxx.service.model.main;

import org.tio.jfinal.kit.Ret;
import org.tio.sitexxx.service.model.main.base.BaseRequestAddFriendRecord;
import org.tio.sitexxx.service.utils.RetUtils;
import org.tio.sitexxx.service.vo.Const;

import java.util.List;
import java.util.Objects;

/**
 * Generated by JFinal.
 */
public class RequestAddFriendRecord extends BaseRequestAddFriendRecord<RequestAddFriendRecord> {
	public static final RequestAddFriendRecord dao = new RequestAddFriendRecord().dao();
}
