
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseSignTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SignTask extends BaseSignTask<SignTask> {
	public static final SignTask dao = new SignTask().dao();
}
