
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseSmsLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsLog extends BaseSmsLog<SmsLog> {
	public static final SmsLog dao = new SmsLog().dao();
}
