
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseStatOnline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StatOnline extends BaseStatOnline<StatOnline> {
	public static final StatOnline dao = new StatOnline().dao();
}
