
package org.tio.sitexxx.service.model.main;


import org.tio.sitexxx.service.model.main.base.BaseStrangerRemarkName;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StrangerRemarkName extends BaseStrangerRemarkName<StrangerRemarkName> {
	public static final StrangerRemarkName dao = new StrangerRemarkName().dao();
}
