
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseUserLastLoginTime;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserLastLoginTime extends BaseUserLastLoginTime<UserLastLoginTime> {
	public static final UserLastLoginTime dao = new UserLastLoginTime().dao();
}
