
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseUserlogModifyNick;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserlogModifyNick extends BaseUserlogModifyNick<UserlogModifyNick> {
	public static final UserlogModifyNick dao = new UserlogModifyNick().dao();
}
