
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.UserThird.SubTable;
import org.tio.sitexxx.service.model.main.base.BaseUserThirdWx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserThirdWx extends BaseUserThirdWx<UserThirdWx> implements SubTable {
	public static final UserThirdWx dao = new UserThirdWx().dao();
}
