
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.UserThird.SubTable;
import org.tio.sitexxx.service.model.main.base.BaseUserThirdQq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserThirdQq extends BaseUserThirdQq<UserThirdQq> implements SubTable {
	public static final UserThirdQq dao = new UserThirdQq().dao();
}
