
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseUserAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserAddress extends BaseUserAddress<UserAddress> {
	public static final UserAddress dao = new UserAddress().dao();
}
