
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseUserInfoSyn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfoSyn extends BaseUserInfoSyn<UserInfoSyn> {
	public static final UserInfoSyn dao = new UserInfoSyn().dao();
}
