
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseUserToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserToken extends BaseUserToken<UserToken> {
	public static final UserToken dao = new UserToken().dao();
}
