
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseUserThird;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserThird extends BaseUserThird<UserThird> {
	public static final UserThird dao = new UserThird().dao();

	/**
	 * 第三方登录类型
	 * @author tanyaowu
	 *
	 */
	public interface Type {
		/**
		 * PC版QQ
		 */
		int QQ = 1;

		/**
		 *  移动版QQ
		 */
		int QQ_MOBILE = 11;

		/**
		 * PC版微信
		 */
		int WX = 2;

		/**
		 *  移动版微信
		 */
		int WX_MOBILE = 22;

		/**
		 *  微信公众号
		 */
		int WX_OPEN = 222;

		/**
		 * PC版微博
		 */
		int WB = 3;

		/**
		 *  移动版微博
		 */
		int WB_MOBILE = 33;

		/**
		 * PC版抖音
		 */
		int DOUYIN = 4;

		/**
		 * PC版OSC
		 */
		int OSC = 5;

		/**
		 * IOS游客登录
		 */
		int APPLE = 9999;
	}

	/**
	 * @param type
	 * @return
	 * @author lixinji
	 * 2020年12月17日 下午3:30:36
	 */
	public static String getThirdLoginTitle(Integer type) {
		switch (type) {
		case UserThird.Type.QQ:
		case UserThird.Type.QQ_MOBILE:
			return "QQ";

		case UserThird.Type.WX:
		case UserThird.Type.WX_MOBILE:
		case UserThird.Type.WX_OPEN:
			return "微信";
		case UserThird.Type.WB:
		case UserThird.Type.WB_MOBILE:
			return "微博";

		case UserThird.Type.DOUYIN:
			return "抖音";

		case UserThird.Type.OSC:
			return "OSC";

		case UserThird.Type.APPLE:
			return "苹果";

		default:
			return "其它";
		}
	}

	private SubTable subTable = null;

	public SubTable getSubTable() {
		return subTable;
	}

	public void setSubTable(SubTable subTable) {
		this.subTable = subTable;
	}

	public static interface SubTable {
		/**
		 * user_third表的id字段
		 */
		public void setUserThirdId(java.lang.Integer userThirdId);

		public boolean save();
		//		{
		//			set("user_third_id", userThirdId);
		//		}

		//		/**
		//		 * user_third表的id字段
		//		 */
		//		public java.lang.Integer getUserThirdId() {
		//			return getInt("user_third_id");
		//		}
	}
}
