
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseVideoOperLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VideoOperLog extends BaseVideoOperLog<VideoOperLog> {
	public static final VideoOperLog dao = new VideoOperLog().dao();
}
