
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxApp extends BaseWxApp<WxApp> {
	public static final WxApp dao = new WxApp().dao();
}
