
package org.tio.sitexxx.service.model.main;

import java.util.Date;

import org.tio.sitexxx.service.model.main.base.BaseWxCallLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxCallLog extends BaseWxCallLog<WxCallLog> {
	public static final WxCallLog dao = new WxCallLog().dao();

	public static WxCallLog from(WxCallItem item) {
		WxCallLog ret = new WxCallLog();
		ret.setCallid(item.getId());
		ret.setTime(new Date());
		return ret;
	}
}
