
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxChatDelItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxChatDelItem extends BaseWxChatDelItem<WxChatDelItem> {
	public static final WxChatDelItem dao = new WxChatDelItem().dao();
}
