
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxChatGroupItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxChatGroupItem extends BaseWxChatGroupItem<WxChatGroupItem> {
	public static final WxChatGroupItem dao = new WxChatGroupItem().dao();

	/**
	 * 是否免打扰：1：是；2：否
	 */
	public void setMsgfreeflag(java.lang.Short msgfreeflag) {
		put("msgfreeflag", msgfreeflag);
	}

	/**
	 * 是否免打扰：1：是；2：否
	 */
	public java.lang.Short getMsgfreeflag() {
		return getShort("msgfreeflag");
	}
}
