
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxFriendApplyItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriendApplyItems extends BaseWxFriendApplyItems<WxFriendApplyItems> {
	public static final WxFriendApplyItems dao = new WxFriendApplyItems().dao();

}
