
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxFriendApplyLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriendApplyLog extends BaseWxFriendApplyLog<WxFriendApplyLog> {
	public static final WxFriendApplyLog dao = new WxFriendApplyLog().dao();

	private String sessionid;

	private String ip;

	public String getSessionid() {
		return sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}
}
