
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxFriendMeta;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriendMeta extends BaseWxFriendMeta<WxFriendMeta> {
	public static final WxFriendMeta dao = new WxFriendMeta().dao();
}
