
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxGroup;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroup extends BaseWxGroup<WxGroup> {
	public List<WxGroupNotice> getGroupNotices() {
		return groupNotices;
	}

	public void setGroupNotices(List<WxGroupNotice> groupNotices) {
		this.groupNotices = groupNotices;
	}

	private List<WxGroupNotice> groupNotices;

	public static final WxGroup	dao						= new WxGroup().dao();
	public static final String	DEFAULT_GROUP_AVATAR	= "/img/group.png";

	public void setMetaid(java.lang.Long metaid) {
		put("metaid", metaid);
	}

	public java.lang.Long getMetaid() {
		return getLong("metaid");
	}

	/**
	 * 群人数
	 */
	public void setJoinnum(java.lang.Short joinnum) {
		put("joinnum", joinnum);
	}

	/**
	 * 群人数
	 */
	public java.lang.Short getJoinnum() {
		return getShort("joinnum");
	}

	/**
	 * 所有都激活：1：是；2：否
	 */
	public void setAllactflag(java.lang.Short allactflag) {
		put("allactflag", allactflag);
	}

	/**
	 * 所有都激活：1：是；2：否
	 */
	public java.lang.Short getAllactflag() {
		return getShort("allactflag");
	}

	/**
	 * 所有都有消息：1：是；2：否
	 */
	public void setAllstartflag(java.lang.Short allstartflag) {
		put("allstartflag", allstartflag);
	}

	/**
	 * 所有都有消息：1：是；2：否
	 */
	public java.lang.Short getAllstartflag() {
		return getShort("allstartflag");
	}

	/**
	 * 全员禁用：1：是；2：否
	 */
	public void setForbiddenflag(java.lang.Short forbiddenflag) {
		put("forbiddenflag", forbiddenflag);
	}

	/**
	 * 全员禁用：1：是；2：否
	 */
	public java.lang.Short getForbiddenflag() {
		return getShort("forbiddenflag");
	}
}
