
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxGroupMetaBak;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupMetaBak extends BaseWxGroupMetaBak<WxGroupMetaBak> {
	public static final WxGroupMetaBak dao = new WxGroupMetaBak().dao();
}
