
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxGroupUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupUser extends BaseWxGroupUser<WxGroupUser> {
	public static final WxGroupUser dao = new WxGroupUser().dao();

	/**
	 * 群列表展示字段
	 * @author lixinji
	 */
	public static interface ViewStatus {
		/**
		 *  正常
		 */
		short NORMAL = 1;

		/**
		 * 未消息激活
		 */
		short NO_ACT = 2;

		/**
		 * 删除
		 */
		short DEL = 3;
	}

	/**
	 * 群用户状态
	 * @author lixinji
	 */
	public static interface Status {
		/**
		 *  正常
		 */
		short NORMAL = 1;

		/**
		 * 退出
		 */
		short OUT = 2;

		/**
		 * 被踢
		 */
		short KICK = 3;
	}
}
