
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxGroupUserInviteLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupUserInviteLog extends BaseWxGroupUserInviteLog<WxGroupUserInviteLog> {
	public static final WxGroupUserInviteLog dao = new WxGroupUserInviteLog().dao();
}
