
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxGroupNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupNotice extends BaseWxGroupNotice<WxGroupNotice> {
	public static final WxGroupNotice dao = new WxGroupNotice().dao();
}
