
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxGroupSign;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupSign extends BaseWxGroupSign<WxGroupSign> {
	public static final WxGroupSign dao = new WxGroupSign().dao();

	private Long timeStamp;

	public Long getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(Long timeStamp) {
		this.timeStamp = timeStamp;
	}

	private Integer day;

	public Integer getMonth() {
		return month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	private Integer month;

	public Integer getDay() {
		return day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}
}
