
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxGroupMsgUserOper;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupMsgUserOper extends BaseWxGroupMsgUserOper<WxGroupMsgUserOper> {
	public static final WxGroupMsgUserOper dao = new WxGroupMsgUserOper().dao();
}
