
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxGroupInblack;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupInblack extends BaseWxGroupInblack<WxGroupInblack> {
	public static final WxGroupInblack dao = new WxGroupInblack().dao();
}
