
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxJpushUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxJpushUser extends BaseWxJpushUser<WxJpushUser> {
	public static final WxJpushUser dao = new WxJpushUser().dao();
}
