
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxReadAck;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxReadAck extends BaseWxReadAck<WxReadAck> {
	public static final WxReadAck dao = new WxReadAck().dao();
}
