
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxSynItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxSynItem extends BaseWxSynItem<WxSynItem> {
	public static final WxSynItem dao = new WxSynItem().dao();
}
