
package org.tio.sitexxx.service.model.main;

import java.util.Map;

import org.tio.sitexxx.service.model.main.base.BaseWxUserGrabRedItem;
import org.tio.sitexxx.service.vo.PayConst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserGrabRedItem extends BaseWxUserGrabRedItem<WxUserGrabRedItem> {
	public static final WxUserGrabRedItem dao = new WxUserGrabRedItem().dao();

	public Map<String, Object> toAllMap() {
		Map<String, Object> map = this._getAttrs();
		map.put(PayConst.ApiClassName.API_MAP_KEY, PayConst.ApiClassName.GRAB_REDPACKET);
		return map;
	}

	public static WxUserGrabRedItem toBean(Map<String, Object> map) {
		map.remove(PayConst.ApiClassName.API_MAP_KEY);
		WxUserGrabRedItem redItem = new WxUserGrabRedItem();
		redItem._setAttrs(map);
		return redItem;
	}

	public void setNick(java.lang.String nick) {
		put("nick", nick);
	}

	public java.lang.String getNick() {
		return getStr("nick");
	}

	public void setAvatar(java.lang.String avatar) {
		put("avatar", avatar);
	}

	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
}
