
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserFavorites;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserFavorites extends BaseWxUserFavorites<WxUserFavorites> {
	public static final WxUserFavorites dao = new WxUserFavorites().dao();
}
