
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserBlackItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserBlackItems extends BaseWxUserBlackItems<WxUserBlackItems> {
	public static final WxUserBlackItems dao = new WxUserBlackItems().dao();
}
