
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserRedPacketItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserRedPacketItemLocal extends BaseWxUserRedPacketItem<WxUserRedPacketItemLocal> {
	public static final WxUserRedPacketItemLocal dao = new WxUserRedPacketItemLocal().dao();
}
