
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserWallet;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserWalletLocal extends BaseWxUserWallet<WxUserWalletLocal> {
	public static final WxUserWalletLocal dao = new WxUserWalletLocal().dao();

	/**
	 * 
	 * @param map
	 * @return
	 * @author lixinji
	 * 2021年2月3日 上午11:06:06
	 */
	public static WxUserWalletLocal mapToBean(Map<String, Object> map) {
		WxUserWalletLocal userWallet = new WxUserWalletLocal();
		userWallet._setAttrs(map);
		return userWallet;
	}
}
