
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserRedPacketItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserRedPacketItem extends BaseWxUserRedPacketItem<WxUserRedPacketItem> {
	public static final WxUserRedPacketItem dao = new WxUserRedPacketItem().dao();
}
