
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserWithholdItemLocal;
import org.tio.sitexxx.service.vo.PayConst;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserWithholdItemLocal extends BaseWxUserWithholdItemLocal<WxUserWithholdItemLocal> {
	public static final WxUserWithholdItemLocal dao = new WxUserWithholdItemLocal().dao();

	public Map<String, Object> toAllMap() {
		Map<String, Object> map = this._getAttrs();
		map.put(PayConst.ApiClassName.API_MAP_KEY, PayConst.ApiClassName.WITHHOLD_QUERY);
		return map;
	}

	public static WxUserWithholdItemLocal toBean(Map<String, Object> map) {
		map.remove(PayConst.ApiClassName.API_MAP_KEY);
		WxUserWithholdItemLocal withholdItem = new WxUserWithholdItemLocal();
		withholdItem._setAttrs(map);
		return withholdItem;
	}
}
