
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserWithholdCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserWithholdCountLocal extends BaseWxUserWithholdCount<WxUserWithholdCountLocal> {
	public static final WxUserWithholdCountLocal dao = new WxUserWithholdCountLocal().dao();
}
