package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserMergeData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserMergeData extends BaseWxUserMergeData<WxUserMergeData> {
	public static final WxUserMergeData dao = new WxUserMergeData().dao();
}

