
package org.tio.sitexxx.service.model.main;

import java.util.Map;

import org.tio.sitexxx.service.model.main.base.BaseWxUserWallet;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserWallet extends BaseWxUserWallet<WxUserWallet> {
	public static final WxUserWallet dao = new WxUserWallet().dao();

	/**
	 * 
	 * @param map
	 * @return
	 * @author lixinji
	 * 2021年2月3日 上午11:06:06
	 */
	public static WxUserWallet mapToBean(Map<String, Object> map) {
		WxUserWallet userWallet = new WxUserWallet();
		userWallet._setAttrs(map);
		return userWallet;
	}
}
