
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserSendRedItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserSendRedItemLocal extends BaseWxUserSendRedItem<WxUserSendRedItemLocal> {
	public static final WxUserSendRedItemLocal dao = new WxUserSendRedItemLocal().dao();

	public void setNick(String nick) {
		put("nick", nick);
	}

	public String getNick() {
		return getStr("nick");
	}

	public void setAvatar(String avatar) {
		put("avatar", avatar);
	}

	public String getAvatar() {
		return getStr("avatar");
	}
}
