
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserRedPacket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserRedPacketLocal extends BaseWxUserRedPacket<WxUserRedPacketLocal> {
	public static final WxUserRedPacketLocal dao = new WxUserRedPacketLocal().dao();
}
