
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserReport;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserReport extends BaseWxUserReport<WxUserReport> {
	public static final WxUserReport dao = new WxUserReport().dao();
}
