
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserWithholdCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserWithholdCount extends BaseWxUserWithholdCount<WxUserWithholdCount> {
	public static final WxUserWithholdCount dao = new WxUserWithholdCount().dao();
}
