
package org.tio.sitexxx.service.model.main;

import java.util.Map;

import org.tio.sitexxx.service.model.main.base.BaseWxUserWithholdItem;
import org.tio.sitexxx.service.vo.PayConst;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserWithholdItem extends BaseWxUserWithholdItem<WxUserWithholdItem> {
	public static final WxUserWithholdItem dao = new WxUserWithholdItem().dao();

	public Map<String, Object> toAllMap() {
		Map<String, Object> map = this._getAttrs();
		map.put(PayConst.ApiClassName.API_MAP_KEY, PayConst.ApiClassName.WITHHOLD_QUERY);
		return map;
	}

	public static WxUserWithholdItem toBean(Map<String, Object> map) {
		map.remove(PayConst.ApiClassName.API_MAP_KEY);
		WxUserWithholdItem withholdItem = new WxUserWithholdItem();
		withholdItem._setAttrs(map);
		return withholdItem;
	}
}
