
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserGrabRedItem;
import org.tio.sitexxx.service.vo.PayConst;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserGrabRedItemLocal extends BaseWxUserGrabRedItem<WxUserGrabRedItemLocal> {
	public static final WxUserGrabRedItemLocal dao = new WxUserGrabRedItemLocal().dao();

	public Map<String, Object> toAllMap() {
		Map<String, Object> map = this._getAttrs();
		map.put(PayConst.ApiClassName.API_MAP_KEY, PayConst.ApiClassName.GRAB_REDPACKET);
		return map;
	}

	public static WxUserGrabRedItemLocal toBean(Map<String, Object> map) {
		map.remove(PayConst.ApiClassName.API_MAP_KEY);
		WxUserGrabRedItemLocal redItem = new WxUserGrabRedItemLocal();
		redItem._setAttrs(map);
		return redItem;
	}

	public void setNick(String nick) {
		put("nick", nick);
	}

	public String getNick() {
		return getStr("nick");
	}

	public void setAvatar(String avatar) {
		put("avatar", avatar);
	}

	public String getAvatar() {
		return getStr("avatar");
	}
}
