
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserRechargeItem;
import org.tio.sitexxx.service.vo.PayConst;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserRechargeItemLocal extends BaseWxUserRechargeItem<WxUserRechargeItemLocal> {
	public static final WxUserRechargeItemLocal dao = new WxUserRechargeItemLocal().dao();

	public Map<String, Object> toAllMap() {
		Map<String, Object> map = this._getAttrs();
		map.put(PayConst.ApiClassName.API_MAP_KEY, PayConst.ApiClassName.RECHARGE_QUERY);
		return map;
	}

	public static WxUserRechargeItemLocal toBean(Map<String, Object> map) {
		map.remove(PayConst.ApiClassName.API_MAP_KEY);
		WxUserRechargeItemLocal regRechargeItem = new WxUserRechargeItemLocal();
		regRechargeItem._setAttrs(map);
		return regRechargeItem;
	}
}
