
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserRedPacket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserRedPacket extends BaseWxUserRedPacket<WxUserRedPacket> {
	public static final WxUserRedPacket dao = new WxUserRedPacket().dao();
}
