
package org.tio.sitexxx.service.model.main;

import java.util.Map;

import org.tio.sitexxx.service.model.main.base.BaseWxUserRealname;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserRealname extends BaseWxUserRealname<WxUserRealname> {
	public static final WxUserRealname dao = new WxUserRealname().dao();

	/**
	 * @param map
	 * @return
	 * @author lixinji
	 * 2021年2月3日 下午4:07:40
	 */
	public static WxUserRealname mapToBean(Map<String, Object> map) {
		WxUserRealname bean = new WxUserRealname();
		bean._setAttrs(map);
		return bean;
	}
}
