
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxUserSendRedItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserSendRedItem extends BaseWxUserSendRedItem<WxUserSendRedItem> {
	public static final WxUserSendRedItem dao = new WxUserSendRedItem().dao();

	public void setNick(java.lang.String nick) {
		put("nick", nick);
	}

	public java.lang.String getNick() {
		return getStr("nick");
	}

	public void setAvatar(java.lang.String avatar) {
		put("avatar", avatar);
	}

	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
}
