
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletInfoLocal extends BaseWxWalletInfo<WxWalletInfoLocal> {
	public static final WxWalletInfoLocal dao = new WxWalletInfoLocal().dao();
}
