
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletWithholdCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletWithholdCount extends BaseWxWalletWithholdCount<WxWalletWithholdCount> {
	public static final WxWalletWithholdCount dao = new WxWalletWithholdCount().dao();
}
