
package org.tio.sitexxx.service.model.main;

import java.util.Map;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletSendRedPacket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletSendRedPacket extends BaseWxWalletSendRedPacket<WxWalletSendRedPacket> {
	public static final WxWalletSendRedPacket dao = new WxWalletSendRedPacket().dao();

	public static WxWalletSendRedPacket mapToBean(Map<String, Object> map) {
		WxWalletSendRedPacket redPacket = new WxWalletSendRedPacket();
		redPacket._setOrPut(map);
		return redPacket;
	}

	public void setNick(java.lang.String nick) {
		put("nick", nick);
	}

	public java.lang.String getNick() {
		return getStr("nick");
	}

	public void setAvatar(java.lang.String avatar) {
		put("avatar", avatar);
	}

	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
}
