
package org.tio.sitexxx.service.model.main;

import java.util.Map;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletBankCards;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletBankCards extends BaseWxWalletBankCards<WxWalletBankCards> {
	public static final WxWalletBankCards dao = new WxWalletBankCards().dao();

	public static WxWalletBankCards mapToBean(Map<String, Object> map) {
		WxWalletBankCards bankCards = new WxWalletBankCards();
		bankCards._setOrPut(map);
		return bankCards;
	}
}
