
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletWithholdCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletWithholdCountLocal extends BaseWxWalletWithholdCount<WxWalletWithholdCountLocal> {
	public static final WxWalletWithholdCountLocal dao = new WxWalletWithholdCountLocal().dao();
}
