
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletBackRedPacketItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletBackRedPacketItems extends BaseWxWalletBackRedPacketItems<WxWalletBackRedPacketItems> {
	public static final WxWalletBackRedPacketItems dao = new WxWalletBackRedPacketItems().dao();
}
