
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletRedPacketRandom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletRedPacketRandomLocal extends BaseWxWalletRedPacketRandom<WxWalletRedPacketRandomLocal> {
	public static final WxWalletRedPacketRandomLocal dao = new WxWalletRedPacketRandomLocal().dao();
}
