
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletBankInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletBankInfoLocal extends BaseWxWalletBankInfo<WxWalletBankInfoLocal> {
	public static final WxWalletBankInfoLocal dao = new WxWalletBankInfoLocal().dao();
}
