
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletSendRedPacket;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletSendRedPacketLocal extends BaseWxWalletSendRedPacket<WxWalletSendRedPacketLocal> {
	public static final WxWalletSendRedPacketLocal dao = new WxWalletSendRedPacketLocal().dao();

	public static WxWalletSendRedPacketLocal mapToBean(Map<String, Object> map) {
		WxWalletSendRedPacketLocal redPacket = new WxWalletSendRedPacketLocal();
		redPacket._setOrPut(map);
		return redPacket;
	}

	public void setNick(String nick) {
		put("nick", nick);
	}

	public String getNick() {
		return getStr("nick");
	}

	public void setAvatar(String avatar) {
		put("avatar", avatar);
	}

	public String getAvatar() {
		return getStr("avatar");
	}
}
