
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletBankInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletBankInfo extends BaseWxWalletBankInfo<WxWalletBankInfo> {
	public static final WxWalletBankInfo dao = new WxWalletBankInfo().dao();
}
