
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletCoinItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletCoinItemLocal extends BaseWxWalletCoinItem<WxWalletCoinItemLocal> {
	public static final WxWalletCoinItemLocal dao = new WxWalletCoinItemLocal().dao();
}
