
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletCoinItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletCoinItem extends BaseWxWalletCoinItem<WxWalletCoinItem> {
	public static final WxWalletCoinItem dao = new WxWalletCoinItem().dao();
}
