
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletBackRedPacketItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletBackRedPacketItemsLocal extends BaseWxWalletBackRedPacketItems<WxWalletBackRedPacketItemsLocal> {
	public static final WxWalletBackRedPacketItemsLocal dao = new WxWalletBackRedPacketItemsLocal().dao();
}
