
package org.tio.sitexxx.service.model.main;

import java.util.Map;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletGrabRedItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletGrabRedItem extends BaseWxWalletGrabRedItem<WxWalletGrabRedItem> {
	public static final WxWalletGrabRedItem dao = new WxWalletGrabRedItem().dao();

	public static WxWalletGrabRedItem mapToBean(Map<String, Object> map) {
		WxWalletGrabRedItem redPacket = new WxWalletGrabRedItem();
		redPacket._setOrPut(map);
		return redPacket;
	}

	public void setNick(java.lang.String nick) {
		put("nick", nick);
	}

	public java.lang.String getNick() {
		return getStr("nick");
	}

	public void setAvatar(java.lang.String avatar) {
		put("avatar", avatar);
	}

	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
}
