
package org.tio.sitexxx.service.model.main;

import org.tio.sitexxx.service.model.main.base.BaseWxWalletInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletInfo extends BaseWxWalletInfo<WxWalletInfo> {
	public static final WxWalletInfo dao = new WxWalletInfo().dao();
}
