
package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgOperLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgOperLog extends BaseMgOperLog<MgOperLog> {
	public static final MgOperLog dao = new MgOperLog().dao();
}
