
package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgRole extends BaseMgRole<MgRole> {
	public static final MgRole dao = new MgRole().dao();
}
