
package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgRoleAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgRoleAuth extends BaseMgRoleAuth<MgRoleAuth> {
	public static final MgRoleAuth dao = new MgRoleAuth().dao();
}
