
package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgUserBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MgUserBase extends BaseMgUserBase<MgUserBase> {
	public static final MgUserBase dao = new MgUserBase().dao();
}
