
package org.tio.mg.service.model.mg;

import org.tio.mg.service.model.mg.base.BaseMgUser;
import org.tio.sitexxx.service.vo.Const;

/**
 * Generated by JFinal.
 */
/**
 * 
 * @author xufei
 * 2020年6月2日 下午3:39:52
 */
@SuppressWarnings("serial")
public class MgUser extends BaseMgUser<MgUser> {
	public static final MgUser dao = new MgUser().dao();
	
	private Short baseflag = Const.YesOrNo.NO;
	
	public Short getBaseflag() {
		return baseflag;
	}

	public void setBaseflag(Short baseflag) {
		this.baseflag = baseflag;
	}

	public String getRids() {
		return getStr("rids");
	}

	public void setRids(String rids) {
		put("rids", rids);
	}

	/**
	 * 姓名
	 */
	public void setRealname(java.lang.String realname) {
		put("realname", realname);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * 部门名称
	 */
	public void setDeptname(java.lang.String deptname) {
		put("deptname", deptname);
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getDeptname() {
		return getStr("deptname");
	}
	
	/**
	 * 部门名称
	 */
	public void setRolename(java.lang.String rolename) {
		put("rolename", rolename);
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getRolename() {
		return getStr("rolename");
	}

	/**
	 * 绑定邮箱
	 */
	public void setEmail(java.lang.String email) {
		put("email", email);
	}
	
	/**
	 * 绑定邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 职位
	 */
	public void setPosition(java.lang.String position) {
		put("position", position);
	}
	
	/**
	 * 职位
	 */
	public java.lang.String getPosition() {
		return getStr("position");
	}
}
