
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupNotice<M extends BaseWxGroupNotice<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 群id
	 */
	public void setGroupid(Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 群id
	 */
	public Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 申请人uid
	 */
	public void setIstop(Integer istop) {
		set("istop", istop);
	}
	
	/**
	 * 申请人uid
	 */
	public Integer getIstop() {
		return getInt("istop");
	}

	/**
	 * 申请信息
	 */
	public void setContent(String content) {
		set("content", content);
	}
	
	/**
	 * 申请信息
	 */
	public String getContent() {
		return getStr("content");
	}

	/**
	 *  群创建时间
	 */
	public void setToptime(java.util.Date toptime) {
		set("toptime", toptime);
	}

	/**
	 *  群创建时间
	 */
	public java.util.Date getToptime() {
		return getDate("toptime");
	}


	/**
	 *  群创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 *  群创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 *  群资料更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 *  群资料更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

