
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserAgent<M extends BaseUserAgent<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.320
	 */
	public void setUserAgent(java.lang.String userAgent) {
		set("userAgent", userAgent);
	}
	
	/**
	 * Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.320
	 */
	public java.lang.String getUserAgent() {
		return getStr("userAgent");
	}

	/**
	 * Internet Explorer, Chrome
	 */
	public void setAgentName(java.lang.String agentName) {
		set("agentName", agentName);
	}
	
	/**
	 * Internet Explorer, Chrome
	 */
	public java.lang.String getAgentName() {
		return getStr("agentName");
	}

	/**
	 * 62, 11
	 */
	public void setAgentVersionMajor(java.lang.String agentVersionMajor) {
		set("agentVersionMajor", agentVersionMajor);
	}
	
	/**
	 * 62, 11
	 */
	public java.lang.String getAgentVersionMajor() {
		return getStr("agentVersionMajor");
	}

	/**
	 * Windows NT
	 */
	public void setOsName(java.lang.String osName) {
		set("osName", osName);
	}
	
	/**
	 * Windows NT
	 */
	public java.lang.String getOsName() {
		return getStr("osName");
	}

	/**
	 * Windows 10.0
	 */
	public void setOsVersion(java.lang.String osVersion) {
		set("osVersion", osVersion);
	}
	
	/**
	 * Windows 10.0
	 */
	public java.lang.String getOsVersion() {
		return getStr("osVersion");
	}

	/**
	 * 是否是移动设备：1：是；2：不是
	 */
	public void setIsMobile(java.lang.Short isMobile) {
		set("isMobile", isMobile);
	}
	
	/**
	 * 是否是移动设备：1：是；2：不是
	 */
	public java.lang.Short getIsMobile() {
		return getShort("isMobile");
	}

	/**
	 * 设备类型
	 */
	public void setDeviceClass(java.lang.String deviceClass) {
		set("deviceClass", deviceClass);
	}
	
	/**
	 * 设备类型
	 */
	public java.lang.String getDeviceClass() {
		return getStr("deviceClass");
	}

}

