
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserThird<M extends BaseUserThird<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 用户昵称
	 */
	public void setNick(java.lang.String nick) {
		set("nick", nick);
	}
	
	/**
	 * 用户昵称
	 */
	public java.lang.String getNick() {
		return getStr("nick");
	}

	/**
	 * 用户头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 用户头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}
	
	public java.lang.String getUnionid() {
		return getStr("unionid");
	}

	/**
	 * 第三方登录类型：
1、PC版QQ，
2、微信，
3、微博，
11、移动版QQ、
22、移动版微信
33、移动版微博

	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 第三方登录类型：
1、PC版QQ，
2、微信，
3、微博，
11、移动版QQ、
22、移动版微信
33、移动版微博

	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 1：男， 2：女，
	 */
	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	/**
	 * 1：男， 2：女，
	 */
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	/**
	 * 修改时间
	 */
	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getTime() {
		return getDate("time");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

