
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserActionLog<M extends BaseUserActionLog<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 可能是谁 ，当uid有值时，本字段一定有值
	 */
	public void setMayuid(java.lang.Integer mayuid) {
		set("mayuid", mayuid);
	}
	
	/**
	 * 可能是谁 ，当uid有值时，本字段一定有值
	 */
	public java.lang.Integer getMayuid() {
		return getInt("mayuid");
	}

	public void setSession(java.lang.String session) {
		set("session", session);
	}
	
	public java.lang.String getSession() {
		return getStr("session");
	}

	public void setUaid(java.lang.Integer uaid) {
		set("uaid", uaid);
	}
	
	public java.lang.Integer getUaid() {
		return getInt("uaid");
	}

	public void setInitpath(java.lang.String initpath) {
		set("initpath", initpath);
	}
	
	public java.lang.String getInitpath() {
		return getStr("initpath");
	}

	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return getDate("time");
	}

	public void setActiontype(java.lang.Integer actiontype) {
		set("actiontype", actiontype);
	}
	
	public java.lang.Integer getActiontype() {
		return getInt("actiontype");
	}

	/**
	 * 动作描述
	 */
	public void setActiondesc(java.lang.String actiondesc) {
		set("actiondesc", actiondesc);
	}
	
	/**
	 * 动作描述
	 */
	public java.lang.String getActiondesc() {
		return getStr("actiondesc");
	}

}

