
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupMsgUserOper<M extends BaseWxGroupMsgUserOper<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 群id
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 群id
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 消息id
	 */
	public void setMsgid(java.lang.Long msgid) {
		set("msgid", msgid);
	}
	
	/**
	 * 消息id
	 */
	public java.lang.Long getMsgid() {
		return getLong("msgid");
	}

	/**
	 * 聊天发起人uid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 聊天发起人uid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 类型：1：删除
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 类型：1：删除
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

