
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTempUserKey<M extends BaseTempUserKey<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public void setName(String name) {
		set("name", name);
	}

	/**
	 * 名称
	 */
	public String getName() {
		return getStr("name");
	}

	public void setCreateUid(Integer createUid) {
		set("create_uid", createUid);
	}

	public Integer getCreateUid() {
		return getInt("create_uid");
	}

	public void setMemberUid(Integer memberUid) {
		set("member_uid", memberUid);
	}

	public Integer getMemberUid() {
		return getInt("member_uid");
	}

	public void setGroupId(Long groupId) {
		set("group_id", groupId);
	}

	public Long getGroupId() {
		return getLong("group_id");
	}

	/**
	 * 内容
	 */
	public void setKey(String key) {
		set("temp_key", key);
	}
	
	/**
	 * 内容
	 */
	public String getKey() {
		return getStr("temp_key");
	}


	/**
	 * 登录链接
	 */
	public void setLoginLink(String loginLink) {
		set("login_link", loginLink);
	}

	/**
	 * 登录链接
	 */
	public String getLoginLink() {
		return getStr("login_link");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

}

