
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupSign<M extends BaseWxGroupSign<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 群id
	 */
	public void setGroupid(Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 群id
	 */
	public Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * uid
	 */
	public void setUid(Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * uid
	 */
	public Integer getUid() {
		return getInt("uid");
	}

	/**
	 *  签到时间
	 */
	public void setSigntime(java.util.Date signtime) {
		set("signtime", signtime);
	}
	
	/**
	 *  签到时间
	 */
	public java.util.Date getSigntime() {
		return getDate("signtime");
	}

}

