
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSignTask<M extends BaseSignTask<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 连续签到天数
	 */
	public void setSignDay(Integer signDay) {
		set("sign_day", signDay);
	}
	
	/**
	 * 连续签到天数
	 */
	public Integer getSignDay() {
		return getInt("sign_day");
	}

	/**
	 * 奖励积分数
	 */
	public void setRewardIntegral(Long rewardIntegral) {
		set("reward_integral", rewardIntegral);
	}

	/**
	 * 奖励积分数
	 */
	public Long getRewardIntegral() {
		return getLong("reward_integral");
	}

	/**
	 * 描述
	 */
	public void setTaskDescribe(String taskDescribe) {
		set("task_describe", taskDescribe);
	}
	
	/**
	 * 描述
	 */
	public String getTaskDescribe() {
		return getStr("task_describe");
	}


	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createtime) {
		set("create_time", createtime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
}

