package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUserMergeData<M extends BaseWxUserMergeData<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 创建用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 创建用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 目标用户id
	 */
	public void setTouid(java.lang.Integer touid) {
		set("touid", touid);
	}
	
	/**
	 * 目标用户id
	 */
	public java.lang.Integer getTouid() {
		return getInt("touid");
	}

	/**
	 * 组id
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 组id
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 消息来源：1.用户，2.群聊
	 */
	public void setSourcetype(java.lang.Short sourcetype) {
		set("sourcetype", sourcetype);
	}
	
	/**
	 * 消息来源：1.用户，2.群聊
	 */
	public java.lang.Short getSourcetype() {
		return getShort("sourcetype");
	}

	/**
	 * 简易内容
	 */
	public void setMsg(java.lang.String data) {
		set("msg", data);
	}

	/**
	 * 简易内容
	 */
	public java.lang.String getMsg() {
		return getStr("msg");
	}


	/**
	 * 数据
	 */
	public void setData(java.lang.String data) {
		set("data", data);
	}
	
	/**
	 * 数据
	 */
	public java.lang.String getData() {
		return getStr("data");
	}

	/**
	 * 状态：1：正常
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：正常
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

