
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollect<M extends BaseCollect<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() {
		return getInt("uid");
	}

	public void setFromId(Integer fromId) {
		set("from_id", fromId);
	}

	public Integer getFromId() {
		return getInt("from_id");
	}

	public void setFromType(Integer fromType) {
		set("from_type", fromType);
	}

	public Integer getFromType() {
		return getInt("from_type");
	}
	/**
	 * 类型
	 */
	public void setCategory(Integer category) {
		set("category", category);
	}
	
	/**
	 * 类型
	 */
	public Integer getCategory() {
		return getInt("category");
	}

	/**
	 * 内容
	 */
	public void setContent(String content) {
		set("content", content);
	}

	/**
	 * 内容
	 */
	public String getContent() {
		return getStr("content");
	}

	/**
	 * 内容
	 */
	public void setText(String text) {
		set("text", text);
	}

	/**
	 * 内容
	 */
	public String getText() {
		return getStr("text");
	}

	/**
	 * 内容
	 */
	public void setImgUrl(String imgUrl) {
		set("img_url", imgUrl);
	}

	/**
	 * 内容
	 */
	public String getImgUrl() {
		return getStr("img_url");
	}

	/**
	 * 内容
	 */
	public void setTitle(String title) {
		set("title", title);
	}

	/**
	 * 内容
	 */
	public String getTitle() {
		return getStr("title");
	}

	/**
	 * 发布时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 发布时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

}

