
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRealNameCertification<M extends BaseRealNameCertification<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * user id
	 */
	public void setUid(Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * user id
	 */
	public Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 身份证号码
	 */
	public void setIdCardNumber(String idCardNumber) {
		set("id_card_number", idCardNumber);
	}
	
	/**
	 * 身份证号码
	 */
	public String getIdCardNumber() {
		return getStr("id_card_number");
	}

	/**
	 * 真实姓名
	 */
	public void setRealName(String realName) {
		set("real_name", realName);
	}
	
	/**
	 * 真实姓名
	 */
	public String getRealName() {
		return getStr("real_name");
	}

	/**
	 * 身份证正面照片
	 */
	public void setIdCardFront(String idCardFront) {
		set("id_card_front", idCardFront);
	}

	/**
	 * 身份证正面照片
	 */
	public String getIdCardFront() {
		return getStr("id_card_front");
	}

	/**
	 * 身份证背面照片
	 */
	public void setIdCardBehind(String idCardBehind) {
		set("id_card_behind", idCardBehind);
	}

	/**
	 * 身份证背面照片
	 */
	public String getIdCardBehind() {
		return getStr("id_card_behind");
	}


	/**
	 * 备注
	 */
	public void setMark(String mark) {
		set("mark", mark);
	}

	/**
	 * 备注
	 */
	public String getMark() {
		return getStr("mark");
	}

	/**
	 * 等级
	 */
	public void setStatus(Integer status) {
		set("status", status);
	}
	
	/**
	 * 等级
	 */
	public Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("create_time", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("create_time");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("update_time", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("update_time");
	}

}

