
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 标题
	 */
	public void setTitle(String title) {
		set("title", title);
	}
	
	/**
	 * 标题
	 */
	public String getTitle() {
		return getStr("title");
	}

	/**
	 * 标题
	 */
	public void setContent(String content) {
		set("content", content);
	}

	/**
	 * 标题
	 */
	public String getContent() {
		return getStr("content");
	}

	/**
	 * 发布时间
	 */
	public void setReleaseTime(java.util.Date releaseTime) {
		set("release_time", releaseTime);
	}

	/**
	 * 发布时间
	 */
	public java.util.Date getReleaseTime() {
		return getDate("release_time");
	}

}

