
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTioThreadLogs<M extends BaseTioThreadLogs<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 业务id
	 */
	public void setBizint(java.lang.Integer bizint) {
		set("bizint", bizint);
	}
	
	/**
	 * 业务id
	 */
	public java.lang.Integer getBizint() {
		return getInt("bizint");
	}

	/**
	 * 业务字符串
	 */
	public void setBizstr(java.lang.String bizstr) {
		set("bizstr", bizstr);
	}
	
	/**
	 * 业务字符串
	 */
	public java.lang.String getBizstr() {
		return getStr("bizstr");
	}

	/**
	 * 状态：2：初始化；1：已执行
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：2：初始化；1：已执行
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 类型：1：注册统计；2：登录统计
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 类型：1：注册统计；2：登录统计
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 上传时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 上传时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

