
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStrangerRemarkName<M extends BaseStrangerRemarkName<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() {
		return getInt("uid");
	}

	public void setRelationUid(Integer relationUid) {
		set("relation_uid", relationUid);
	}

	public Integer getRelationUid() {
		return getInt("relation_uid");
	}

	public void setRemarkName(String remarkName) {
		set("remark_name", remarkName);
	}

	public String getRemarkName() {
		return getStr("remark_name");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

}

