
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCircleApply<M extends BaseCircleApply<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 圈子名称
	 */
	public void setName(String name) {
		set("name", name);
	}

	/**
	 * 圈子名称
	 */
	public String getName() {
		return getStr("name");
	}

	/**
	 * 圈子创建者的uid
	 */
	public void setUid(Integer uid) {
		set("uid", uid);
	}

	/**
	 * 圈子创建者的uid
	 */
	public Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 圈子头像
	 */
	public void setAvatar(String avatar) {
		set("avatar", avatar);
	}

	/**
	 * 圈子头像
	 */
	public String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 圈子说明
	 */
	public void setDescribe(String describe) {
		set("describe", describe);
	}

	/**
	 * 圈子说明
	 */
	public String getDescribe() {
		return getStr("describe");
	}

	/**
	 * 圈子是否开放
	 */
	public void setIsOpen(Integer isOpen) {
		set("is_open", isOpen);
	}

	/**
	 * 圈子是否开放
	 */
	public Integer getIsOpen() {
		return getInt("is_open");
	}

	/**
	 * 进入圈子是否需要审核
	 */
	public void setIsExamine(Integer isExamine) {
		set("is_examine", isExamine);
	}

	/**
	 * 进入圈子是否需要审核
	 */
	public Integer getIsExamine() {
		return getInt("is_examine");
	}

	/**
	 * 进入圈子是否需要邀请
	 */
	public void setIsInvite(Integer isInvite) {
		set("is_invite", isInvite);
	}

	/**
	 * 进入圈子是否需要邀请
	 */
	public Integer getIsInvite() {
		return getInt("is_invite");
	}

	/**
	 * 需要多少人邀请才可以进入圈子
	 */
	public void setInviteNum(Integer inviteNum) {
		set("invite_num", inviteNum);
	}

	/**
	 * 需要多少人邀请才可以进入圈子
	 */
	public Integer getInviteNum() {
		return getInt("invite_num");
	}

	/**
	 * 圈子状态
	 */
	public void setStatus(Integer status) {
		set("status", status);
	}

	/**
	 * 圈子状态
	 */
	public Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 圈子id
	 */
	public void setCircleId(Integer circleId) {
		set("circle_id", circleId);
	}

	/**
	 * 圈子id
	 */
	public Integer getCircleId() {
		return getInt("circle_id");
	}

	/**
	 * 申请时间
	 */
	public void setApplyTime(java.util.Date applyTime) {
		set("apply_time", applyTime);
	}

	/**
	 * 申请时间
	 */
	public java.util.Date getApplyTime() {
		return getDate("apply_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}


	/**
	 * 拒绝理由
	 */
	public void setRefuseReason(String refuseReason) {
		set("refuse_reason", refuseReason);
	}

	/**
	 * 拒绝理由
	 */
	public String getRefuseReason() {
		return getStr("refuse_reason");
	}
}

