
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCircleLog<M extends BaseCircleLog<M>> extends TioModel<M> implements IBean {
	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setOperateUid(Integer uid) {
		set("operate_uid", uid);
	}

	public Integer getOperateUid() {
		return getInt("operate_uid");
	}

	public void setOperatedUid(Integer uid) {
		set("operated_uid", uid);
	}

	public Integer getOperatedUid() {
		return getInt("operated_uid");
	}

	public void setNick(String nick) {
		set("nick", nick);
	}

	public String getNick() {
		return getStr("nick");
	}

	public void setAvatar(String avatar) {
		set("avatar", avatar);
	}

	public String getAvatar() {
		return getStr("avatar");
	}

	public void setDescribe(String describe) {
		set("describe", describe);
	}

	public String getDescribe() {
		return getStr("describe");
	}

	public void setInviteUserList(String describe) {
		set("invite_users", describe);
	}

	public String getInviteUserList() {
		return getStr("invite_users");
	}

	public void setCircleId(Integer circleId) {
		set("circle_id", circleId);
	}

	public Integer getCircleId() {
		return getInt("circle_id");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return getInt("type");
	}


	public void setContentType(Integer contentType) {
		set("content_type", contentType);
	}

	public Integer getContentType() {
		return getInt("content_type");
	}

	/**
	 * 记录时间
	 */
	public void setRecordTime(java.util.Date recordTime) {
		set("record_time", recordTime);
	}

	/**
	 * 记录时间
	 */
	public java.util.Date getRecordTime() {
		return getDate("record_time");
	}


}

