
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatOnline<M extends BaseStatOnline<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 哪台服务器上的数据
	 */
	public void setServer(java.lang.String server) {
		set("server", server);
	}
	
	/**
	 * 哪台服务器上的数据
	 */
	public java.lang.String getServer() {
		return getStr("server");
	}

	/**
	 * 登录的用户数
	 */
	public void setLogined(java.lang.Integer logined) {
		set("logined", logined);
	}
	
	/**
	 * 登录的用户数
	 */
	public java.lang.Integer getLogined() {
		return getInt("logined");
	}

	/**
	 * 独立ip数
	 */
	public void setIp(java.lang.Integer ip) {
		set("ip", ip);
	}
	
	/**
	 * 独立ip数
	 */
	public java.lang.Integer getIp() {
		return getInt("ip");
	}

	/**
	 * 独立session数
	 */
	public void setSession(java.lang.Integer session) {
		set("session", session);
	}
	
	/**
	 * 独立session数
	 */
	public java.lang.Integer getSession() {
		return getInt("session");
	}

	/**
	 * 打开的页面数
	 */
	public void setPage(java.lang.Integer page) {
		set("page", page);
	}
	
	/**
	 * 打开的页面数
	 */
	public java.lang.Integer getPage() {
		return getInt("page");
	}

	/**
	 * 群组个数（包括聊天室在内的所有群组）
	 */
	public void setGroup(java.lang.Integer group) {
		set("group", group);
	}
	
	/**
	 * 群组个数（包括聊天室在内的所有群组）
	 */
	public java.lang.Integer getGroup() {
		return getInt("group");
	}

	/**
	 * 这个时间必须由程序指定，其秒必须是5的整数
	 */
	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	/**
	 * 这个时间必须由程序指定，其秒必须是5的整数
	 */
	public java.util.Date getTime() {
		return getDate("time");
	}

}

