
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserlogModifyAvatar<M extends BaseUserlogModifyAvatar<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setOldavatar(java.lang.String oldavatar) {
		set("oldavatar", oldavatar);
	}
	
	public java.lang.String getOldavatar() {
		return getStr("oldavatar");
	}

	public void setNewavatar(java.lang.String newavatar) {
		set("newavatar", newavatar);
	}
	
	public java.lang.String getNewavatar() {
		return getStr("newavatar");
	}

	public void setOldavatarbig(java.lang.String oldavatarbig) {
		set("oldavatarbig", oldavatarbig);
	}
	
	public java.lang.String getOldavatarbig() {
		return getStr("oldavatarbig");
	}

	public void setNewavatarbig(java.lang.String newavatarbig) {
		set("newavatarbig", newavatarbig);
	}
	
	public java.lang.String getNewavatarbig() {
		return getStr("newavatarbig");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

