
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxTag<M extends BaseWxTag<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setTagname(java.lang.String tagname) {
		set("tagname", tagname);
	}
	
	public java.lang.String getTagname() {
		return getStr("tagname");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

}

