
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxChatGroupItem<M extends BaseWxChatGroupItem<M>> extends TioModel<M> implements IBean {

	/**
	 * 群id
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 群id
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 群组用户关联表id
	 */
	public void setGpulinkid(java.lang.Long gpulinkid) {
		set("gpulinkid", gpulinkid);
	}
	
	/**
	 * 群组用户关联表id
	 */
	public java.lang.Long getGpulinkid() {
		return getLong("gpulinkid");
	}

	/**
	 * 聊天id
	 */
	public void setChatlinkid(java.lang.Long chatlinkid) {
		set("chatlinkid", chatlinkid);
	}
	
	/**
	 * 聊天id
	 */
	public java.lang.Long getChatlinkid() {
		return getLong("chatlinkid");
	}

	public void setChatlinkmetaid(java.lang.Long chatlinkmetaid) {
		set("chatlinkmetaid", chatlinkmetaid);
	}
	
	public java.lang.Long getChatlinkmetaid() {
		return getLong("chatlinkmetaid");
	}

	/**
	 * 重置标识(废弃)：1：是；2：否
	 */
	public void setResetflag(java.lang.Short resetflag) {
		set("resetflag", resetflag);
	}
	
	/**
	 * 重置标识(废弃)：1：是；2：否
	 */
	public java.lang.Short getResetflag() {
		return getShort("resetflag");
	}

	/**
	 * 是否是有效连接（是否是有效的聊天信息）：1：是；2：否
	 */
	public void setLinkflag(java.lang.Short linkflag) {
		set("linkflag", linkflag);
	}
	
	/**
	 * 是否是有效连接（是否是有效的聊天信息）：1：是；2：否
	 */
	public java.lang.Short getLinkflag() {
		return getShort("linkflag");
	}

	/**
	 * 焦点标识：1：是；2：否
	 */
	public void setFocusflag(java.lang.Short focusflag) {
		set("focusflag", focusflag);
	}
	
	/**
	 * 焦点标识：1：是；2：否
	 */
	public java.lang.Short getFocusflag() {
		return getShort("focusflag");
	}

	/**
	 * 群角色：1：群主；2：成员
	 */
	public void setGrouprole(java.lang.Short grouprole) {
		set("grouprole", grouprole);
	}
	
	/**
	 * 群角色：1：群主；2：成员
	 */
	public java.lang.Short getGrouprole() {
		return getShort("grouprole");
	}

	/**
	 * 从哪个消息开始有阅读权限
	 */
	public void setStartmsgid(java.lang.Long startmsgid) {
		set("startmsgid", startmsgid);
	}
	
	/**
	 * 从哪个消息开始有阅读权限
	 */
	public java.lang.Long getStartmsgid() {
		return getLong("startmsgid");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

