
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseImg<M extends BaseImg<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 上传者
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 上传者
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setSession(java.lang.String session) {
		set("session", session);
	}
	
	public java.lang.String getSession() {
		return getStr("session");
	}

	/**
	 * 标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 文件名
	 */
	public void setFilename(java.lang.String filename) {
		set("filename", filename);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getFilename() {
		return getStr("filename");
	}

	/**
	 * 图片url
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 图片url
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 原始url，因为图片可能来自第三方
	 */
	public void setIniturl(java.lang.String initurl) {
		set("initurl", initurl);
	}
	
	/**
	 * 原始url，因为图片可能来自第三方
	 */
	public java.lang.String getIniturl() {
		return getStr("initurl");
	}

	/**
	 * 图片来源。1、im上传，2：博客上传
	 */
	public void setComefrom(java.lang.Short comefrom) {
		set("comefrom", comefrom);
	}
	
	/**
	 * 图片来源。1、im上传，2：博客上传
	 */
	public java.lang.Short getComefrom() {
		return getShort("comefrom");
	}

	/**
	 * 图片的宽
	 */
	public void setWidth(java.lang.Integer width) {
		set("width", width);
	}
	
	/**
	 * 图片的宽
	 */
	public java.lang.Integer getWidth() {
		return getInt("width");
	}

	/**
	 * 图片的高
	 */
	public void setHeight(java.lang.Integer height) {
		set("height", height);
	}
	
	/**
	 * 图片的高
	 */
	public java.lang.Integer getHeight() {
		return getInt("height");
	}

	/**
	 * 文件大小，单位字节
	 */
	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	/**
	 * 文件大小，单位字节
	 */
	public java.lang.Long getSize() {
		return getLong("size");
	}

	/**
	 * 状态：1：不可公开浏览；2：可公开浏览；3：禁止在任何场景显示
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：不可公开浏览；2：可公开浏览；3：禁止在任何场景显示
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 缩略图url
	 */
	public void setCoverurl(java.lang.String coverurl) {
		set("coverurl", coverurl);
	}
	
	/**
	 * 缩略图url
	 */
	public java.lang.String getCoverurl() {
		return getStr("coverurl");
	}

	/**
	 * 缩略图的宽
	 */
	public void setCoverwidth(java.lang.Integer coverwidth) {
		set("coverwidth", coverwidth);
	}
	
	/**
	 * 缩略图的宽
	 */
	public java.lang.Integer getCoverwidth() {
		return getInt("coverwidth");
	}

	/**
	 * 缩略图的高
	 */
	public void setCoverheight(java.lang.Integer coverheight) {
		set("coverheight", coverheight);
	}
	
	/**
	 * 缩略图的高
	 */
	public java.lang.Integer getCoverheight() {
		return getInt("coverheight");
	}

	/**
	 * 缩略图尺寸，单位：字节
	 */
	public void setCoversize(java.lang.Integer coversize) {
		set("coversize", coversize);
	}
	
	/**
	 * 缩略图尺寸，单位：字节
	 */
	public java.lang.Integer getCoversize() {
		return getInt("coversize");
	}

	/**
	 * 上传时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 上传时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

