
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserThirdQq<M extends BaseUserThirdQq<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * user_third表的id字段
	 */
	public void setUserThirdId(java.lang.Integer userThirdId) {
		set("user_third_id", userThirdId);
	}
	
	/**
	 * user_third表的id字段
	 */
	public java.lang.Integer getUserThirdId() {
		return getInt("user_third_id");
	}

	/**
	 * 标识用户是否为黄钻用户（0：不是；1：是）。
	 */
	public void setIsYellowVip(java.lang.Short isYellowVip) {
		set("is_yellow_vip", isYellowVip);
	}
	
	/**
	 * 标识用户是否为黄钻用户（0：不是；1：是）。
	 */
	public java.lang.Short getIsYellowVip() {
		return getShort("is_yellow_vip");
	}

	/**
	 * 黄钻等级
	 */
	public void setYellowVipLevel(java.lang.String yellowVipLevel) {
		set("yellow_vip_level", yellowVipLevel);
	}
	
	/**
	 * 黄钻等级
	 */
	public java.lang.String getYellowVipLevel() {
		return getStr("yellow_vip_level");
	}

}

