
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxWalletSendRedPacket<M extends BaseWxWalletSendRedPacket<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public void setChatmode(java.lang.Short chatmode) {
		set("chatmode", chatmode);
	}
	
	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public java.lang.Short getChatmode() {
		return getShort("chatmode");
	}

	/**
	 * 红包范围id
	 */
	public void setChatbizid(java.lang.Long chatbizid) {
		set("chatbizid", chatbizid);
	}
	
	/**
	 * 红包范围id
	 */
	public java.lang.Long getChatbizid() {
		return getLong("chatbizid");
	}

	/**
	 * 消息id
	 */
	public void setMsgid(java.lang.Long msgid) {
		set("msgid", msgid);
	}
	
	/**
	 * 消息id
	 */
	public java.lang.Long getMsgid() {
		return getLong("msgid");
	}

	/**
	 * 请求id
	 */
	public void setReqid(java.lang.String reqid) {
		set("reqid", reqid);
	}
	
	/**
	 * 请求id
	 */
	public java.lang.String getReqid() {
		return getStr("reqid");
	}

	/**
	 * 协议支付卡号
	 */
	public void setAgrno(java.lang.String agrno) {
		set("agrno", agrno);
	}
	
	/**
	 * 协议支付卡号
	 */
	public java.lang.String getAgrno() {
		return getStr("agrno");
	}

	/**
	 * 商户id
	 */
	public void setMerid(java.lang.String merid) {
		set("merid", merid);
	}
	
	/**
	 * 商户id
	 */
	public java.lang.String getMerid() {
		return getStr("merid");
	}

	/**
	 * 钱包id
	 */
	public void setWalletid(java.lang.String walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 钱包id
	 */
	public java.lang.String getWalletid() {
		return getStr("walletid");
	}

	/**
	 * 附属钱包id
	 */
	public void setSubwalletid(java.lang.String subwalletid) {
		set("subwalletid", subwalletid);
	}
	
	/**
	 * 附属钱包id
	 */
	public java.lang.String getSubwalletid() {
		return getStr("subwalletid");
	}

	/**
	 * 商户订单号
	 */
	public void setMerorderid(java.lang.String merorderid) {
		set("merorderid", merorderid);
	}
	
	/**
	 * 商户订单号
	 */
	public java.lang.String getMerorderid() {
		return getStr("merorderid");
	}

	/**
	 * 金额
	 */
	public void setCny(java.lang.Long cny) {
		set("cny", cny);
	}
	
	/**
	 * 金额
	 */
	public java.lang.Long getCny() {
		return getLong("cny");
	}

	/**
	 * 类型：1：普通红包；2：手气红包；
	 */
	public void setMode(java.lang.Short mode) {
		set("mode", mode);
	}
	
	/**
	 * 类型：1：普通红包；2：手气红包；
	 */
	public java.lang.Short getMode() {
		return getShort("mode");
	}

	/**
	 * 状态：1：发送完成；2：初始化生成；3：支付中；4：成功；5：超时；6：取消；7：失败
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：发送完成；2：初始化生成；3：支付中；4：成功；5：超时；6：取消；7：失败
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 发送消息触发模型：1：回调；2：查询；3：补偿
	 */
	public void setSendmode(java.lang.Short sendmode) {
		set("sendmode", sendmode);
	}
	
	/**
	 * 发送消息触发模型：1：回调；2：查询；3：补偿
	 */
	public java.lang.Short getSendmode() {
		return getShort("sendmode");
	}

	/**
	 * 发送红包个数
	 */
	public void setNum(java.lang.Short num) {
		set("num", num);
	}
	
	/**
	 * 发送红包个数
	 */
	public java.lang.Short getNum() {
		return getShort("num");
	}

	/**
	 * 已接受数量
	 */
	public void setAcceptnum(java.lang.Short acceptnum) {
		set("acceptnum", acceptnum);
	}
	
	/**
	 * 已接受数量
	 */
	public java.lang.Short getAcceptnum() {
		return getShort("acceptnum");
	}

	/**
	 * 接受的用户uid
	 */
	public void setAcceptuid(java.lang.Integer acceptuid) {
		set("acceptuid", acceptuid);
	}
	
	/**
	 * 接受的用户uid
	 */
	public java.lang.Integer getAcceptuid() {
		return getInt("acceptuid");
	}

	/**
	 * 封面
	 */
	public void setCovers(java.lang.String covers) {
		set("covers", covers);
	}
	
	/**
	 * 封面
	 */
	public java.lang.String getCovers() {
		return getStr("covers");
	}

	/**
	 * 祝福语
	 */
	public void setBless(java.lang.String bless) {
		set("bless", bless);
	}
	
	/**
	 * 祝福语
	 */
	public java.lang.String getBless() {
		return getStr("bless");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 支付方式：1：协议支付；2：余额支付
	 */
	public void setPaytype(java.lang.Short paytype) {
		set("paytype", paytype);
	}
	
	/**
	 * 支付方式：1：协议支付；2：余额支付
	 */
	public java.lang.Short getPaytype() {
		return getShort("paytype");
	}

	/**
	 * 开始时间
	 */
	public void setStarttime(java.util.Date starttime) {
		set("starttime", starttime);
	}
	
	/**
	 * 开始时间
	 */
	public java.util.Date getStarttime() {
		return getDate("starttime");
	}

	/**
	 * api发起时间
	 */
	public void setApitime(java.util.Date apitime) {
		set("apitime", apitime);
	}
	
	/**
	 * api发起时间
	 */
	public java.util.Date getApitime() {
		return getDate("apitime");
	}

	/**
	 * 超时时间：每个阶段超时时间公用-按status来
	 */
	public void setBacktime(java.util.Date backtime) {
		set("backtime", backtime);
	}
	
	/**
	 * 超时时间：每个阶段超时时间公用-按status来
	 */
	public java.util.Date getBacktime() {
		return getDate("backtime");
	}

	/**
	 * 红包结束时间
	 */
	public void setEndtime(java.util.Date endtime) {
		set("endtime", endtime);
	}
	
	/**
	 * 红包结束时间
	 */
	public java.util.Date getEndtime() {
		return getDate("endtime");
	}

	/**
	 * 发起的ip
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 发起的ip
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setDevice(java.lang.Short device) {
		set("device", device);
	}
	
	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public java.lang.Short getDevice() {
		return getShort("device");
	}

	/**
	 * 发起的app版本号
	 */
	public void setAppversion(java.lang.String appversion) {
		set("appversion", appversion);
	}
	
	/**
	 * 发起的app版本号
	 */
	public java.lang.String getAppversion() {
		return getStr("appversion");
	}

	/**
	 * 快捷支付超时设置：1-1440分
	 */
	public void setPaytimeout(java.lang.Short paytimeout) {
		set("paytimeout", paytimeout);
	}
	
	/**
	 * 快捷支付超时设置：1-1440分
	 */
	public java.lang.Short getPaytimeout() {
		return getShort("paytimeout");
	}

	/**
	 * 快捷支付回调url
	 */
	public void setPaynotifyurl(java.lang.String paynotifyurl) {
		set("paynotifyurl", paynotifyurl);
	}
	
	/**
	 * 快捷支付回调url
	 */
	public java.lang.String getPaynotifyurl() {
		return getStr("paynotifyurl");
	}

	/**
	 * 预下单创建时间
	 */
	public void setBizcreattime(java.lang.String bizcreattime) {
		set("bizcreattime", bizcreattime);
	}
	
	/**
	 * 预下单创建时间
	 */
	public java.lang.String getBizcreattime() {
		return getStr("bizcreattime");
	}

	/**
	 * 订单完成时间
	 */
	public void setBizcompletetime(java.lang.String bizcompletetime) {
		set("bizcompletetime", bizcompletetime);
	}
	
	/**
	 * 订单完成时间
	 */
	public java.lang.String getBizcompletetime() {
		return getStr("bizcompletetime");
	}

	/**
	 * 订单错误信息
	 */
	public void setOrdererrormsg(java.lang.String ordererrormsg) {
		set("ordererrormsg", ordererrormsg);
	}
	
	/**
	 * 订单错误信息
	 */
	public java.lang.String getOrdererrormsg() {
		return getStr("ordererrormsg");
	}

	/**
	 * 对账状态：1：是；2：否
	 */
	public void setCheckflag(java.lang.Short checkflag) {
		set("checkflag", checkflag);
	}
	
	/**
	 * 对账状态：1：是；2：否
	 */
	public java.lang.Short getCheckflag() {
		return getShort("checkflag");
	}

	/**
	 * 对账时间
	 */
	public void setCheckdate(java.lang.String checkdate) {
		set("checkdate", checkdate);
	}
	
	/**
	 * 对账时间
	 */
	public java.lang.String getCheckdate() {
		return getStr("checkdate");
	}

	/**
	 * 同步状态：1：初始化处理；2：未处理；3：完成
	 */
	public void setCoinsyn(java.lang.Short coinsyn) {
		set("coinsyn", coinsyn);
	}
	
	/**
	 * 同步状态：1：初始化处理；2：未处理；3：完成
	 */
	public java.lang.Short getCoinsyn() {
		return getShort("coinsyn");
	}

	/**
	 * 查询同步:1：回调成功；2：否；3：查询同步
	 */
	public void setQuerysyn(java.lang.Short querysyn) {
		set("querysyn", querysyn);
	}
	
	/**
	 * 查询同步:1：回调成功；2：否；3：查询同步
	 */
	public java.lang.Short getQuerysyn() {
		return getShort("querysyn");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

