
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMoments<M extends BaseMoments<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() {
		return getInt("uid");
	}
	/**
	 * 视频链接
	 */
	public void setVideoUrl(String videoUrl) {
		set("video_url", videoUrl);
	}
	
	/**
	 * 视频链接
	 */
	public String getVideoUrl() {
		return getStr("video_url");
	}

	/**
	 * 内容
	 */
	public void setContent(String content) {
		set("content", content);
	}

	/**
	 * 内容
	 */
	public String getContent() {
		return getStr("content");
	}

	/**
	 * 图片链接，多张图片使用 , 连接
	 */
	public void setImgUrl(String imgUrl) {
		set("img_url", imgUrl);
	}

	/**
	 * 图片链接，多张图片使用 , 连接
	 */
	public String getImgUrl() {
		return getStr("img_url");
	}

	/**
	 * 发布时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 发布时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}


	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

	/**
	 * 权限标识：1：公开；2：私密；3：可见；4：不可见
	 */
	public void setAuthFlag(java.lang.Short authflag) {
		set("authflag", authflag);
	}

	/**
	 * 权限标识：1：公开；2：私密；3：可见；4：不可见
	 */
	public java.lang.Short getAuthFlag() {
		return getShort("authflag");
	}

}

