
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserInfoSyn<M extends BaseUserInfoSyn<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 同步类型：1：昵称；2：头像；
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 同步类型：1：昵称；2：头像；
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 业务字符串
	 */
	public void setBizstr(java.lang.String bizstr) {
		set("bizstr", bizstr);
	}
	
	/**
	 * 业务字符串
	 */
	public java.lang.String getBizstr() {
		return getStr("bizstr");
	}

	/**
	 * 业务id
	 */
	public void setBizint(java.lang.Integer bizint) {
		set("bizint", bizint);
	}
	
	/**
	 * 业务id
	 */
	public java.lang.Integer getBizint() {
		return getInt("bizint");
	}

	/**
	 * 业务longid
	 */
	public void setBizbigint(java.lang.Long bizbigint) {
		set("bizbigint", bizbigint);
	}
	
	/**
	 * 业务longid
	 */
	public java.lang.Long getBizbigint() {
		return getLong("bizbigint");
	}

	/**
	 * 处理标识：1、初始化；2：处理中；3：删除
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 处理标识：1、初始化；2：处理中；3：删除
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 处理ip
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 处理ip
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

