
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUserReport<M extends BaseWxUserReport<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 举报投诉人
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 举报投诉人
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 举报投诉类型：1：用户；2：群：3：消息；4:建议
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 举报投诉类型：1：用户；2：群：3：消息；4:建议
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 消息id
	 */
	public void setMid(java.lang.Long mid) {
		set("mid", mid);
	}
	
	/**
	 * 消息id
	 */
	public java.lang.Long getMid() {
		return getLong("mid");
	}

	/**
	 * 被举报者
	 */
	public void setTouid(java.lang.Integer touid) {
		set("touid", touid);
	}
	
	/**
	 * 被举报者
	 */
	public java.lang.Integer getTouid() {
		return getInt("touid");
	}

	/**
	 * 被投诉群
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 被投诉群
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 举报投诉原因
	 */
	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}
	
	/**
	 * 举报投诉原因
	 */
	public java.lang.String getReason() {
		return getStr("reason");
	}

	/**
	 * 举报的内容
	 */
	public void setSrctext(java.lang.String srctext) {
		set("srctext", srctext);
	}
	
	/**
	 * 举报的内容
	 */
	public java.lang.String getSrctext() {
		return getStr("srctext");
	}

	/**
	 * 处理状态：1：处理中；2：初始化；3：已处理
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 处理状态：1：处理中；2：初始化；3：已处理
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 图片
	 */
	public void setImgs(java.lang.String imgs) {
		set("imgs", imgs);
	}
	
	/**
	 * 图片
	 */
	public java.lang.String getImgs() {
		return getStr("imgs");
	}

	/**
	 * 设备
	 */
	public void setDevicetype(java.lang.Short devicetype) {
		set("devicetype", devicetype);
	}
	
	/**
	 * 设备
	 */
	public java.lang.Short getDevicetype() {
		return getShort("devicetype");
	}

	/**
	 * 版本号
	 */
	public void setAppversion(java.lang.String appversion) {
		set("appversion", appversion);
	}
	
	/**
	 * 版本号
	 */
	public java.lang.String getAppversion() {
		return getStr("appversion");
	}

	/**
	 * 后台管理员uid
	 */
	public void setAdminuid(java.lang.Integer adminuid) {
		set("adminuid", adminuid);
	}
	
	/**
	 * 后台管理员uid
	 */
	public java.lang.Integer getAdminuid() {
		return getInt("adminuid");
	}

	/**
	 * 后台管理员昵称
	 */
	public void setAdminnick(java.lang.String adminnick) {
		set("adminnick", adminnick);
	}
	
	/**
	 * 后台管理员昵称
	 */
	public java.lang.String getAdminnick() {
		return getStr("adminnick");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

