
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserToken<M extends BaseUserToken<M>> extends TioModel<M> implements IBean {

	/**
	 * userid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * userid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 1：pc， 2：安卓，3：IOS
	 */
	public void setDevicetype(java.lang.Short devicetype) {
		set("devicetype", devicetype);
	}
	
	/**
	 * 1：pc， 2：安卓，3：IOS
	 */
	public java.lang.Short getDevicetype() {
		return getShort("devicetype");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}
	
	public java.lang.String getToken() {
		return getStr("token");
	}

}

