
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserlogModifyNick<M extends BaseUserlogModifyNick<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setOldnick(java.lang.String oldnick) {
		set("oldnick", oldnick);
	}
	
	public java.lang.String getOldnick() {
		return getStr("oldnick");
	}

	public void setNewnick(java.lang.String newnick) {
		set("newnick", newnick);
	}
	
	public java.lang.String getNewnick() {
		return getStr("newnick");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

