
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupApplyItems<M extends BaseWxGroupApplyItems<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 申请记录
	 */
	public void setAid(java.lang.Integer aid) {
		set("aid", aid);
	}
	
	/**
	 * 申请记录
	 */
	public java.lang.Integer getAid() {
		return getInt("aid");
	}

	/**
	 * 申请群id
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 申请群id
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 申请uid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 申请uid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 申请状态：1：已处理；2：申请中；3：已驳回
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 申请状态：1：已处理；2：申请中；3：已驳回
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 *  群创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 *  群创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 *  群资料更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 *  群资料更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

