
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxWalletRechargeItem<M extends BaseWxWalletRechargeItem<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 钱包id
	 */
	public void setWalletid(java.lang.String walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 钱包id
	 */
	public java.lang.String getWalletid() {
		return getStr("walletid");
	}

	/**
	 * 商户号
	 */
	public void setMerid(java.lang.String merid) {
		set("merid", merid);
	}
	
	/**
	 * 商户号
	 */
	public java.lang.String getMerid() {
		return getStr("merid");
	}

	/**
	 * 请求id
	 */
	public void setReqid(java.lang.String reqid) {
		set("reqid", reqid);
	}
	
	/**
	 * 请求id
	 */
	public java.lang.String getReqid() {
		return getStr("reqid");
	}

	/**
	 * 商户订单号
	 */
	public void setMerorderid(java.lang.String merorderid) {
		set("merorderid", merorderid);
	}
	
	/**
	 * 商户订单号
	 */
	public java.lang.String getMerorderid() {
		return getStr("merorderid");
	}

	/**
	 * 协议卡号
	 */
	public void setAgrno(java.lang.String agrno) {
		set("agrno", agrno);
	}
	
	/**
	 * 协议卡号
	 */
	public java.lang.String getAgrno() {
		return getStr("agrno");
	}

	/**
	 * 充值金额(分)
	 */
	public void setAmount(java.lang.Long amount) {
		set("amount", amount);
	}
	
	/**
	 * 充值金额(分)
	 */
	public java.lang.Long getAmount() {
		return getLong("amount");
	}

	/**
	 * 商户手续费
	 */
	public void setMerfee(java.lang.Integer merfee) {
		set("merfee", merfee);
	}
	
	/**
	 * 商户手续费
	 */
	public java.lang.Integer getMerfee() {
		return getInt("merfee");
	}

	/**
	 * 业务服务费-自己收取的
	 */
	public void setBizfee(java.lang.Integer bizfee) {
		set("bizfee", bizfee);
	}
	
	/**
	 * 业务服务费-自己收取的
	 */
	public java.lang.Integer getBizfee() {
		return getInt("bizfee");
	}

	/**
	 * 备注：商户传输附加值
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注：商户传输附加值
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 商户状态:-1为未处理
	 */
	public void setMerstatus(java.lang.String merstatus) {
		set("merstatus", merstatus);
	}
	
	/**
	 * 商户状态:-1为未处理
	 */
	public java.lang.String getMerstatus() {
		return getStr("merstatus");
	}

	/**
	 * 超时设置：1-1440分
	 */
	public void setTimeout(java.lang.Short timeout) {
		set("timeout", timeout);
	}
	
	/**
	 * 超时设置：1-1440分
	 */
	public java.lang.Short getTimeout() {
		return getShort("timeout");
	}

	/**
	 * 回调url
	 */
	public void setNotifyurl(java.lang.String notifyurl) {
		set("notifyurl", notifyurl);
	}
	
	/**
	 * 回调url
	 */
	public java.lang.String getNotifyurl() {
		return getStr("notifyurl");
	}

	/**
	 * 银行卡卡号-掩码
	 */
	public void setBankcardnumber(java.lang.String bankcardnumber) {
		set("bankcardnumber", bankcardnumber);
	}
	
	/**
	 * 银行卡卡号-掩码
	 */
	public java.lang.String getBankcardnumber() {
		return getStr("bankcardnumber");
	}

	/**
	 * 银行代码
	 */
	public void setBankcode(java.lang.String bankcode) {
		set("bankcode", bankcode);
	}
	
	/**
	 * 银行代码
	 */
	public java.lang.String getBankcode() {
		return getStr("bankcode");
	}

	/**
	 * 银行名称
	 */
	public void setBankname(java.lang.String bankname) {
		set("bankname", bankname);
	}
	
	/**
	 * 银行名称
	 */
	public java.lang.String getBankname() {
		return getStr("bankname");
	}

	/**
	 * 银行icon
	 */
	public void setBankicon(java.lang.String bankicon) {
		set("bankicon", bankicon);
	}
	
	/**
	 * 银行icon
	 */
	public java.lang.String getBankicon() {
		return getStr("bankicon");
	}

	/**
	 * 查询同步:1：回调成功；2：否；3：查询同步
	 */
	public void setQuerysyn(java.lang.Short querysyn) {
		set("querysyn", querysyn);
	}
	
	/**
	 * 查询同步:1：回调成功；2：否；3：查询同步
	 */
	public java.lang.Short getQuerysyn() {
		return getShort("querysyn");
	}

	/**
	 * 预下单创建时间
	 */
	public void setBizcreattime(java.lang.String bizcreattime) {
		set("bizcreattime", bizcreattime);
	}
	
	/**
	 * 预下单创建时间
	 */
	public java.lang.String getBizcreattime() {
		return getStr("bizcreattime");
	}

	/**
	 * 订单完成时间
	 */
	public void setBizcompletetime(java.lang.String bizcompletetime) {
		set("bizcompletetime", bizcompletetime);
	}
	
	/**
	 * 订单完成时间
	 */
	public java.lang.String getBizcompletetime() {
		return getStr("bizcompletetime");
	}

	/**
	 * 订单错误信息
	 */
	public void setOrdererrormsg(java.lang.String ordererrormsg) {
		set("ordererrormsg", ordererrormsg);
	}
	
	/**
	 * 订单错误信息
	 */
	public java.lang.String getOrdererrormsg() {
		return getStr("ordererrormsg");
	}

	/**
	 * 对账状态：1：是；2：否
	 */
	public void setCheckflag(java.lang.Short checkflag) {
		set("checkflag", checkflag);
	}
	
	/**
	 * 对账状态：1：是；2：否
	 */
	public java.lang.Short getCheckflag() {
		return getShort("checkflag");
	}

	/**
	 * 对账时间
	 */
	public void setCheckdate(java.lang.String checkdate) {
		set("checkdate", checkdate);
	}
	
	/**
	 * 对账时间
	 */
	public java.lang.String getCheckdate() {
		return getStr("checkdate");
	}

	/**
	 * 同步状态：1：初始化处理；2：未处理；3：完成
	 */
	public void setCoinsyn(java.lang.Short coinsyn) {
		set("coinsyn", coinsyn);
	}
	
	/**
	 * 同步状态：1：初始化处理；2：未处理；3：完成
	 */
	public java.lang.Short getCoinsyn() {
		return getShort("coinsyn");
	}

	/**
	 * 发起的ip
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 发起的ip
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setDevice(java.lang.Short device) {
		set("device", device);
	}
	
	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public java.lang.Short getDevice() {
		return getShort("device");
	}

	/**
	 * 发起的app版本号
	 */
	public void setAppversion(java.lang.String appversion) {
		set("appversion", appversion);
	}
	
	/**
	 * 发起的app版本号
	 */
	public java.lang.String getAppversion() {
		return getStr("appversion");
	}

	/**
	 * 充值返回得余额
	 */
	public void setRecvacctamount(java.lang.Long recvacctamount) {
		set("recvacctamount", recvacctamount);
	}
	
	/**
	 * 充值返回得余额
	 */
	public java.lang.Long getRecvacctamount() {
		return getLong("recvacctamount");
	}

	/**
	 * 队列处理时间
	 */
	public void setQueuetime(java.util.Date queuetime) {
		set("queuetime", queuetime);
	}
	
	/**
	 * 队列处理时间
	 */
	public java.util.Date getQueuetime() {
		return getDate("queuetime");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

