
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoginTaskItems<M extends BaseLoginTaskItems<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 操作id-系统处理-1
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 操作id-系统处理-1
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 处理标识：1、初始化；2：处理中；3：删除
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 处理标识：1、初始化；2：处理中；3：删除
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 处理时间
	 */
	public void setDealtime(java.util.Date dealtime) {
		set("dealtime", dealtime);
	}
	
	/**
	 * 处理时间
	 */
	public java.util.Date getDealtime() {
		return getDate("dealtime");
	}

	/**
	 * 处理机器
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 处理机器
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

