
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUserWithholdItemLocal<M extends BaseWxUserWithholdItemLocal<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 钱包id
	 */
	public void setWalletid(String walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 钱包id
	 */
	public String getWalletid() {
		return getStr("walletid");
	}

	/**
	 * 商户号
	 */
	public void setBizid(String bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 商户号
	 */
	public String getBizid() {
		return getStr("bizid");
	}

	/**
	 * 请求id
	 */
	public void setReqid(String reqid) {
		set("reqid", reqid);
	}
	
	/**
	 * 请求id
	 */
	public String getReqid() {
		return getStr("reqid");
	}

	/**
	 * 提现流水号
	 */
	public void setSerialnumber(String serialnumber) {
		set("serialnumber", serialnumber);
	}
	
	/**
	 * 提现流水号
	 */
	public String getSerialnumber() {
		return getStr("serialnumber");
	}

	/**
	 * 币种
	 */
	public void setCurrency(String currency) {
		set("currency", currency);
	}
	
	/**
	 * 币种
	 */
	public String getCurrency() {
		return getStr("currency");
	}

	/**
	 * 提现金额(分）
	 */
	public void setAmount(Integer amount) {
		set("amount", amount);
	}
	
	/**
	 * 提现金额(分）
	 */
	public Integer getAmount() {
		return getInt("amount");
	}

	/**
	 * 实际到账(分)
	 */
	public void setArrivalamount(Integer arrivalamount) {
		set("arrivalamount", arrivalamount);
	}
	
	/**
	 * 实际到账(分)
	 */
	public Integer getArrivalamount() {
		return getInt("arrivalamount");
	}

	/**
	 * 预提现的token值
	 */
	public void setToken(String token) {
		set("token", token);
	}
	
	/**
	 * 预提现的token值
	 */
	public String getToken() {
		return getStr("token");
	}

	/**
	 * 备注：商户传输附加值
	 */
	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注：商户传输附加值
	 */
	public String getRemark() {
		return getStr("remark");
	}

	/**
	 * 状态：初始化：INIT;成功：SUCCESS;取消：CANCEL;失败：FAIL
	 */
	public void setStatus(String status) {
		set("status", status);
	}
	
	/**
	 * 状态：初始化：INIT;成功：SUCCESS;取消：CANCEL;失败：FAIL
	 */
	public String getStatus() {
		return getStr("status");
	}

	/**
	 * 超时设置：1-1440分
	 */
	public void setTimeout(Short timeout) {
		set("timeout", timeout);
	}
	
	/**
	 * 超时设置：1-1440分
	 */
	public Short getTimeout() {
		return getShort("timeout");
	}

	/**
	 * 回调url
	 */
	public void setNotifyurl(String notifyurl) {
		set("notifyurl", notifyurl);
	}
	
	/**
	 * 回调url
	 */
	public String getNotifyurl() {
		return getStr("notifyurl");
	}

	/**
	 * 预下单创建时间
	 */
	public void setBizcreattime(String bizcreattime) {
		set("bizcreattime", bizcreattime);
	}
	
	/**
	 * 预下单创建时间
	 */
	public String getBizcreattime() {
		return getStr("bizcreattime");
	}

	/**
	 * 订单完成时间
	 */
	public void setBizcompletetime(String bizcompletetime) {
		set("bizcompletetime", bizcompletetime);
	}
	
	/**
	 * 订单完成时间
	 */
	public String getBizcompletetime() {
		return getStr("bizcompletetime");
	}

	/**
	 * 订单错误信息
	 */
	public void setOrdererrormsg(String ordererrormsg) {
		set("ordererrormsg", ordererrormsg);
	}
	
	/**
	 * 订单错误信息
	 */
	public String getOrdererrormsg() {
		return getStr("ordererrormsg");
	}

	/**
	 * 同步状态：1：初始化；2：未完成；3：完成
	 */
	public void setCoinsyn(Short coinsyn) {
		set("coinsyn", coinsyn);
	}
	
	/**
	 * 同步状态：1：初始化；2：未完成；3：完成
	 */
	public Short getCoinsyn() {
		return getShort("coinsyn");
	}

	/**
	 * 发起的ip
	 */
	public void setIp(String ip) {
		set("ip", ip);
	}
	
	/**
	 * 发起的ip
	 */
	public String getIp() {
		return getStr("ip");
	}

	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setDevice(Short device) {
		set("device", device);
	}
	
	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public Short getDevice() {
		return getShort("device");
	}

	/**
	 * 发起的app版本号
	 */
	public void setAppversion(String appversion) {
		set("appversion", appversion);
	}
	
	/**
	 * 发起的app版本号
	 */
	public String getAppversion() {
		return getStr("appversion");
	}

	/**
	 * 队列处理时间
	 */
	public void setQueuetime(java.util.Date queuetime) {
		set("queuetime", queuetime);
	}
	
	/**
	 * 队列处理时间
	 */
	public java.util.Date getQueuetime() {
		return getDate("queuetime");
	}

	/**
	 * 银行卡卡号-掩码
	 */
	public void setBankcardnumber(String bankcardnumber) {
		set("bankcardnumber", bankcardnumber);
	}
	
	/**
	 * 银行卡卡号-掩码
	 */
	public String getBankcardnumber() {
		return getStr("bankcardnumber");
	}

	/**
	 * 银行代码
	 */
	public void setBankcode(String bankcode) {
		set("bankcode", bankcode);
	}
	
	/**
	 * 银行代码
	 */
	public String getBankcode() {
		return getStr("bankcode");
	}

	/**
	 * 银行名称
	 */
	public void setBankname(String bankname) {
		set("bankname", bankname);
	}
	
	/**
	 * 银行名称
	 */
	public String getBankname() {
		return getStr("bankname");
	}

	/**
	 * 银行icon
	 */
	public void setBankicon(String bankicon) {
		set("bankicon", bankicon);
	}
	
	/**
	 * 银行icon
	 */
	public String getBankicon() {
		return getStr("bankicon");
	}

	/**
	 * 提现账号
	 */
	public void setWithholdAccount(String withholdAccount) {
		set("withholdAccount", withholdAccount);
	}

	/**
	 * 提现账号
	 */
	public String getWithholdAccount() {
		return getStr("withholdAccount");
	}


	/**
	 * 实际到账(分)
	 */
	public void setWithholdType(Integer withholdType) {
		set("withholdType", withholdType);
	}

	/**
	 * 实际到账(分)
	 */
	public Integer getWithholdType() {
		return getInt("withholdType");
	}


	/**
	 * 查询同步:1：回调成功；2：否；3：查询同步
	 */
	public void setQuerysyn(Short querysyn) {
		set("querysyn", querysyn);
	}
	
	/**
	 * 查询同步:1：回调成功；2：否；3：查询同步
	 */
	public Short getQuerysyn() {
		return getShort("querysyn");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

