
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCircleUidCircleidSetting<M extends BaseCircleUidCircleidSetting<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() {
		return getInt("uid");
	}

	public void setCircleId(Integer circleId) {
		set("circle_id", circleId);
	}

	public Integer getCircleId() {
		return getInt("circle_id");
	}
}

