
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMomentsComments<M extends BaseMomentsComments<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setPid(Integer pid) {
		set("pid", pid);
	}

	public Integer getPid() {
		return getInt("pid");
	}

	public void setMid(Integer mid) {
		set("mid", mid);
	}

	public Integer getMid() {
		return getInt("mid");
	}

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 头像
	 */
	public void setAvatar(String avatar) {
		set("avatar", avatar);
	}

	/**
	 * 头像
	 */
	public String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 内容
	 */
	public void setContent(String content) {
		set("content", content);
	}

	/**
	 * 内容
	 */
	public String getContent() {
		return getStr("content");
	}

	/**
	 * 发布时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 发布时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}


	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

}

