
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmailSendLog<M extends BaseEmailSendLog<M>> extends TioModel<M> implements IBean {

	/**
	 * 发给谁
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 发给谁
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 发往的邮箱
	 */
	public void setEmailto(java.lang.String emailto) {
		set("emailto", emailto);
	}
	
	/**
	 * 发往的邮箱
	 */
	public java.lang.String getEmailto() {
		return getStr("emailto");
	}

	/**
	 * 邮件类型，1：注册邮件
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 邮件类型，1：注册邮件
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 发送状态，1：成功，2：失败
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 发送状态，1：成功，2：失败
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	public void setSession(java.lang.String session) {
		set("session", session);
	}
	
	public java.lang.String getSession() {
		return getStr("session");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * ip_info表的id
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * ip_info表的id
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * user_agent表的id，浏览器信息id
	 */
	public void setUaid(java.lang.Integer uaid) {
		set("uaid", uaid);
	}
	
	/**
	 * user_agent表的id，浏览器信息id
	 */
	public java.lang.Integer getUaid() {
		return getInt("uaid");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 验证码
	 */
	public void setAuthcode(java.lang.String authcode) {
		set("authcode", authcode);
	}
	
	/**
	 * 验证码
	 */
	public java.lang.String getAuthcode() {
		return getStr("authcode");
	}

	/**
	 * 邮件标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 邮件标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 邮件内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 邮件内容
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}

	/**
	 * 邮箱服务器
	 */
	public void setEmailserver(java.lang.String emailserver) {
		set("emailserver", emailserver);
	}
	
	/**
	 * 邮箱服务器
	 */
	public java.lang.String getEmailserver() {
		return getStr("emailserver");
	}

	/**
	 * 从哪个邮箱发出
	 */
	public void setEmailfrom(java.lang.String emailfrom) {
		set("emailfrom", emailfrom);
	}
	
	/**
	 * 从哪个邮箱发出
	 */
	public java.lang.String getEmailfrom() {
		return getStr("emailfrom");
	}

	/**
	 * 源邮箱密码(加密后的)
	 */
	public void setEmailpwd(java.lang.String emailpwd) {
		set("emailpwd", emailpwd);
	}
	
	/**
	 * 源邮箱密码(加密后的)
	 */
	public java.lang.String getEmailpwd() {
		return getStr("emailpwd");
	}

}

