
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupMeta<M extends BaseWxGroupMeta<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 群id
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 群id
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 所有都激活：1：是；2：否
	 */
	public void setAllactflag(java.lang.Short allactflag) {
		set("allactflag", allactflag);
	}
	
	/**
	 * 所有都激活：1：是；2：否
	 */
	public java.lang.Short getAllactflag() {
		return getShort("allactflag");
	}

	/**
	 * 所有都有消息：1：是；2：否
	 */
	public void setAllstartflag(java.lang.Short allstartflag) {
		set("allstartflag", allstartflag);
	}
	
	/**
	 * 所有都有消息：1：是；2：否
	 */
	public java.lang.Short getAllstartflag() {
		return getShort("allstartflag");
	}

	/**
	 * 全员禁用：1：是；2：否
	 */
	public void setForbiddenflag(java.lang.Short forbiddenflag) {
		set("forbiddenflag", forbiddenflag);
	}
	
	/**
	 * 全员禁用：1：是；2：否
	 */
	public java.lang.Short getForbiddenflag() {
		return getShort("forbiddenflag");
	}

	/**
	 * 群人数
	 */
	public void setJoinnum(java.lang.Short joinnum) {
		set("joinnum", joinnum);
	}
	
	/**
	 * 群人数
	 */
	public java.lang.Short getJoinnum() {
		return getShort("joinnum");
	}

	/**
	 * 退群次数
	 */
	public void setLeavecount(java.lang.Short leavecount) {
		set("leavecount", leavecount);
	}
	
	/**
	 * 退群次数
	 */
	public java.lang.Short getLeavecount() {
		return getShort("leavecount");
	}

	/**
	 * 踢人次数
	 */
	public void setKickcount(java.lang.Short kickcount) {
		set("kickcount", kickcount);
	}
	
	/**
	 * 踢人次数
	 */
	public java.lang.Short getKickcount() {
		return getShort("kickcount");
	}

	/**
	 * 群主转让次数
	 */
	public void setTransfercount(java.lang.Short transfercount) {
		set("transfercount", transfercount);
	}
	
	/**
	 * 群主转让次数
	 */
	public java.lang.Short getTransfercount() {
		return getShort("transfercount");
	}

	/**
	 * 最后一条消息id-废弃
	 */
	public void setLastmsgid(java.lang.Long lastmsgid) {
		set("lastmsgid", lastmsgid);
	}
	
	/**
	 * 最后一条消息id-废弃
	 */
	public java.lang.Long getLastmsgid() {
		return getLong("lastmsgid");
	}

	/**
	 * 消息条数
	 */
	public void setMsgcount(java.lang.Integer msgcount) {
		set("msgcount", msgcount);
	}
	
	/**
	 * 消息条数
	 */
	public java.lang.Integer getMsgcount() {
		return getInt("msgcount");
	}

	/**
	 *  群创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 *  群创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 *  群资料更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 *  群资料更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

