
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxChatDelItem<M extends BaseWxChatDelItem<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setChatlinkid(java.lang.Long chatlinkid) {
		set("chatlinkid", chatlinkid);
	}
	
	public java.lang.Long getChatlinkid() {
		return getLong("chatlinkid");
	}

	/**
	 * 聊天模式：1：私聊；2：群聊
	 */
	public void setChatmode(java.lang.Short chatmode) {
		set("chatmode", chatmode);
	}
	
	/**
	 * 聊天模式：1：私聊；2：群聊
	 */
	public java.lang.Short getChatmode() {
		return getShort("chatmode");
	}

	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public void setBizid(java.lang.Long bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public java.lang.Long getBizid() {
		return getLong("bizid");
	}

	/**
	 * 用户uid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户uid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

