
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxWalletGrabRedItem<M extends BaseWxWalletGrabRedItem<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 红包id
	 */
	public void setRid(java.lang.Integer rid) {
		set("rid", rid);
	}
	
	/**
	 * 红包id
	 */
	public java.lang.Integer getRid() {
		return getInt("rid");
	}

	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public void setChatbizid(java.lang.Long chatbizid) {
		set("chatbizid", chatbizid);
	}
	
	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public java.lang.Long getChatbizid() {
		return getLong("chatbizid");
	}

	/**
	 * 聊天模式：1：私聊；2：群聊
	 */
	public void setChatmode(java.lang.Short chatmode) {
		set("chatmode", chatmode);
	}
	
	/**
	 * 聊天模式：1：私聊；2：群聊
	 */
	public java.lang.Short getChatmode() {
		return getShort("chatmode");
	}

	/**
	 * 发送方uid
	 */
	public void setSenduid(java.lang.Integer senduid) {
		set("senduid", senduid);
	}
	
	/**
	 * 发送方uid
	 */
	public java.lang.Integer getSenduid() {
		return getInt("senduid");
	}

	/**
	 * 发送方钱包id
	 */
	public void setSendwalletid(java.lang.String sendwalletid) {
		set("sendwalletid", sendwalletid);
	}
	
	/**
	 * 发送方钱包id
	 */
	public java.lang.String getSendwalletid() {
		return getStr("sendwalletid");
	}

	/**
	 * 随机红包id
	 */
	public void setRandomid(java.lang.Integer randomid) {
		set("randomid", randomid);
	}
	
	/**
	 * 随机红包id
	 */
	public java.lang.Integer getRandomid() {
		return getInt("randomid");
	}

	/**
	 * 请求id
	 */
	public void setReqid(java.lang.String reqid) {
		set("reqid", reqid);
	}
	
	/**
	 * 请求id
	 */
	public java.lang.String getReqid() {
		return getStr("reqid");
	}

	/**
	 * 商户id
	 */
	public void setMerid(java.lang.String merid) {
		set("merid", merid);
	}
	
	/**
	 * 商户id
	 */
	public java.lang.String getMerid() {
		return getStr("merid");
	}

	/**
	 * 商户订单号-转账
	 */
	public void setMerorderid(java.lang.String merorderid) {
		set("merorderid", merorderid);
	}
	
	/**
	 * 商户订单号-转账
	 */
	public java.lang.String getMerorderid() {
		return getStr("merorderid");
	}

	/**
	 * 钱包id
	 */
	public void setWalletid(java.lang.String walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 钱包id
	 */
	public java.lang.String getWalletid() {
		return getStr("walletid");
	}

	/**
	 * 红包总金额(分）
	 */
	public void setCny(java.lang.Long cny) {
		set("cny", cny);
	}
	
	/**
	 * 红包总金额(分）
	 */
	public java.lang.Long getCny() {
		return getLong("cny");
	}

	/**
	 * 初始化状态：1；成功：2；初始化；3：分配取消
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 初始化状态：1；成功：2；初始化；3：分配取消
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 抢红包时间
	 */
	public void setGrabtime(java.util.Date grabtime) {
		set("grabtime", grabtime);
	}
	
	/**
	 * 抢红包时间
	 */
	public java.util.Date getGrabtime() {
		return getDate("grabtime");
	}

	public void setBizcreattime(java.util.Date bizcreattime) {
		set("bizcreattime", bizcreattime);
	}
	
	public java.util.Date getBizcreattime() {
		return getDate("bizcreattime");
	}

	/**
	 * 红包完成时间-抢完/超市
	 */
	public void setCompletetime(java.lang.String completetime) {
		set("completetime", completetime);
	}
	
	/**
	 * 红包完成时间-抢完/超市
	 */
	public java.lang.String getCompletetime() {
		return getStr("completetime");
	}

	public void setBizcompletetime(java.util.Date bizcompletetime) {
		set("bizcompletetime", bizcompletetime);
	}
	
	public java.util.Date getBizcompletetime() {
		return getDate("bizcompletetime");
	}

	/**
	 * 订单错误信息
	 */
	public void setOrdererrormsg(java.lang.String ordererrormsg) {
		set("ordererrormsg", ordererrormsg);
	}
	
	/**
	 * 订单错误信息
	 */
	public java.lang.String getOrdererrormsg() {
		return getStr("ordererrormsg");
	}

	/**
	 * 同步状态：1：已完成；2：未完成
	 */
	public void setCoinsyn(java.lang.Short coinsyn) {
		set("coinsyn", coinsyn);
	}
	
	/**
	 * 同步状态：1：已完成；2：未完成
	 */
	public java.lang.Short getCoinsyn() {
		return getShort("coinsyn");
	}

	/**
	 * 发起的ip
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 发起的ip
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setDevice(java.lang.Short device) {
		set("device", device);
	}
	
	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public java.lang.Short getDevice() {
		return getShort("device");
	}

	/**
	 * 发起的app版本号
	 */
	public void setAppversion(java.lang.String appversion) {
		set("appversion", appversion);
	}
	
	/**
	 * 发起的app版本号
	 */
	public java.lang.String getAppversion() {
		return getStr("appversion");
	}

	/**
	 * 队列处理时间
	 */
	public void setQueuetime(java.util.Date queuetime) {
		set("queuetime", queuetime);
	}
	
	/**
	 * 队列处理时间
	 */
	public java.util.Date getQueuetime() {
		return getDate("queuetime");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

