
package org.tio.sitexxx.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupMsg<M extends BaseGroupMsg<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 转发好友uid
	 */
	public void setUids(String uids) {
		set("uids", uids);
	}

	/**
	 * 转发好友uid
	 */
	public String getUids() {
		return getStr("uids");
	}


	/**
	 * 转发群组groupids
	 */
	public void setGroupids(String groupids) {
		set("groupids", groupids);
	}

	/**
	 * 转发好友uid
	 */
	public String getGroupids() {
		return getStr("groupids");
	}

	/**
	 * 内容类型，1、普通文本消息，4、音频，5、视频，6、图片
	 */
	public void setContenttype(Integer contenttype) {
		set("contenttype", contenttype);
	}

	/**
	 * 内容类型，1、普通文本消息，4、音频，5、视频，6、图片
	 */
	public Integer getContenttype() {
		return getInt("contenttype");
	}

	/**
	 * 消息内容
	 */
	public void setMsg(String msg) {
		set("msg", msg);
	}
	
	/**
	 * 消息内容
	 */
	public String  getMsg() {
		return getStr("msg");
	}


	/**
	 * 文件路径
	 */
	public void setFile(String file) {
		set("file", file);
	}

	/**
	 * 文件路径
	 */
	public String  getFile() {
		return getStr("file");
	}

	/**
	 * 该记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 该记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}


}

