
package org.tio.sitexxx.service.model.main.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupInblack<M extends BaseWxGroupInblack<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 群id
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 群id
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 封停原因
	 */
	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}
	
	/**
	 * 封停原因
	 */
	public java.lang.String getReason() {
		return getStr("reason");
	}

	/**
	 * 操作：1：封停；2：解封
	 */
	public void setOper(java.lang.Short oper) {
		set("oper", oper);
	}
	
	/**
	 * 操作：1：封停；2：解封
	 */
	public java.lang.Short getOper() {
		return getShort("oper");
	}

	/**
	 * 后台管理员uid
	 */
	public void setAdminuid(java.lang.Integer adminuid) {
		set("adminuid", adminuid);
	}
	
	/**
	 * 后台管理员uid
	 */
	public java.lang.Integer getAdminuid() {
		return getInt("adminuid");
	}

	/**
	 * 后台管理员昵称
	 */
	public void setAdminnick(java.lang.String adminnick) {
		set("adminnick", adminnick);
	}
	
	/**
	 * 后台管理员昵称
	 */
	public java.lang.String getAdminnick() {
		return getStr("adminnick");
	}

	/**
	 *  群创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 *  群创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 *  群资料更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 *  群资料更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

