
package org.tio.mg.service.model.conf.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAvatar<M extends BaseAvatar<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 头像性别：1：男；2：女：3：中性
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 头像性别：1：男；2：女：3：中性
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 本服务器上有路径
	 */
	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	/**
	 * 本服务器上有路径
	 */
	public java.lang.String getPath() {
		return getStr("path");
	}

	/**
	 * 原始的网址地址
	 */
	public void setInitUrl(java.lang.String initUrl) {
		set("init_url", initUrl);
	}
	
	/**
	 * 原始的网址地址
	 */
	public java.lang.String getInitUrl() {
		return getStr("init_url");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

