# api服务器和view服务器
	set $http_server_api http://127.0.0.1:6060;
	set $http_server_view http://127.0.0.1:10160;
		
# 页面所在目录
set $pages_dir "/home/bs/page";

# 上传资源服务器配置
# 文件根目录
set $upload_res_dir "/home/upload";

#  允许被嵌入的地址
# set $X_Frame_Options "ALLOW-FROM http://localhost/,http://222.186.136.66/,http://129.211.52.247/,http://admin.tiocloud.com/";
# set $X_Frame_Options SAMEORIGIN;
set $X_Frame_Options "";
