
package org.tio.sitexxx.service.model.conf;

import org.tio.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("area", "id", Area.class);
		arp.addMapping("auto_avatar", "id", AutoAvatar.class);
		arp.addMapping("auto_avatar_plate", "id", AutoAvatarPlate.class);
		arp.addMapping("avatar", "id", Avatar.class);
		arp.addMapping("bank_conf", "id", BankConf.class);
		arp.addMapping("conf", "name", Conf.class);
		arp.addMapping("conf_dev", "name", ConfDev.class);
		arp.addMapping("dict", "id", Dict.class);
		arp.addMapping("email_server", "email", EmailServer.class);
		arp.addMapping("httpcache", "id", Httpcache.class);
		arp.addMapping("ip_black_list", "id", IpBlackList.class);
		arp.addMapping("ip_white_list", "id", IpWhiteList.class);
		arp.addMapping("zh_cn_index_list", "id", ZhCnIndexList.class);
		arp.addMapping("client_conf", "name", ClientConf.class);
	}
}


