
package org.tio.sitexxx.service.model.conf;

import java.util.List;

import org.tio.sitexxx.service.model.conf.base.BaseArea;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	public static final Area dao = new Area().dao();

	private List<Area> childArea;

	private Area parentArea;

	public List<Area> getChildArea() {
		return childArea;
	}

	public void setChildArea(List<Area> childArea) {
		this.childArea = childArea;
	}

	public Area getParentArea() {
		return parentArea;
	}

	public void setParentArea(Area parentArea) {
		this.parentArea = parentArea;
	}

}
