
package org.tio.sitexxx.service.model.conf;


import org.tio.sitexxx.service.model.conf.base.BaseClientConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientConf extends BaseClientConf<ClientConf> {
	public static final ClientConf dao = new ClientConf().dao();
}
