
package org.tio.sitexxx.service.model.conf;

import org.tio.sitexxx.service.model.conf.base.BaseConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Conf extends BaseConf<Conf> {
	public static final Conf dao = new Conf().dao();
}
