
package org.tio.sitexxx.service.model.conf;

import org.tio.sitexxx.service.model.conf.base.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict().dao();
}
