
package org.tio.sitexxx.service.model.conf;

import org.tio.sitexxx.service.model.conf.base.BaseIpBlackList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IpBlackList extends BaseIpBlackList<IpBlackList> {
	public static final IpBlackList dao = new IpBlackList().dao();
}
