
package org.tio.sitexxx.service.model.conf.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.sitexxx.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientConf<M extends BaseClientConf<M>> extends TioModel<M> implements IBean {

	/**
	 * 配置名称
	 */
	public void setName(String name) {
		set("name", name);
	}
	
	/**
	 * 配置名称
	 */
	public String getName() {
		return getStr("name");
	}

	/**
	 * 参数值
	 */
	public void setValue(Integer value) {
		set("value", value);
	}
	
	/**
	 * 参数值
	 */
	public Integer getValue() {
		return getInt("value");
	}

	/**
	 * 类型 switch:开关 text:文本
	 */
	public void setType(String type) {
		set("type", type);
	}

	/**
	 * 类型 switch:开关 text:文本
	 */
	public String getType() {
		return getStr("type");
	}

	/**
	 * 配置备注
	 */
	public void setDescribe(String describe) {
		set("describe", describe);
	}
	
	/**
	 * 配置备注
	 */
	public String getDescribe() {
		return getStr("describe");
	}

	/**
	 * 该条记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该条记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

