
package org.tio.sitexxx.service.model.conf.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArea<M extends BaseArea<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 名字
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 名字
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 编码
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 编码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 父级编码
	 */
	public void setPcode(java.lang.String pcode) {
		set("pcode", pcode);
	}
	
	/**
	 * 父级编码
	 */
	public java.lang.String getPcode() {
		return getStr("pcode");
	}

	/**
	 * 状态：1：启用；2：禁言
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：启用；2：禁言
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 邮政编码
	 */
	public void setPost(java.lang.Integer post) {
		set("post", post);
	}
	
	/**
	 * 邮政编码
	 */
	public java.lang.Integer getPost() {
		return getInt("post");
	}

	/**
	 * 排序号
	 */
	public void setOrderby(java.lang.Integer orderby) {
		set("orderby", orderby);
	}
	
	/**
	 * 排序号
	 */
	public java.lang.Integer getOrderby() {
		return getInt("orderby");
	}

}

