
package org.tio.sitexxx.service.model.conf.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConf<M extends BaseConf<M>> extends TioModel<M> implements IBean {

	/**
	 * 配置标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	/**
	 * 配置标题
	 */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 参数名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 参数名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 参数值
	 */
	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	/**
	 * 参数值
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}

	/**
	 * 配置备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 配置备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}

	/**
	 * 类型：1：系统；2：业务
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 类型：1：系统；2：业务
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 该条记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该条记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

