
package org.tio.sitexxx.service.model.conf.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseZhCnIndexList<M extends BaseZhCnIndexList<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 中文字符
	 */
	public void setZhchar(java.lang.String zhchar) {
		set("zhchar", zhchar);
	}
	
	/**
	 * 中文字符
	 */
	public java.lang.String getZhchar() {
		return getStr("zhchar");
	}

	/**
	 * 字母索引
	 */
	public void setChatindex(java.lang.String chatindex) {
		set("chatindex", chatindex);
	}
	
	/**
	 * 字母索引
	 */
	public java.lang.String getChatindex() {
		return getStr("chatindex");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

