
package org.tio.mg.service.model.stat.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRegisterStat<M extends BaseUserRegisterStat<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 类型：1：日期；2：ip；3：ip小的周期
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 类型：1：日期；2：ip；3：ip小的周期
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 统计字符串：日期/ip地址
	 */
	public void setStatbizstr(java.lang.String statbizstr) {
		set("statbizstr", statbizstr);
	}
	
	/**
	 * 统计字符串：日期/ip地址
	 */
	public java.lang.String getStatbizstr() {
		return getStr("statbizstr");
	}

	/**
	 * 统计id：ipid
	 */
	public void setStatbizid(java.lang.Integer statbizid) {
		set("statbizid", statbizid);
	}
	
	/**
	 * 统计id：ipid
	 */
	public java.lang.Integer getStatbizid() {
		return getInt("statbizid");
	}

	/**
	 * 注册人数
	 */
	public void setRegcount(java.lang.Integer regcount) {
		set("regcount", regcount);
	}
	
	/**
	 * 注册人数
	 */
	public java.lang.Integer getRegcount() {
		return getInt("regcount");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

