
package org.tio.mg.service.model.stat.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGroupStat<M extends BaseGroupStat<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 类型：1：新增；3：删除
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 类型：1：新增；3：删除
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 统计字符串：日期/ip地址
	 */
	public void setDayperiod(java.lang.String dayperiod) {
		set("dayperiod", dayperiod);
	}
	
	/**
	 * 统计字符串：日期/ip地址
	 */
	public java.lang.String getDayperiod() {
		return getStr("dayperiod");
	}

	/**
	 * 群组新增数
	 */
	public void setAddcount(java.lang.Integer addcount) {
		set("addcount", addcount);
	}
	
	/**
	 * 群组新增数
	 */
	public java.lang.Integer getAddcount() {
		return getInt("addcount");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

