
package org.tio.mg.service.model.stat.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTioSlowRequest<M extends BaseTioSlowRequest<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 请求类型，1：api， 2：view
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 请求类型，1：api， 2：view
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 请求路径，含querystring
	 */
	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	/**
	 * 请求路径，含querystring
	 */
	public java.lang.String getPath() {
		return getStr("path");
	}

	/**
	 * 请求体
	 */
	public void setBody(java.lang.String body) {
		set("body", body);
	}
	
	/**
	 * 请求体
	 */
	public java.lang.String getBody() {
		return getStr("body");
	}

	/**
	 * 耗时，单位：毫秒
	 */
	public void setCost(java.lang.Long cost) {
		set("cost", cost);
	}
	
	/**
	 * 耗时，单位：毫秒
	 */
	public java.lang.Long getCost() {
		return getLong("cost");
	}

	/**
	 * 请求开始时间
	 */
	public void setStarttime(java.util.Date starttime) {
		set("starttime", starttime);
	}
	
	/**
	 * 请求开始时间
	 */
	public java.util.Date getStarttime() {
		return getDate("starttime");
	}

	/**
	 * 响应结束时间
	 */
	public void setEndtime(java.util.Date endtime) {
		set("endtime", endtime);
	}
	
	/**
	 * 响应结束时间
	 */
	public java.util.Date getEndtime() {
		return getDate("endtime");
	}

	/**
	 * 当前用户
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 当前用户
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 当前的session
	 */
	public void setSession(java.lang.String session) {
		set("session", session);
	}
	
	/**
	 * 当前的session
	 */
	public java.lang.String getSession() {
		return getStr("session");
	}

}

