## 有域名则配域名，譬如sub1.t-io.org
my.ip=192.168.31.2
bs.ip=192.168.31.2

## uuid start 
# 1、要保证每台不同的机器，这两个值的搭配值不一样
# 2、取值范围[1-31]
uuid.workerid=2
uuid.datacenter=1

#独立计划任务执行标识：执行：true；不执行：false，同一个集群中只有一台机器配成true
quartz.open.flag=true
#消息通知处理：执行：true；不执行：false，同一个集群中只有一台机器配成true
msg.topic.flag=true
