# 钱包模式 1: 第三方钱包，2本地钱包
pay.mode=2

# 程序运行模式：1、开发，2、测试，3、生产环境
dev.mode=1

# 是否启动im，1：启动，2：不启动
start.im=2

# 是否启动view，1：启动，2：不启动
start.view=1

#操作开启开关：true:开启；false:不开启
oper.open.flag=true

# 生产环境配成false，开发环境无所谓
tio.setCheckLastVersion = false

# 是否启动flashpolicyserver，1：启动，2：不启动
#用flash与服务器交互时，会用到，譬如基于flash的播放器
start.flash.policy.server=2

# 系统参数，系统参数以systemparam.开头，系统启动时会自动调用System.setProperty()，譬如：System.setProperty("TIO_MAX_POOL_SIZE_FOR_TIO", 64)
systemparam.TIO_MAX_POOL_SIZE_FOR_TIO = 32
systemparam.TIO_MAX_POOL_SIZE_FOR_GROUP = 256
systemparam.org.freemarker.loggerLibrary = SLF4J

# view项目的模型文件，生产环境和测试环境配成webpack.json，开发环境配成webpack-dev.json
#1、用webpack.json会压缩html、js、css
#2、用webpack.json会无视js中的log()、info()、error()函数；用webpack-dev.json这几个函数分别对应console.log()、console.info()、console.error()
view.model.config.file=webpack-dev.json

# web api工程中，是否启动httpcache表中配置的业务缓存，1：启用，2：不启用
web.api.use.http.cache=1
# web view工程，是否启动httpcache表中配置的业务缓存，1：启用，2：不启用
web.view.use.http.cache=1

# 预加载 1、加载，2、不加载
view.preAccess=2

# 网站地址
site=http://192.168.31.2:9527


#上传资源服务器
#1、这个服务器是单纯的nginx服务器，并不经过java
#2、对照upload.t-io.org.conf一起理解
# res.server=https://ctr2.atex.cc/
# res.server=https://qingxiao.yourda.cc/
res.server=https://qingxiao.yourda.cc/

#1、用户通过http-api服务器上传的文件会存在这个目录下
#2、用户访问这些资源只通过nginx访问，并不经过http-api服务器
#3、对照upload.t-io.org.conf一起理解，此值与upload.t-io.org.conf文件的"server -> location -> root"配置值一样
res.root=D:/AAA/upload
#res.root=/opt/upload

#mysql后台数据库备份存放的目录
#mysql.backup.backend.dir=/data/mysqlbackup/backend
mysql.backup.backend.dir=D:/AAA/mysqlbackup/backend

#用于维持tio http session的cookie name，可以不用修改
#1、如果开发环境和测试环境的主域名一样，不同环境建议设置不同值，这样同时访问两个环境时cookie不会相互干扰
http.session.cookie.name=tio_mg_session

##    http 配置 start
#监听端口
http.api.port = 6061
http.view.port = 10161

#静态资源目录，包含html, js, css, 图片等
#配成和http.view.page一样的
#http.api.page=/home/mg/page/dist
http.api.page=D:/AAA/mg-page
# 视图资源目录，包含html, js, css, 图片等，其中非res目录下的html、js、css是支持freemarker的
# nginx.conf有个配置项：location ~ /res/.+/.*$ {...}
#http.view.page=D:/tio/tio-site/src/backend/all/src/main/resources/config/page
#http.view.page=/config/page
#http.view.page=D:/tio/backpage/page
#http.view.page=/home/mg/page/dist
http.view.page=D:/AAA/mg-page

#解码异常时，是否打印日志，开发环境建议开启
http.api.logWhenDecodeError = true
http.view.logWhenDecodeError = true
im.logWhenDecodeError = true
im.ws.logWhenDecodeError = true

#静态资源缓存时间，小于等于0则不缓存静态资源，单位：秒，（3600=1小时，86400=24小时，2592000=30天，15552000=180天）
#1、生产环境的html、js、css是会加载到内存缓存起来的，当你更换这些文件时，并不会立即生效（你可以通过"遥控"下的"清空静态资源"立即生效）
#2、开发环境的配置值，负数表示不缓存，这样就不用频繁的清空缓存了
http.maxLiveTimeOfStaticRes=864000
# 上传文件允许的最大size，单位：KB
http.max_length_of_multi_body = 204800
# POST时允许的最大size，单位：KB
http.max_length_of_post_body = 204800

## cookie域名，生产环境应该是.t-io.org
http.cookie.domain=.local.amdin

## 是否被代理了，如果运行在nginx等的后面，此值要填true
http.isproxied=true

#------------ 数据库配置 start ---------
db.jdbc.pool.initialSize=1
db.jdbc.pool.maxActive=100
db.jdbc.pool.minIdle=1
db.jdbc.driverClassName=com.mysql.cj.jdbc.Driver
#db.jdbc.filters=slf4j,config,stat,wall
db.jdbc.filters=

db.jdbc.validationQuery=SELECT 'x'

#注意格式，必须是tio_site_xxxx格式
db.jdbc.multi.name=tio_site_main,tio_site_stat,tio_site_conf,tio_mg

#业务库
tio_site_main.jdbc.url=jdbc:mysql://${DB_HOST}:3306/tio_site_main?generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull
tio_site_main.jdbc.driverClassName=${db.jdbc.driverClassName}
tio_site_main.jdbc.username=${DB_USER}
tio_site_main.jdbc.password=${DB_PASSWORD}
tio_site_main.dbType=mysql

tio_site_stat.jdbc.url=jdbc:mysql://${DB_HOST}:3306/tio_site_stat?generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull
tio_site_stat.jdbc.driverClassName=${db.jdbc.driverClassName}
tio_site_stat.jdbc.username=${DB_USER}
tio_site_stat.jdbc.password=${DB_PASSWORD}
tio_site_stat.dbType=mysql

tio_site_conf.jdbc.url=jdbc:mysql://${DB_HOST}:3306/tio_site_conf?generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull
tio_site_conf.jdbc.driverClassName=${db.jdbc.driverClassName}
tio_site_conf.jdbc.username=${DB_USER}
tio_site_conf.jdbc.password=${DB_PASSWORD}
tio_site_conf.dbType=mysql

tio_mg.jdbc.url=jdbc:mysql://${DB_HOST}:3306/tio_mg?generateSimpleParameterMetadata=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull
tio_mg.jdbc.driverClassName=${db.jdbc.driverClassName}
tio_mg.jdbc.username=${DB_USER}
tio_mg.jdbc.password=${DB_PASSWORD}
tio_mg.dbType=mysql
#------------ 数据库配置   end ---------

#启动清空配置缓存-开发模式设置为true;正式环境建议false
clear.cache.flag=true

#------------ redis start ---------
redis.cluster.flag=false
redis.ip=192.168.31.148
redis.port=6379
redis.password=
redis.cluster.address=redis://127.0.0.1:7000,redis://127.0.0.1:7001,redis://127.0.0.1:7002,redis://127.0.0.1:7003,redis://127.0.0.1:7004,redis://127.0.0.1:7005,redis://127.0.0.1:7006,redis://127.0.0.1:7007,redis://127.0.0.1:7008,redis://127.0.0.1:7009,redis://127.0.0.1:7010,redis://127.0.0.1:7011
#------------ redis   end ---------

# QPS
request.permitsPerSecond=4000000
# 清理本阶段警告的时间间隔，参考值1000 * 60 * 60 * 2，单位为ms
request.warnClearInterval=300
# 本阶段最多警告多次数，参考值10
request.maxWarnCount=5000000
# 一共最多警告多次数
request.maxAllWarnCount=200000
#前面多少条消息不计入令牌桶
skip.warn.count = 80000000

#------------ im server end ------------------------
#im服务地址
im.server=http://192.168.31.2

# cloudflare / tencentoss
oss-type=tencentoss
# Cloudflare R2
cloudflare.r2-access-key=88cbe45580fc5725986f0c1ffd1db6e3
cloudflare.r2-secret-key=2f96fe4757294d3be402fc73fafa168231975d0f3d6365c03f8f509ecd8a1a76
cloudflare.r2-bucket-name=ctcx
cloudflare.r2-endpoint=https://0fd4c030de5520eae6227e1c590a64f4.r2.cloudflarestorage.com

tencentoss.secret-id=IKIDtoY7VjnuzudK4g9QVP7dw52oOlvuiLo6
tencentoss.secret-key=CE4jCRXQ6aqtjMtNirmU0JPL7g3DLI2Z
tencentoss.bucket-name=qingm188-1333631480
tencentoss.region=ap-hongkong

