http.session.cache.name = http_session_cache_name_0321

http.api.page500 = /p500/index.html
http.api.page404 = /p400/index.html
http.view.page500 = /p500/index.html
http.view.page404 = /p400/index.html

http.api.readbuffersize=2048
http.view.readbuffersize=1024
im.ws.readbuffersize=1024
im.socket.readbuffersize=1024

# session超时时间，单位：秒，（3600=1小时，86400=24小时，2592000=30天，15552000=180天）
http.session.timeout = 600


# contextpath，要么是空串，要么是/开头的
http.api.contextpath = /tioadmin
http.api.suffix = .admin_x
http.view.suffix =
http.view.contextpath = 

freemarker.suffix=txt|js|css|html|htm|json|xml
##    http 配置 end

############################################################################################################################################


# 默认的替换敏感词的串
sensitive.words.replace.text = *


#生产环境的网站
product.site=https://www.t-io.org

#获取MG_TIO_ACCESS_TOKEN的几个key
access.token.android.key1=kjmnopdc
access.token.android.key2=KjnbopSy
access.token.android.key3=EijBbMgHsjiSoleT

access.token.ios.key1=LiNhEops
access.token.ios.key2=LmhSuESp
access.token.ios.key3=PlkDnjSmySuiEjhY

access.token.pc.key1=UijSoEpB
access.token.pc.key2=PkjSmTnb
access.token.pc.key3=uPezilSoTLyzkMop

pwd.key.login.aes=xOezYlYsPebzEolO
pwd.key.register.aes=iOezXlTsOebzEolU

#第三方登录
#----QQ（PC）
third.login.qq.pc.AppID=
third.login.qq.pc.AppSecret=
#----微信（PC）
third.login.wechat.pc.AppID=
third.login.wechat.pc.AppSecret=
#----新浪微博（PC）
third.login.weibo.pc.AppID=
third.login.weibo.pc.AppSecret=
#----抖音（PC）
third.login.douyin.pc.AppID=
third.login.douyin.pc.AppSecret=
#----OSC（PC）
third.login.osc.pc.AppID=
third.login.osc.pc.AppSecret=

#----苹果IMEI（苹果APP）
third.login.apple.app.key=


#苹果内购key, ios pay key
ios.pay.key=



#用于统计的websocket配置
stat.ws.protocol=wss
stat.ws.port=9324

#http-server-api启动时是否开启ssl，1：开启，2：不开启。因为http-server-api是运行在nginx后面，所以此处配成2
web.api.use.ssl=2

#阿里惠普字体的ttf文件路径
medium.font.ttf.file=classpath:config/font/Alibaba-PuHuiTi-Medium.ttf
#用户使用阿里惠普字体的字号
user.avatar.medium.font.size=84
#用户头像背景模板图片路径
user.avatar.base.background.img=classpath:config/font/backgroud.png