
package org.tio.mg.service.model.conf;

import org.tio.mg.service.model.conf.base.BaseAutoAvatar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoAvatar extends BaseAutoAvatar<AutoAvatar> {
	public static final AutoAvatar dao = new AutoAvatar().dao();
}
