
package org.tio.mg.service.model.conf;

import org.tio.mg.service.model.conf.base.BaseAvatar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Avatar extends BaseAvatar<Avatar> {
	public static final Avatar dao = new Avatar().dao();
}
