
package org.tio.mg.service.model.conf;

import org.tio.mg.service.model.conf.base.BaseConfDev;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfDev extends BaseConfDev<ConfDev> {
	public static final ConfDev dao = new ConfDev().dao();
}
