
package org.tio.mg.service.model.conf;

import org.tio.mg.service.model.conf.base.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict().dao();
	
	/**
	 * 插入的兄弟节点
	 */
	private Integer bid;

	public Integer getBid() {
		return bid;
	}

	public void setBid(Integer bid) {
		this.bid = bid;
	}

	/**
	 * 父节点名字
	 * @param pname
	 * @author xufei
	 * 2020年5月29日 下午3:10:18
	 */
	public void setPname(java.lang.String pname) {
		put("pname", pname);
	}
	
	/**
	 * 父节点名字
	 */
	public java.lang.String getPname() {
		return getStr("pname");
	}
}
