
package org.tio.mg.service.model.conf;

import org.tio.mg.service.model.conf.base.BaseEmailServer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmailServer extends BaseEmailServer<EmailServer> {
	public static final EmailServer dao = new EmailServer().dao();
}
