
package org.tio.mg.service.model.conf;

import org.tio.mg.service.model.conf.base.BaseZhCnIndexList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ZhCnIndexList extends BaseZhCnIndexList<ZhCnIndexList> {
	public static final ZhCnIndexList dao = new ZhCnIndexList().dao();
}
