
package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgUser<M extends BaseMgUser<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setLoginname(java.lang.String loginname) {
		set("loginname", loginname);
	}
	
	public java.lang.String getLoginname() {
		return getStr("loginname");
	}

	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}
	
	public java.lang.String getPwd() {
		return getStr("pwd");
	}

	/**
	 * 昵称
	 */
	public void setNick(java.lang.String nick) {
		set("nick", nick);
	}
	
	/**
	 * 昵称
	 */
	public java.lang.String getNick() {
		return getStr("nick");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setBindip(java.lang.String bindip) {
		set("bindip", bindip);
	}

	public java.lang.String getBindip() {
		return getStr("bindip");
	}

	/**
	 * 头像url
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 头像url
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 头像说明
	 */
	public void setAvatarbig(java.lang.String avatarbig) {
		set("avatarbig", avatarbig);
	}
	
	/**
	 * 头像说明
	 */
	public java.lang.String getAvatarbig() {
		return getStr("avatarbig");
	}

	/**
	 * 用户状态, 1：正常，2：未激活；3：违规，4：封停，5：注销
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 用户状态, 1：正常，2：未激活；3：违规，4：封停，5：注销
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * ipid
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * ipid
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}


	/**
	 * 谷歌绑定秘钥
	 */
	public void setSecretKey(java.lang.String secretkey) {
		set("secretkey", secretkey);
	}

	/**
	 * 谷歌绑定秘钥
	 */
	public java.lang.String getSecretKey() {
		return getStr("secretkey");
	}

	/**
	 * 谷歌绑定状态： 1：正常、2未绑定
	 */
	public void setIsBound(java.lang.Short status) {
		set("isbound", status);
	}

	/**
	 * 谷歌绑定状态： 1：正常、2未绑定
	 */
	public java.lang.Short getIsBound() {
		return getShort("isbound");
	}

}

