
package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgFavoritePath<M extends BaseMgFavoritePath<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 路径
	 */
	public void setRoutkey(java.lang.String routkey) {
		set("routkey", routkey);
	}
	
	/**
	 * 路径
	 */
	public java.lang.String getRoutkey() {
		return getStr("routkey");
	}

	/**
	 * 权限id
	 */
	public void setAid(java.lang.Integer aid) {
		set("aid", aid);
	}
	
	/**
	 * 权限id
	 */
	public java.lang.Integer getAid() {
		return getInt("aid");
	}

	/**
	 * 用户uid
	 */
	public void setMguid(java.lang.Integer mguid) {
		set("mguid", mguid);
	}
	
	/**
	 * 用户uid
	 */
	public java.lang.Integer getMguid() {
		return getInt("mguid");
	}

	/**
	 * 排序id
	 */
	public void setFindex(java.lang.Short findex) {
		set("findex", findex);
	}
	
	/**
	 * 排序id
	 */
	public java.lang.Short getFindex() {
		return getShort("findex");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

