
package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgReimburseCode<M extends BaseMgReimburseCode<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 序号
	 */
	public void setIndex(java.lang.Integer index) {
		set("index", index);
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getIndex() {
		return getInt("index");
	}

	/**
	 * 生成code
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 生成code
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 使用状态：1：是；2：否
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 使用状态：1：是；2：否
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

