
package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgUserBase<M extends BaseMgUserBase<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setMguid(java.lang.Integer mguid) {
		set("mguid", mguid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getMguid() {
		return getInt("mguid");
	}

	/**
	 * 姓名
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}
	
	/**
	 * 姓名
	 */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * 部门名称
	 */
	public void setDeptname(java.lang.String deptname) {
		set("deptname", deptname);
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getDeptname() {
		return getStr("deptname");
	}

	/**
	 * 绑定邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 绑定邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 绑定手机
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 绑定手机
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 手机是否激活：1：已激活；2：未激活
	 */
	public void setValidphone(java.lang.Short validphone) {
		set("validphone", validphone);
	}
	
	/**
	 * 手机是否激活：1：已激活；2：未激活
	 */
	public java.lang.Short getValidphone() {
		return getShort("validphone");
	}

	/**
	 * 邮箱是否已激活：1：已激活；2：未激活
	 */
	public void setValidemail(java.lang.Short validemail) {
		set("validemail", validemail);
	}
	
	/**
	 * 邮箱是否已激活：1：已激活；2：未激活
	 */
	public java.lang.Short getValidemail() {
		return getShort("validemail");
	}

	/**
	 * 个性签名
	 */
	public void setSign(java.lang.String sign) {
		set("sign", sign);
	}
	
	/**
	 * 个性签名
	 */
	public java.lang.String getSign() {
		return getStr("sign");
	}

	/**
	 * 性别：1：男；2：女
	 */
	public void setSex(java.lang.Short sex) {
		set("sex", sex);
	}
	
	/**
	 * 性别：1：男；2：女
	 */
	public java.lang.Short getSex() {
		return getShort("sex");
	}

	/**
	 * 生日
	 */
	public void setBirthday(java.lang.Long birthday) {
		set("birthday", birthday);
	}
	
	/**
	 * 生日
	 */
	public java.lang.Long getBirthday() {
		return getLong("birthday");
	}

	/**
	 * 地区：待定存储
	 */
	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	/**
	 * 地区：待定存储
	 */
	public java.lang.String getArea() {
		return getStr("area");
	}

	/**
	 * 行业
	 */
	public void setIndustry(java.lang.String industry) {
		set("industry", industry);
	}
	
	/**
	 * 行业
	 */
	public java.lang.String getIndustry() {
		return getStr("industry");
	}

	/**
	 * 职位
	 */
	public void setPosition(java.lang.String position) {
		set("position", position);
	}
	
	/**
	 * 职位
	 */
	public java.lang.String getPosition() {
		return getStr("position");
	}

	/**
	 * 爱好
	 */
	public void setHobby(java.lang.String hobby) {
		set("hobby", hobby);
	}
	
	/**
	 * 爱好
	 */
	public java.lang.String getHobby() {
		return getStr("hobby");
	}

	/**
	 * 收入
	 */
	public void setIncome(java.lang.String income) {
		set("income", income);
	}
	
	/**
	 * 收入
	 */
	public java.lang.String getIncome() {
		return getStr("income");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

	/**
	 * 最新消息推送时间戳
	 */
	public void setMsgpushtime(java.util.Date msgpushtime) {
		set("msgpushtime", msgpushtime);
	}
	
	/**
	 * 最新消息推送时间戳
	 */
	public java.util.Date getMsgpushtime() {
		return getDate("msgpushtime");
	}

}

