
package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgAuth<M extends BaseMgAuth<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 父节点
	 */
	public void setPid(java.lang.Integer pid) {
		set("pid", pid);
	}
	
	/**
	 * 父节点
	 */
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 深度
	 */
	public void setDeep(java.lang.Short deep) {
		set("deep", deep);
	}
	
	/**
	 * 深度
	 */
	public java.lang.Short getDeep() {
		return getShort("deep");
	}

	/**
	 * 权限名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 权限名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 访问路径key
	 */
	public void setRoutekey(java.lang.String routekey) {
		set("routekey", routekey);
	}
	
	/**
	 * 访问路径key
	 */
	public java.lang.String getRoutekey() {
		return getStr("routekey");
	}

	/**
	 * 权限url：页面url/操作url
	 */
	public void setAuthurl(java.lang.String authurl) {
		set("authurl", authurl);
	}
	
	/**
	 * 权限url：页面url/操作url
	 */
	public java.lang.String getAuthurl() {
		return getStr("authurl");
	}

	/**
	 * 权限排序字段
	 */
	public void setAindex(java.lang.Short aindex) {
		set("aindex", aindex);
	}
	
	/**
	 * 权限排序字段
	 */
	public java.lang.Short getAindex() {
		return getShort("aindex");
	}

	/**
	 * 权限类型：1：菜单；2：页面；3：操作
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 权限类型：1：菜单；2：页面；3：操作
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 图标字段
	 */
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	/**
	 * 图标字段
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 状态：1：有效；2：不可用
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：有效；2：不可用
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 日记记录标识：1：是；2：否
	 */
	public void setLogflag(java.lang.Short logflag) {
		set("logflag", logflag);
	}
	
	/**
	 * 日记记录标识：1：是；2：否
	 */
	public java.lang.Short getLogflag() {
		return getShort("logflag");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

