
package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgInvoiceReimbursement<M extends BaseMgInvoiceReimbursement<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 报销人
	 */
	public void setMguid(java.lang.Integer mguid) {
		set("mguid", mguid);
	}
	
	/**
	 * 报销人
	 */
	public java.lang.Integer getMguid() {
		return getInt("mguid");
	}

	/**
	 * 用户id
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 金额
	 */
	public void setAmount(java.lang.Double amount) {
		set("amount", amount);
	}
	
	/**
	 * 金额
	 */
	public java.lang.Double getAmount() {
		return getDouble("amount");
	}

	/**
	 * 单据数量
	 */
	public void setNum(java.lang.Short num) {
		set("num", num);
	}
	
	/**
	 * 单据数量
	 */
	public java.lang.Short getNum() {
		return getShort("num");
	}

	/**
	 * 状态：1：已下载；2：初始化
	 */
	public void setUploadstatus(java.lang.Short uploadstatus) {
		set("uploadstatus", uploadstatus);
	}
	
	/**
	 * 状态：1：已下载；2：初始化
	 */
	public java.lang.Short getUploadstatus() {
		return getShort("uploadstatus");
	}

	/**
	 * zipurl
	 */
	public void setFileurl(java.lang.String fileurl) {
		set("fileurl", fileurl);
	}
	
	/**
	 * zipurl
	 */
	public java.lang.String getFileurl() {
		return getStr("fileurl");
	}

	/**
	 * 状态：1：正常：3：删除
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：正常：3：删除
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 后台用户id
	 */
	public void setOperuid(java.lang.Integer operuid) {
		set("operuid", operuid);
	}
	
	/**
	 * 后台用户id
	 */
	public java.lang.Integer getOperuid() {
		return getInt("operuid");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 报销时间
	 */
	public void setReimtime(java.util.Date reimtime) {
		set("reimtime", reimtime);
	}
	
	/**
	 * 报销时间
	 */
	public java.util.Date getReimtime() {
		return getDate("reimtime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

