
package org.tio.mg.service.model.mg.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMgUserLoginLog<M extends BaseMgUserLoginLog<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 天周期
	 */
	public void setDayperiod(java.lang.String dayperiod) {
		set("dayperiod", dayperiod);
	}
	
	/**
	 * 天周期
	 */
	public java.lang.String getDayperiod() {
		return getStr("dayperiod");
	}

	/**
	 * 时间周期
	 */
	public void setTimeperiod(java.lang.String timeperiod) {
		set("timeperiod", timeperiod);
	}
	
	/**
	 * 时间周期
	 */
	public java.lang.String getTimeperiod() {
		return getStr("timeperiod");
	}

	/**
	 * 时间周期
	 */
	public void setHourperiod(java.lang.String hourperiod) {
		set("hourperiod", hourperiod);
	}
	
	/**
	 * 时间周期
	 */
	public java.lang.String getHourperiod() {
		return getStr("hourperiod");
	}

	/**
	 * userid
	 */
	public void setMguid(java.lang.Integer mguid) {
		set("mguid", mguid);
	}
	
	/**
	 * userid
	 */
	public java.lang.Integer getMguid() {
		return getInt("mguid");
	}

	/**
	 * 登录的ip
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 登录的ip
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 对应ip_info表的id
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * 对应ip_info表的id
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 移动设备号
	 */
	public void setImei(java.lang.String imei) {
		set("imei", imei);
	}
	
	/**
	 * 移动设备号
	 */
	public java.lang.String getImei() {
		return getStr("imei");
	}

	/**
	 * 创建时间
	 */
	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getTime() {
		return getDate("time");
	}

	/**
	 * sessionid其实就是token
	 */
	public void setSessionid(java.lang.String sessionid) {
		set("sessionid", sessionid);
	}
	
	/**
	 * sessionid其实就是token
	 */
	public java.lang.String getSessionid() {
		return getStr("sessionid");
	}

	/**
	 * 登录设置：1PC，2手机
	 */
	public void setDevicetype(java.lang.Short devicetype) {
		set("devicetype", devicetype);
	}
	
	/**
	 * 登录设置：1PC，2手机
	 */
	public java.lang.Short getDevicetype() {
		return getShort("devicetype");
	}

	/**
	 * 如果是手机，则带上手机公司相关信息 ，譬如华为P9
	 */
	public void setDeviceinfo(java.lang.String deviceinfo) {
		set("deviceinfo", deviceinfo);
	}
	
	/**
	 * 如果是手机，则带上手机公司相关信息 ，譬如华为P9
	 */
	public java.lang.String getDeviceinfo() {
		return getStr("deviceinfo");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

