
package org.tio.sitexxx.service.model.stat.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTioIpStat<M extends BaseTioIpStat<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 应用类型：1：ws，2、socket，11、web_view，12、web_api
	 */
	public void setAppType(java.lang.Short appType) {
		set("appType", appType);
	}
	
	/**
	 * 应用类型：1：ws，2、socket，11、web_view，12、web_api
	 */
	public java.lang.Short getAppType() {
		return getShort("appType");
	}

	/**
	 * 时长类型，单位：秒，譬如60，3600等
	 */
	public void setDurationType(java.lang.Long durationType) {
		set("durationType", durationType);
	}
	
	/**
	 * 时长类型，单位：秒，譬如60，3600等
	 */
	public java.lang.Long getDurationType() {
		return getLong("durationType");
	}

	/**
	 * 服务器，可以是域名也可以是ip，配置文件中的my.ip
	 */
	public void setServer(java.lang.String server) {
		set("server", server);
	}
	
	/**
	 * 服务器，可以是域名也可以是ip，配置文件中的my.ip
	 */
	public java.lang.String getServer() {
		return getStr("server");
	}

	/**
	 * 统计的开始时间点
	 */
	public void setStart(java.util.Date start) {
		set("start", start);
	}
	
	/**
	 * 统计的开始时间点
	 */
	public java.util.Date getStart() {
		return getDate("start");
	}

	/**
	 * 当前统计了多久，单位：毫秒
	 */
	public void setDuration(java.lang.Long duration) {
		set("duration", duration);
	}
	
	/**
	 * 当前统计了多久，单位：毫秒
	 */
	public java.lang.Long getDuration() {
		return getLong("duration");
	}

	/**
	 * 形如：59分45秒717毫秒
	 */
	public void setFormatedDuration(java.lang.String formatedDuration) {
		set("formatedDuration", formatedDuration);
	}
	
	/**
	 * 形如：59分45秒717毫秒
	 */
	public java.lang.String getFormatedDuration() {
		return getStr("formatedDuration");
	}

	/**
	 * 客户端ip， 对应到ip表的id字段
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * 客户端ip， 对应到ip表的id字段
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 解码异常的次数
	 */
	public void setDecodeErrorCount(java.lang.Integer decodeErrorCount) {
		set("decodeErrorCount", decodeErrorCount);
	}
	
	/**
	 * 解码异常的次数
	 */
	public java.lang.Integer getDecodeErrorCount() {
		return getInt("decodeErrorCount");
	}

	/**
	 * 收到该IP连接请求的次数
	 */
	public void setRequestCount(java.lang.Integer requestCount) {
		set("requestCount", requestCount);
	}
	
	/**
	 * 收到该IP连接请求的次数
	 */
	public java.lang.Integer getRequestCount() {
		return getInt("requestCount");
	}

	/**
	 * 当前处于连接状态的个数
	 */
	public void setActivatedCount(java.lang.Integer activatedCount) {
		set("activatedCount", activatedCount);
	}
	
	/**
	 * 当前处于连接状态的个数
	 */
	public java.lang.Integer getActivatedCount() {
		return getInt("activatedCount");
	}

	/**
	 * 本IP已发送的字节数
	 */
	public void setSentBytes(java.lang.Long sentBytes) {
		set("sentBytes", sentBytes);
	}
	
	/**
	 * 本IP已发送的字节数
	 */
	public java.lang.Long getSentBytes() {
		return getLong("sentBytes");
	}

	/**
	 * 本IP已发送的packet数
	 */
	public void setSentPackets(java.lang.Long sentPackets) {
		set("sentPackets", sentPackets);
	}
	
	/**
	 * 本IP已发送的packet数
	 */
	public java.lang.Long getSentPackets() {
		return getLong("sentPackets");
	}

	/**
	 * 本IP已处理的字节数
	 */
	public void setHandledBytes(java.lang.Long handledBytes) {
		set("handledBytes", handledBytes);
	}
	
	/**
	 * 本IP已处理的字节数
	 */
	public java.lang.Long getHandledBytes() {
		return getLong("handledBytes");
	}

	/**
	 * 本IP已处理的packet数
	 */
	public void setHandledPackets(java.lang.Long handledPackets) {
		set("handledPackets", handledPackets);
	}
	
	/**
	 * 本IP已处理的packet数
	 */
	public java.lang.Long getHandledPackets() {
		return getLong("handledPackets");
	}

	/**
	 * 本IP已接收的字节数
	 */
	public void setReceivedBytes(java.lang.Long receivedBytes) {
		set("receivedBytes", receivedBytes);
	}
	
	/**
	 * 本IP已接收的字节数
	 */
	public java.lang.Long getReceivedBytes() {
		return getLong("receivedBytes");
	}

	/**
	 * 本IP已接收了多少次TCP数据包
	 */
	public void setReceivedTcps(java.lang.Long receivedTcps) {
		set("receivedTcps", receivedTcps);
	}
	
	/**
	 * 本IP已接收了多少次TCP数据包
	 */
	public java.lang.Long getReceivedTcps() {
		return getLong("receivedTcps");
	}

	/**
	 * 本IP已接收的packet数
	 */
	public void setReceivedPackets(java.lang.Long receivedPackets) {
		set("receivedPackets", receivedPackets);
	}
	
	/**
	 * 本IP已接收的packet数
	 */
	public java.lang.Long getReceivedPackets() {
		return getLong("receivedPackets");
	}

	public void setPacketsPerTcpReceive(java.lang.Double packetsPerTcpReceive) {
		set("packetsPerTcpReceive", packetsPerTcpReceive);
	}
	
	public java.lang.Double getPacketsPerTcpReceive() {
		return getDouble("packetsPerTcpReceive");
	}

	/**
	 * 平均每次TCP接收到的字节数，这个可以用来监控慢攻击，配置PacketsPerTcpReceive定位慢攻击
	 */
	public void setBytesPerTcpReceive(java.lang.Double bytesPerTcpReceive) {
		set("bytesPerTcpReceive", bytesPerTcpReceive);
	}
	
	/**
	 * 平均每次TCP接收到的字节数，这个可以用来监控慢攻击，配置PacketsPerTcpReceive定位慢攻击
	 */
	public java.lang.Double getBytesPerTcpReceive() {
		return getDouble("bytesPerTcpReceive");
	}

}

