
package org.tio.sitexxx.service.model.stat.base;

import org.tio.sitexxx.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserTimeLoginStat<M extends BaseUserTimeLoginStat<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 天周期
	 */
	public void setDayperiod(java.lang.String dayperiod) {
		set("dayperiod", dayperiod);
	}
	
	/**
	 * 天周期
	 */
	public java.lang.String getDayperiod() {
		return getStr("dayperiod");
	}

	/**
	 * 人数统计：默认1，用户统计
	 */
	public void setUsercount(java.lang.Integer usercount) {
		set("usercount", usercount);
	}
	
	/**
	 * 人数统计：默认1，用户统计
	 */
	public java.lang.Integer getUsercount() {
		return getInt("usercount");
	}

	/**
	 * 总登录次数
	 */
	public void setTotalcount(java.lang.Integer totalcount) {
		set("totalcount", totalcount);
	}
	
	/**
	 * 总登录次数
	 */
	public java.lang.Integer getTotalcount() {
		return getInt("totalcount");
	}

	/**
	 * 小时0
	 */
	public void setHour0(java.lang.Integer hour0) {
		set("hour0", hour0);
	}
	
	/**
	 * 小时0
	 */
	public java.lang.Integer getHour0() {
		return getInt("hour0");
	}

	/**
	 * 小时1
	 */
	public void setHour1(java.lang.Integer hour1) {
		set("hour1", hour1);
	}
	
	/**
	 * 小时1
	 */
	public java.lang.Integer getHour1() {
		return getInt("hour1");
	}

	/**
	 * 小时2
	 */
	public void setHour2(java.lang.Integer hour2) {
		set("hour2", hour2);
	}
	
	/**
	 * 小时2
	 */
	public java.lang.Integer getHour2() {
		return getInt("hour2");
	}

	/**
	 * 小时3
	 */
	public void setHour3(java.lang.Integer hour3) {
		set("hour3", hour3);
	}
	
	/**
	 * 小时3
	 */
	public java.lang.Integer getHour3() {
		return getInt("hour3");
	}

	/**
	 * 小时4
	 */
	public void setHour4(java.lang.Integer hour4) {
		set("hour4", hour4);
	}
	
	/**
	 * 小时4
	 */
	public java.lang.Integer getHour4() {
		return getInt("hour4");
	}

	/**
	 * 小时5
	 */
	public void setHour5(java.lang.Integer hour5) {
		set("hour5", hour5);
	}
	
	/**
	 * 小时5
	 */
	public java.lang.Integer getHour5() {
		return getInt("hour5");
	}

	/**
	 * 小时6
	 */
	public void setHour6(java.lang.Integer hour6) {
		set("hour6", hour6);
	}
	
	/**
	 * 小时6
	 */
	public java.lang.Integer getHour6() {
		return getInt("hour6");
	}

	/**
	 * 小时7
	 */
	public void setHour7(java.lang.Integer hour7) {
		set("hour7", hour7);
	}
	
	/**
	 * 小时7
	 */
	public java.lang.Integer getHour7() {
		return getInt("hour7");
	}

	/**
	 * 小时8
	 */
	public void setHour8(java.lang.Integer hour8) {
		set("hour8", hour8);
	}
	
	/**
	 * 小时8
	 */
	public java.lang.Integer getHour8() {
		return getInt("hour8");
	}

	/**
	 * 小时9
	 */
	public void setHour9(java.lang.Integer hour9) {
		set("hour9", hour9);
	}
	
	/**
	 * 小时9
	 */
	public java.lang.Integer getHour9() {
		return getInt("hour9");
	}

	/**
	 * 小时10
	 */
	public void setHour10(java.lang.Integer hour10) {
		set("hour10", hour10);
	}
	
	/**
	 * 小时10
	 */
	public java.lang.Integer getHour10() {
		return getInt("hour10");
	}

	/**
	 * 小时11
	 */
	public void setHour11(java.lang.Integer hour11) {
		set("hour11", hour11);
	}
	
	/**
	 * 小时11
	 */
	public java.lang.Integer getHour11() {
		return getInt("hour11");
	}

	/**
	 * 小时12
	 */
	public void setHour12(java.lang.Integer hour12) {
		set("hour12", hour12);
	}
	
	/**
	 * 小时12
	 */
	public java.lang.Integer getHour12() {
		return getInt("hour12");
	}

	/**
	 * 小时13
	 */
	public void setHour13(java.lang.Integer hour13) {
		set("hour13", hour13);
	}
	
	/**
	 * 小时13
	 */
	public java.lang.Integer getHour13() {
		return getInt("hour13");
	}

	/**
	 * 小时14
	 */
	public void setHour14(java.lang.Integer hour14) {
		set("hour14", hour14);
	}
	
	/**
	 * 小时14
	 */
	public java.lang.Integer getHour14() {
		return getInt("hour14");
	}

	/**
	 * 小时15
	 */
	public void setHour15(java.lang.Integer hour15) {
		set("hour15", hour15);
	}
	
	/**
	 * 小时15
	 */
	public java.lang.Integer getHour15() {
		return getInt("hour15");
	}

	/**
	 * 小时16
	 */
	public void setHour16(java.lang.Integer hour16) {
		set("hour16", hour16);
	}
	
	/**
	 * 小时16
	 */
	public java.lang.Integer getHour16() {
		return getInt("hour16");
	}

	/**
	 * 小时17
	 */
	public void setHour17(java.lang.Integer hour17) {
		set("hour17", hour17);
	}
	
	/**
	 * 小时17
	 */
	public java.lang.Integer getHour17() {
		return getInt("hour17");
	}

	/**
	 * 小时18
	 */
	public void setHour18(java.lang.Integer hour18) {
		set("hour18", hour18);
	}
	
	/**
	 * 小时18
	 */
	public java.lang.Integer getHour18() {
		return getInt("hour18");
	}

	/**
	 * 小时19
	 */
	public void setHour19(java.lang.Integer hour19) {
		set("hour19", hour19);
	}
	
	/**
	 * 小时19
	 */
	public java.lang.Integer getHour19() {
		return getInt("hour19");
	}

	/**
	 * 小时20
	 */
	public void setHour20(java.lang.Integer hour20) {
		set("hour20", hour20);
	}
	
	/**
	 * 小时20
	 */
	public java.lang.Integer getHour20() {
		return getInt("hour20");
	}

	/**
	 * 小时21
	 */
	public void setHour21(java.lang.Integer hour21) {
		set("hour21", hour21);
	}
	
	/**
	 * 小时21
	 */
	public java.lang.Integer getHour21() {
		return getInt("hour21");
	}

	/**
	 * 小时22
	 */
	public void setHour22(java.lang.Integer hour22) {
		set("hour22", hour22);
	}
	
	/**
	 * 小时22
	 */
	public java.lang.Integer getHour22() {
		return getInt("hour22");
	}

	/**
	 * 小时23
	 */
	public void setHour23(java.lang.Integer hour23) {
		set("hour23", hour23);
	}
	
	/**
	 * 小时23
	 */
	public java.lang.Integer getHour23() {
		return getInt("hour23");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

