# 把http跳转到https
server {
    include vars.conf;
    listen 80;
    server_name reslocal.tiocloud.com;
    return 301 https://$server_name$request_uri;
}

server {
    include vars.conf;

    listen 443 ssl http2;
    server_name reslocal.tiocloud.com;

    # access_log logs/reslocal.tiocloud.com-access.txt main;

    if ($scheme = http) {
        return 301 https://$host$request_uri;
    }

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";
    add_header X-Frame-Options $X_Frame_Options;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Headers *;
    add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
	
    ssl_certificate cert/tiocloud/fullchain.crt;
    ssl_certificate_key cert/tiocloud/private.pem;
    include common-ssl.conf;

    etag on;
    gzip_vary on;


    location / {
        root $upload_res_dir;
        index index.html index.htm;
        etag on;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_valid 200 304 301 302 5d;
        proxy_cache_valid 404 1m;
        proxy_cache_valid any 3d;
        proxy_cache_key $host$uri$is_args$args;
        expires 5d;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

    }
}