
package org.tio.mg.service.model.stat;

import org.tio.mg.service.model.stat.base.BaseImeiStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ImeiStat extends BaseImeiStat<ImeiStat> {
	public static final ImeiStat dao = new ImeiStat().dao();
}
