
package org.tio.mg.service.model.stat;

import org.tio.mg.service.model.stat.base.BaseTioIpPathAccessStat;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TioIpPathAccessStat extends BaseTioIpPathAccessStat<TioIpPathAccessStat> {
	public static final TioIpPathAccessStat dao = new TioIpPathAccessStat().dao();

}
