
package org.tio.mg.service.model.stat;

import org.tio.mg.service.model.stat.base.BaseTioIpPullblackLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TioIpPullblackLog extends BaseTioIpPullblackLog<TioIpPullblackLog> {
	public static final TioIpPullblackLog dao = new TioIpPullblackLog().dao();

	public static interface Type {
		/**
		 * http请求太频繁
		 */
		short HTTP_REQUEST_TOO_FREQUENTLY = (short) 1;

		/**
		 * 恶意攻击，后面分类再定 
		 */
		short ATTACK = (short) 2;

		/**
		 * 被人工拉黑
		 */
		short MANUAL = (short) 3;

		/**
		 * IM请求太频繁
		 */
		short IM_REQUEST_TOO_FREQUENTLY = (short) 4;
	}
}
