
package org.tio.mg.service.model.stat;

import org.tio.mg.service.model.stat.base.BaseTioSlowRequest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TioSlowRequest extends BaseTioSlowRequest<TioSlowRequest> {
	public static final TioSlowRequest dao = new TioSlowRequest().dao();
}
