
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseAlbum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Album extends BaseAlbum<Album> {
	public static final Album dao = new Album().dao();
}
