
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseAlbumPhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AlbumPhoto extends BaseAlbumPhoto<AlbumPhoto> {
	public static final AlbumPhoto dao = new AlbumPhoto().dao();
}
