
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseAudio;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Audio extends BaseAudio<Audio> {
	public static final Audio dao = new Audio().dao();
}
