
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseChatroomJoinLeave;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ChatroomJoinLeave extends BaseChatroomJoinLeave<ChatroomJoinLeave> {
	public static final ChatroomJoinLeave dao = new ChatroomJoinLeave().dao();
	
	private boolean isChat = false;

	/**
	 * @return the isChat
	 */
	public boolean isChat() {
		return isChat;
	}

	/**
	 * @param isChat the isChat to set
	 */
	public void setChat(boolean isChat) {
		this.isChat = isChat;
	}
}
