
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseCircleComplaint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleComplaint extends BaseCircleComplaint<CircleComplaint> {
	public static final CircleComplaint dao = new CircleComplaint().dao();
}
