
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseCircleMemberInviteCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleMemberInviteCode extends BaseCircleMemberInviteCode<CircleMemberInviteCode> {
	public static final CircleMemberInviteCode dao = new CircleMemberInviteCode().dao();
}
