
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseCircleViewSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleViewSetting extends BaseCircleViewSetting<CircleViewSetting> {
	public static final CircleViewSetting dao = new CircleViewSetting().dao();
}
