
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseCircleMemberApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleMemberApply extends BaseCircleMemberApply<CircleMemberApply> {
	public static final CircleMemberApply dao = new CircleMemberApply().dao();
}
