
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseCircleArticleComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleArticleComment extends BaseCircleArticleComment<CircleArticleComment> {
	public static final CircleArticleComment dao = new CircleArticleComment().dao();
	private String nick;

	public String getNick() {
		return nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}
}
