
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseCircleMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleMember extends BaseCircleMember<CircleMember> {
	public static final CircleMember dao = new CircleMember().dao();
}
