
package org.tio.mg.service.model.main;



import org.tio.mg.service.model.main.base.BaseCircleArticle;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleArticle extends BaseCircleArticle<CircleArticle> {
	public static final CircleArticle dao = new CircleArticle().dao();
	private String nick;

	private List<CircleArticleComment> comments;

	private List<CircleArticleLike> likes;

	private Integer likesCount;

	public Integer getLikesCount() {
		return likesCount;
	}

	public void setLikesCount(Integer likesCount) {
		this.likesCount = likesCount;
	}


	public String getNick() {
		return nick;
	}

	public void setNick(String nick) {
		this.nick = nick;
	}

	public List<CircleArticleComment> getComments() {
		return comments;
	}

	public void setComments(List<CircleArticleComment> comments) {
		this.comments = comments;
	}

	public List<CircleArticleLike> getLikes() {
		return likes;
	}

	public void setLikes(List<CircleArticleLike> likes) {
		this.likes = likes;
	}
}
