
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseCircleApply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleApply extends BaseCircleApply<CircleApply> {
	public static final CircleApply dao = new CircleApply().dao();
}
