
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseCircleUidCityidSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CircleUidCityidSetting extends BaseCircleUidCityidSetting<CircleUidCityidSetting> {
	public static final CircleUidCityidSetting dao = new CircleUidCityidSetting().dao();
}
