
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class City extends BaseCity<City> {
	public static final City dao = new City().dao();
}
