
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseDemo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Demo extends BaseDemo<Demo> {
	public static final Demo dao = new Demo().dao();
}

