
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseEmailSendLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EmailSendLog extends BaseEmailSendLog<EmailSendLog> {
	public static final EmailSendLog dao = new EmailSendLog().dao();
}
