
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginLog extends BaseLoginLog<LoginLog> {
	public static final LoginLog dao = new LoginLog().dao();
}
