
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {


	/**
	 * 超级管理员
	 */
	public static final short ADMIN_SUPER = 99;

	/**
	 * 普通管理员
	 */
	public static final short ADMIN_NORMAL = 1;

	/**
	 * 用户
	 */
	public static final short NORMAL = 2;

	/**
	 * 上传视频的角色
	 */
	public static final short UPLOAD_VIDEO = 6;

	/**
	 * 允许阅读文档的角色
	 */
	public static final short ALLOW_READ_DOC = 7;//allow_read_doc
	
	/**
	 * 已经支付过脚手架源代码的角色
	 */
	public static final short PAID_DOC_CODE = 8; //paid_doc
	
	/**
	 *   已经购买t-io官网源代码的角色
	 */
	public static final short PAID_SITECODE = 9; 
	
	/**
	 *	钛信文档权限
	 */
	public static final short DOC_TAIXIN_DOC_ROLE = 15;

	/**
	 * 购买了官网代码旗舰版的用户
	 */
	public static final short PAID_SITECODE_QIJIAN = 94; 
	
	/**
	 *  购买了官网代码白金版的用户
	 */
	public static final short PAID_SITECODE_BAIJIN = 95; 
	
	/**
	 * 购买了tio-chat普及版的用户
	 */
	public static final short PAID_TIOCHAT_BASE = 96; 


}
