
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseSignItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SignItem extends BaseSignItem<SignItem> {
	public static final SignItem dao = new SignItem().dao();
}
