
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseSignRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SignRole extends BaseSignRole<SignRole> {
	public static final SignRole dao = new SignRole().dao();
}
