
/*
 * 使用本软件请从杭州钛特云有限公司获取授权，其它途径获取本软件的行为皆为侵权行为
 * 黄庆辉-4412********4310
 */package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseTioThreadLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TioThreadLogs extends BaseTioThreadLogs<TioThreadLogs> {
	public static final TioThreadLogs dao = new TioThreadLogs().dao();
}
