
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseUserlogModifyAvatar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserlogModifyAvatar extends BaseUserlogModifyAvatar<UserlogModifyAvatar> {
	public static final UserlogModifyAvatar dao = new UserlogModifyAvatar().dao();
}
