
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	public static final UserRole dao = new UserRole().dao();
}
