
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.UserThird.SubTable;
import org.tio.mg.service.model.main.base.BaseUserThirdOsc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserThirdOsc extends BaseUserThirdOsc<UserThirdOsc> implements SubTable {
	public static final UserThirdOsc dao = new UserThirdOsc().dao();
}
