
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseUserMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserMsg extends BaseUserMsg<UserMsg> {
	public static final UserMsg dao = new UserMsg().dao();
}
