
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Video extends BaseVideo<Video> {

	public static interface Status {
		/**
		 * 正常
		 */
		short NORMAL = 1;

		/**
		 * 违规
		 */
		short INVALID = 2;
	}

	public static interface ComeFrom {
		/**
		 * IM上传
		 */
		short IM_UPLOAD = 1;

	}

}
