
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxCallItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxCallItem extends BaseWxCallItem<WxCallItem> {
	public static final WxCallItem dao = new WxCallItem().dao();

	/**
	 * 通话类型，是音频通话还是视频通话
	 * @author tanyaowu 
	 * 2020年1月23日 上午10:53:20
	 */
	public static interface CallType {
		/**
		 * 音频通话
		 */
		short	AUDIO	= 1;
		/**
		 * 视频通话
		 */
		short	VIDEO	= 2;
	}

	/**
	 * 呼叫状态：1、发起呼叫， 2、信令接通，3、流媒体接通，4、通话结束（拒接、占线、挂断都属于通话结束）
	 * @author tanyaowu 
	 * 2020年2月21日 下午5:42:34
	 */
	public static interface Status {
		/**
		 * 发起呼叫
		 */
		short	BEGIN_CALLING		= 1;
		/**
		 * 信令接通
		 */
		short	TCP_CONNECTED		= 2;
		/**
		 * 流媒体接通
		 */
		short	STREAM_CONNECTED	= 3;
		/**
		 * 通话结束（拒接、占线、挂断都属于通话结束）
		 */
		short	END					= 4;
	}

	/**
	 * 挂断类型 <br>
	 * 1、正常挂断<br>
	 * 2、拒接挂断<br>
	 * 3、对方正在通话<br>
	 * 4、TCP断开时，系统自动挂断<br>
	 * 5、客户端出现异常，系统自动挂机（譬如获取摄像头失败等），这个请求是客户端发起的挂断请求<br>
	 * 6、ICE服务器异常，这个请求是客户端发起的挂断请求<br>
	 * 7、系统重启<br>
	 * 8、对方不在线<br>
	 * 9、等待响应超时<br>
	 * 10、发起方取消了通话
	 * 99、还没有挂断<br>
	 * @author tanyaowu 
	 * 2020年2月21日 下午6:28:14
	 */
	public static interface Hanguptype {
		/**
		 * 正常挂断
		 */
		short	NORMAL				= 1;
		/**
		 * 拒接挂断
		 */
		short	REJECT				= 2;
		/**
		 * 对方正在通话
		 */
		short	OTHER_SIDE_CALLING	= 3;
		/**
		 * TCP断开时，系统自动挂断
		 */
		short	TCP_DROPPED			= 4;
		/**
		 * 客户端出现异常，系统自动挂机（譬如获取摄像头失败等），这个请求是客户端发起的挂断请求
		 */
		short	CLIENT_ERROR		= 5;
		/**
		 * ICE服务器异常，这个请求是客户端发起的挂断请求
		 */
		short	ICE_ERROR			= 6;
		/**
		 * 系统重启
		 */
		short	SYSTEM_RESTART		= 7;
		/**
		 * 对方不在线
		 */
		short	OFFLINE				= 8;
		/**
		 * 等待响应超时
		 */
		short	RESP_TIMEOUT		= 9;
		/**
		 * 发起方取消了通话
		 */
		short	CANCELED			= 10;
		/**
		 * 还没有挂断
		 */
		short	NOT_HANGUP			= 99;
	}

}
