
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxChatGroupItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxChatGroupItem extends BaseWxChatGroupItem<WxChatGroupItem> {
	public static final WxChatGroupItem dao = new WxChatGroupItem().dao();
}
