
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxChatItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxChatItems extends BaseWxChatItems<WxChatItems> {
	public static final WxChatItems dao = new WxChatItems().dao();
}
