
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxChatUserItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxChatUserItem extends BaseWxChatUserItem<WxChatUserItem> {
	public static final WxChatUserItem dao = new WxChatUserItem().dao();
	
	public static interface UserIndexOper {
		/**
		 * 	关联用户
		 */
		short ADD_FRIEND = 1;
		
		/**
		 * 移除聊天会话
		 */
		short REMOVE_CHAT = 2;

		
		/**
		 * 隐藏聊天-好友黑名单专用
		 */
		short BLOCK_CHAT = 3;
		
		
		/**
		 * 删除好友
		 */
		short DEL_FRIEND = 4;
		
		/**
		 *   被删除好友
		 */
		short TO_DEL_FRIEND =5;
		
		/**
		 * 恢复聊天-好友黑名单专用
		 */
		short REMOVE_BLOCK_CHAT = 6;
		
		/**
		 * 激活聊天
		 */
		short CHAT_ITEM_ACT = 7;
		
		/**
		 * 清空聊天消息
		 */
		short CLEAR_CHAT_MSG = 8;

	}
	
}
