
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxFriendDelLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriendDelLog extends BaseWxFriendDelLog<WxFriendDelLog> {
	public static final WxFriendDelLog dao = new WxFriendDelLog().dao();
}
