
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriend extends BaseWxFriend<WxFriend> {
	public static final WxFriend dao = new WxFriend().dao();
	
	/**
	 * 好友状态
	 * @author xufei
	 */
	public static interface Status {
		/**
		 *  正常
		 */
		short NORMAL = 1;

		/**
		 * 拉黑-废弃
		 */
		short OUT = 2;
	}
	
	/**
	 * 添加好友验证码
	 * @author xufei
	 * 2020年1月9日 下午5:33:23
	 */
	public static interface AddRespCode {
		
		/**
		 * 错误码
		 */
		Short ERROR = -1;
		
		/**
		 * 需要验证
		 */
		Short WHERE = 1;
		
		/**
		 *  无条件
		 */
		Short NO_WHERE = 2;
	}
}
