
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxFriendApplyItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriendApplyItems extends BaseWxFriendApplyItems<WxFriendApplyItems> {
	public static final WxFriendApplyItems dao = new WxFriendApplyItems().dao();
	
	/**
	 * 申请状态
	 * @author xufei
	 * 2020年1月9日 下午2:50:54
	 */
	public static interface ApplyStatus {
		/**
		 *  通过
		 */
		short PASS = 1;

		/**
		 * 申请中
		 */
		short APPLY = 2;
		
		/**
		 * 无效：过期/拒绝
		 */
		short INVALID = 3;
	}
}
