
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxFriendOperMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxFriendOperMsg extends BaseWxFriendOperMsg<WxFriendOperMsg> {
	public static final WxFriendOperMsg dao = new WxFriendOperMsg().dao();
}
