
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxGroupMeta;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupMeta extends BaseWxGroupMeta<WxGroupMeta> {
	public static final WxGroupMeta dao = new WxGroupMeta().dao();
}
