
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroup extends BaseWxGroup<WxGroup> {
	public static final WxGroup dao = new WxGroup().dao();
	public static final String DEFAULT_GROUP_AVATAR = "/img/group.png";
	
	/**
	 * 群人数
	 */
	public void setJoinnum(java.lang.Short joinnum) {
		put("joinnum", joinnum);
	}
	
	/**
	 * 群人数
	 */
	public java.lang.Short getJoinnum() {
		return getShort("joinnum");
	}
}
