
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxGroupUserDelLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxGroupUserDelLog extends BaseWxGroupUserDelLog<WxGroupUserDelLog> {
	public static final WxGroupUserDelLog dao = new WxGroupUserDelLog().dao();
}
