
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxTagFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxTagFriend extends BaseWxTagFriend<WxTagFriend> {
	public static final WxTagFriend dao = new WxTagFriend().dao();
}
