
package org.tio.mg.service.model.main;

import org.tio.mg.service.model.main.base.BaseWxTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxTag extends BaseWxTag<WxTag> {
	public static final WxTag dao = new WxTag().dao();
}
