
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseWxUserCoinLocal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxUserCoinLocal extends BaseWxUserCoinLocal<WxUserCoinLocal> {
	public static final WxUserCoinLocal dao = new WxUserCoinLocal().dao();
}
