
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseWxWalletInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletInfoLocal extends BaseWxWalletInfo<WxWalletInfoLocal> {
	public static final WxWalletInfoLocal dao = new WxWalletInfoLocal().dao();
}
