
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseWxWallet;

import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletLocal extends BaseWxWallet<WxWalletLocal> {
	public static final WxWalletLocal dao = new WxWalletLocal().dao();

	public static WxWalletLocal mapToBean(Map<String, Object> map) {
		WxWalletLocal wallet = new WxWalletLocal();
		wallet._setOrPut(map);
		return wallet;
	}
}
