
package org.tio.mg.service.model.main;


import org.tio.mg.service.model.main.base.BaseWxWalletCoin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxWalletCoinLocal extends BaseWxWalletCoin<WxWalletCoinLocal> {
	public static final WxWalletCoinLocal dao = new WxWalletCoinLocal().dao();
}
