const state={
    curruser:null,//当前用户
    routes:[],//菜单列表
    dealroutes:[],
    tags:[],//导航tag标签
    authList:[],//权限列表
    sysparams:null,
    tologin:{//提示重新登录弹框
        show:false,
        title:''
    },
    useruid:'',//用户信息弹框uid
    usershow:false,//用户信息弹框显示状态
    tmchat:{},//会话信息
    chatshow:false,//会话显示状态
    routefrom:'',//首次访问的路由地址
};
const mutations= {
    setCurrUser(state,val){
        state.curruser=val;
    },
    addRouteList(state,val){
        state.routes=val;
    },
    addDealRoutes(state,val){
        state.dealroutes=val;
    },
    addTags(state,val){
        state.tags=val;
    },
    setAuthList(state,val){
        state.authList=val;
    },
    setSysParams(state,val){
        state.sysparams=val;
    },
    setLoginDialog(state,val){
        state.tologin=val;
    },
    setUserInfoUid(state,val){
        state.useruid=val;
    },
    setUserInfoShow(state,val){
        state.usershow=val;
    },
    setChatShow(state,val){
        state.chatshow=val;
    },
    setTmChat(state,val){
        state.tmchat=val;
    },
    setRouteFrom(state,val){
        state.routefrom=val;
    },
};
export default{
    state,
    mutations
}