
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupUserInviteLog<M extends BaseWxGroupUserInviteLog<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 邀请进哪个群
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 邀请进哪个群
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 发起邀请的userid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 发起邀请的userid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 1：可用状态，2：不可用状态（譬如进群后被T）
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 1：可用状态，2：不可用状态（譬如进群后被T）
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 被邀请的userid
	 */
	public void setInviteduid(java.lang.Integer inviteduid) {
		set("inviteduid", inviteduid);
	}
	
	/**
	 * 被邀请的userid
	 */
	public java.lang.Integer getInviteduid() {
		return getInt("inviteduid");
	}

	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

