
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxWalletBankInfo<M extends BaseWxWalletBankInfo<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 银行名称
	 */
	public void setBankname(java.lang.String bankname) {
		set("bankname", bankname);
	}
	
	/**
	 * 银行名称
	 */
	public java.lang.String getBankname() {
		return getStr("bankname");
	}

	/**
	 * 银行代码
	 */
	public void setBankcode(java.lang.String bankcode) {
		set("bankcode", bankcode);
	}
	
	/**
	 * 银行代码
	 */
	public java.lang.String getBankcode() {
		return getStr("bankcode");
	}

	/**
	 * 银行icon
	 */
	public void setBanklogo(java.lang.String banklogo) {
		set("banklogo", banklogo);
	}
	
	/**
	 * 银行icon
	 */
	public java.lang.String getBanklogo() {
		return getStr("banklogo");
	}

	public void setBankwatermark(java.lang.String bankwatermark) {
		set("bankwatermark", bankwatermark);
	}
	
	public java.lang.String getBankwatermark() {
		return getStr("bankwatermark");
	}

	public void setBackcolor(java.lang.String backcolor) {
		set("backcolor", backcolor);
	}
	
	public java.lang.String getBackcolor() {
		return getStr("backcolor");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

