
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxFriendApplyLog<M extends BaseWxFriendApplyLog<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * fromuserid，发起添加好友请求的userid
	 */
	public void setFromuid(java.lang.Integer fromuid) {
		set("fromuid", fromuid);
	}
	
	/**
	 * fromuserid，发起添加好友请求的userid
	 */
	public java.lang.Integer getFromuid() {
		return getInt("fromuid");
	}

	/**
	 * 添加谁为好友
	 */
	public void setTouid(java.lang.Integer touid) {
		set("touid", touid);
	}
	
	/**
	 * 添加谁为好友
	 */
	public java.lang.Integer getTouid() {
		return getInt("touid");
	}

	/**
	 * 打招呼的内容
	 */
	public void setGreet(java.lang.String greet) {
		set("greet", greet);
	}
	
	/**
	 * 打招呼的内容
	 */
	public java.lang.String getGreet() {
		return getStr("greet");
	}

	/**
	 * 1、已经同意，2、已经拒绝，3、已读未处理，4、未读，5、作废
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 1、已经同意，2、已经拒绝，3、已读未处理，4、未读，5、作废
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 已读时间
	 */
	public void setReadtime(java.util.Date readtime) {
		set("readtime", readtime);
	}
	
	/**
	 * 已读时间
	 */
	public java.util.Date getReadtime() {
		return getDate("readtime");
	}

	/**
	 * 处理时间（拒绝时间或同意时间）
	 */
	public void setReplytime(java.util.Date replytime) {
		set("replytime", replytime);
	}
	
	/**
	 * 处理时间（拒绝时间或同意时间）
	 */
	public java.util.Date getReplytime() {
		return getDate("replytime");
	}

	/**
	 * 打招呼时的ip信息
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * 打招呼时的ip信息
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

