
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUserRedPacketItem<M extends BaseWxUserRedPacketItem<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 接受的用户id-冗余
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 接受的用户id-冗余
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 发送的红包id
	 */
	public void setRedid(java.lang.Integer redid) {
		set("redid", redid);
	}
	
	/**
	 * 发送的红包id
	 */
	public java.lang.Integer getRedid() {
		return getInt("redid");
	}

	/**
	 * 金额
	 */
	public void setCny(java.lang.Double cny) {
		set("cny", cny);
	}
	
	/**
	 * 金额
	 */
	public java.lang.Double getCny() {
		return getDouble("cny");
	}

	/**
	 * 类型：1：正常红包；2：退回合并红包
	 */
	public void setMode(java.lang.Short mode) {
		set("mode", mode);
	}
	
	/**
	 * 类型：1：正常红包；2：退回合并红包
	 */
	public java.lang.Short getMode() {
		return getShort("mode");
	}

	/**
	 * 状态：1：完成；2：初始化
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：完成；2：初始化
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 红包的顺序
	 */
	public void setIndex(java.lang.Integer index) {
		set("index", index);
	}
	
	/**
	 * 红包的顺序
	 */
	public java.lang.Integer getIndex() {
		return getInt("index");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

