
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCircleMsg<M extends BaseCircleMsg<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return getInt("id");
	}

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() {
		return getInt("uid");
	}

	public void setToUid(Integer toUid) {
		set("to_uid", toUid);
	}

	public Integer getToUid() {
		return getInt("to_uid");
	}

	public void setText(String text) {
		set("text", text);
	}

	public String getText() {
		return getStr("text");
	}

	public void setResume(String resume) {
		set("resume", resume);
	}

	public String getResume() {
		return getStr("resume");
	}


	public void setReadFlag(Integer readFlag) {
		set("read_flag", readFlag);
	}

	public Integer getReadFlag() {
		return getInt("read_flag");
	}


	public void setContentType(Integer contentType) {
		set("content_type", contentType);
	}

	public Integer getContentType() {
		return getInt("content_type");
	}

	/**
	 * 发送时间
	 */
	public void setTime(java.util.Date time) {
		set("time", time);
	}

	/**
	 * 发送时间
	 */
	public java.util.Date getTime() {
		return getDate("time");
	}

	/**
	 * 阅读时间
	 */
	public void setReadTime(java.util.Date readTime) {
		set("read_time", readTime);
	}

	/**
	 * 阅读时间
	 */
	public java.util.Date getReadTime() {
		return getDate("read_time");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}


}

