
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

import java.util.Date;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWalletItemLocal<M extends BaseWalletItemLocal<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public Integer getId() {
		return getInt("id");
	}

	public void setType(Integer type) {
		set("type", type);
	}
	
	public Integer getType() { return getInt("type"); }

	public void setRechargeOrWithhold(Integer rechargeOrWithhold) {
		set("rechargeOrWithhold", rechargeOrWithhold);
	}

	public Integer getRechargeOrWithhold() { return getInt("rechargeOrWithhold"); }

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() { return getInt("uid"); }

	public void setAmount(Double amount) {
		set("amount", amount);
	}

	public Double getAmount() { return getDouble("amount"); }

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() { return getInt("status"); }

	public void setCreateTime(Date createTime) {
		set("createTime", createTime);
	}

	public Date getCreateTime() { return getDate("createTime"); }

	public void setUpdateTime(Date updateTime) {
		set("updateTime", updateTime);
	}

	public Date getUpdateTime() { return getDate("updateTime"); }

	public void setSerialnumber(String serialnumber) {
		set("serialnumber", serialnumber);
	}

	public String getSerialnumber() { return getStr("serialnumber"); }

	public void setToken(String token) {
		set("token", token);
	}

	public String getToken() { return getStr("token"); }

	public void setName(String name) {
		set("name", name);
	}

	public String getName() { return getStr("name"); }

	public void setBankname(String bankname) {
		set("bankname", bankname);
	}

	public String getBankname() { return getStr("bankname"); }
//	public void setUlink(String ulink) {
//		set("ulink", ulink);
//	}
//
//	public String getUlink() { return getStr("ulink"); }
//
//	public void setUlinkimg(String ulinkimg) {
//		set("ulinkimg", ulinkimg);
//	}
//
//	public String getUlinkimg() { return getStr("ulinkimg"); }

	public void setPaymentAccount(String paymentAccount) {
		set("paymentAccount", paymentAccount);
	}

	public String getPaymentAccount() { return getStr("paymentAccount"); }
}

