
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePaymentImg<M extends BasePaymentImg<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public Integer getId() {
		return getInt("id");
	}

	public void setPaymentImg(String paymentImg) {
		set("paymentImg", paymentImg);
	}
	
	public String getPaymentImg() {
		return getStr("paymentImg");
	}


	/**
	 * 收款码类型 1: 微信收款码 2: 支付宝收款
	 */
	public void setType(Integer type) {
		set("type", type);
	}

	/**
	 * 收款码类型 1: 微信收款码 2: 支付宝收款
	 */
	public Integer getType() {
		return getInt("type");
	}
}

