
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserPaymentImg<M extends BaseUserPaymentImg<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * ID
	 */
	public void setUId(Integer uid) {
		set("uid", uid);
	}

	/**
	 * ID
	 */
	public Integer getUId() {
		return getInt("uid");
	}

	/**
     * 用户收款码url
	 */
	public void setUserPaymentUrl(String userPaymentUrl) {
		set("userPaymentUrl", userPaymentUrl);
	}

	/**
	 * 用户收款码url
	 */
	public String getUserPaymentUrl() {
		return getStr("userPaymentUrl");
	}

	/**
	 * 收款码类型 1: 支付宝 2: 微信
	 */
	public void setType(Integer type) {
		set("type", type);
	}

	/**
	 * 收款码类型 1: 支付宝 2: 微信
	 */
	public Integer getType() {
		return getInt("type");
	}

	/**
	 * 名字
	 */
	public void setName(String name) {
		set("name", name);
	}

	/**
	 * 名字
	 */
	public String getName() {
		return getStr("name");
	}

	/**
	 * 支付账号
	 */
	public void setPaymentAccount(String paymentAccount) {
		set("paymentAccount", paymentAccount);
	}

	/**
	 * 支付账号
	 */
	public String getPaymentAccount() {
		return getStr("paymentAccount");
	}
}

