
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIpInfo<M extends BaseIpInfo<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 国家
	 */
	public void setCountry(java.lang.String country) {
		set("country", country);
	}
	
	/**
	 * 国家
	 */
	public java.lang.String getCountry() {
		return getStr("country");
	}

	/**
	 * 区域
	 */
	public void setArea(java.lang.String area) {
		set("area", area);
	}
	
	/**
	 * 区域
	 */
	public java.lang.String getArea() {
		return getStr("area");
	}

	/**
	 * 省
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	/**
	 * 省
	 */
	public java.lang.String getProvince() {
		return getStr("province");
	}

	/**
	 * 市
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	/**
	 * 市
	 */
	public java.lang.String getCity() {
		return getStr("city");
	}

	/**
	 * 运营商
	 */
	public void setOperator(java.lang.String operator) {
		set("operator", operator);
	}
	
	/**
	 * 运营商
	 */
	public java.lang.String getOperator() {
		return getStr("operator");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return getDate("time");
	}

}

