
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxWalletBankCards<M extends BaseWxWalletBankCards<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 绑卡请求code
	 */
	public void setReqid(java.lang.String reqid) {
		set("reqid", reqid);
	}
	
	/**
	 * 绑卡请求code
	 */
	public java.lang.String getReqid() {
		return getStr("reqid");
	}

	/**
	 * 商户号
	 */
	public void setMerid(java.lang.String merid) {
		set("merid", merid);
	}
	
	/**
	 * 商户号
	 */
	public java.lang.String getMerid() {
		return getStr("merid");
	}

	/**
	 * 钱包id
	 */
	public void setWalletid(java.lang.String walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 钱包id
	 */
	public java.lang.String getWalletid() {
		return getStr("walletid");
	}

	/**
	 * 商户订单号
	 */
	public void setMerorderid(java.lang.String merorderid) {
		set("merorderid", merorderid);
	}
	
	/**
	 * 商户订单号
	 */
	public java.lang.String getMerorderid() {
		return getStr("merorderid");
	}

	/**
	 * 签约号码
	 */
	public void setAgrno(java.lang.String agrno) {
		set("agrno", agrno);
	}
	
	/**
	 * 签约号码
	 */
	public java.lang.String getAgrno() {
		return getStr("agrno");
	}

	/**
	 * 银行code
	 */
	public void setBankcode(java.lang.String bankcode) {
		set("bankcode", bankcode);
	}
	
	/**
	 * 银行code
	 */
	public java.lang.String getBankcode() {
		return getStr("bankcode");
	}

	/**
	 * 银行卡号
	 */
	public void setCardno(java.lang.String cardno) {
		set("cardno", cardno);
	}
	
	/**
	 * 银行卡号
	 */
	public java.lang.String getCardno() {
		return getStr("cardno");
	}

	/**
	 * 银行名称
	 */
	public void setBankname(java.lang.String bankname) {
		set("bankname", bankname);
	}
	
	/**
	 * 银行名称
	 */
	public java.lang.String getBankname() {
		return getStr("bankname");
	}

	/**
	 * 持卡人
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 持卡人
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 预留手机
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 预留手机
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 卡类型：1：信用卡；2：储蓄卡
	 */
	public void setCardtype(java.lang.Short cardtype) {
		set("cardtype", cardtype);
	}
	
	/**
	 * 卡类型：1：信用卡；2：储蓄卡
	 */
	public java.lang.Short getCardtype() {
		return getShort("cardtype");
	}

	/**
	 * 银行限额
	 */
	public void setBanklimit(java.lang.Double banklimit) {
		set("banklimit", banklimit);
	}
	
	/**
	 * 银行限额
	 */
	public java.lang.Double getBanklimit() {
		return getDouble("banklimit");
	}

	/**
	 * 状态：1：已认证；2：未认证；3：移除
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：已认证；2：未认证；3：移除
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 移除请求id
	 */
	public void setDelreqid(java.lang.String delreqid) {
		set("delreqid", delreqid);
	}
	
	/**
	 * 移除请求id
	 */
	public java.lang.String getDelreqid() {
		return getStr("delreqid");
	}

	/**
	 * 删除时间
	 */
	public void setDeltime(java.util.Date deltime) {
		set("deltime", deltime);
	}
	
	/**
	 * 删除时间
	 */
	public java.util.Date getDeltime() {
		return getDate("deltime");
	}

	/**
	 * 删除id
	 */
	public void setDelid(java.lang.Integer delid) {
		set("delid", delid);
	}
	
	/**
	 * 删除id
	 */
	public java.lang.Integer getDelid() {
		return getInt("delid");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

