
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSignItem<M extends BaseSignItem<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * user id
	 */
	public void setUid(Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * user id
	 */
	public Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 签到领取的积分数
	 */
	public void setIntegral(Long integral) {
		set("integral", integral);
	}

	/**
	 * 签到领取的积分数
	 */
	public Long getIntegral() {
		return getLong("integral");
	}


	/**
	 * 领取签到积分前的积分数
	 */
	public Long getBeforeIntegral() {
		return getLong("before_integral");
	}

	/**
	 * 领取签到积分前的积分数
	 */
	public void setBeforeIntegral(Long beforeIntegral) {
		set("before_integral", beforeIntegral);
	}


	/**
	 * 领取签到积分后的积分数
	 */
	public void setNowIntegral(Long nowIntegral) {
		set("now_integral", nowIntegral);
	}

	/**
	 * 领取签到积分后的积分数
	 */
	public Long getNowIntegral() {
		return getLong("now_integral");
	}

	/**
	 * 描述
	 */
	public void setDescribe(String describe) {
		set("describe", describe);
	}
	
	/**
	 * 描述
	 */
	public String getDescribe() {
		return getStr("describe");
	}


	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("create_time", createtime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("create_time");
	}


}

