
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFile<M extends BaseFile<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 上传者
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 上传者
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setSession(java.lang.String session) {
		set("session", session);
	}
	
	public java.lang.String getSession() {
		return getStr("session");
	}

	/**
	 * 文件名
	 */
	public void setFilename(java.lang.String filename) {
		set("filename", filename);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getFilename() {
		return getStr("filename");
	}

	/**
	 * 后缀名
	 */
	public void setExt(java.lang.String ext) {
		set("ext", ext);
	}
	
	/**
	 * 后缀名
	 */
	public java.lang.String getExt() {
		return getStr("ext");
	}

	/**
	 * 文件url
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 文件url
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 原始url，因为文件可能来自第三方
	 */
	public void setIniturl(java.lang.String initurl) {
		set("initurl", initurl);
	}
	
	/**
	 * 原始url，因为文件可能来自第三方
	 */
	public java.lang.String getIniturl() {
		return getStr("initurl");
	}

	/**
	 * 文件大小，单位字节
	 */
	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	/**
	 * 文件大小，单位字节
	 */
	public java.lang.Long getSize() {
		return getLong("size");
	}

	/**
	 * 状态：1：正常；2：无效
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：正常；2：无效
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 上传时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 上传时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

