
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseChatroomJoinLeave<M extends BaseChatroomJoinLeave<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * userid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * userid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 *  服务器地址，对应 app-host.properties的my.ip那个配置项
	 */
	public void setServer(java.lang.String server) {
		set("server", server);
	}
	
	/**
	 *  服务器地址，对应 app-host.properties的my.ip那个配置项
	 */
	public java.lang.String getServer() {
		return getStr("server");
	}

	/**
	 * sessionid
	 */
	public void setSession(java.lang.String session) {
		set("session", session);
	}
	
	/**
	 * sessionid
	 */
	public java.lang.String getSession() {
		return getStr("session");
	}

	/**
	 * ip_info的id字段
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * ip_info的id字段
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setDevice(java.lang.Short device) {
		set("device", device);
	}
	
	/**
	 * 设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public java.lang.Short getDevice() {
		return getShort("device");
	}

	/**
	 * 群组id
	 */
	public void setGroupid(java.lang.String groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 群组id
	 */
	public java.lang.String getGroupid() {
		return getStr("groupid");
	}

	/**
	 * 进入聊天室时间
	 */
	public void setJointime(java.util.Date jointime) {
		set("jointime", jointime);
	}
	
	/**
	 * 进入聊天室时间
	 */
	public java.util.Date getJointime() {
		return getDate("jointime");
	}

	/**
	 * 离开聊天室时间
	 */
	public void setLeavetime(java.util.Date leavetime) {
		set("leavetime", leavetime);
	}
	
	/**
	 * 离开聊天室时间
	 */
	public java.util.Date getLeavetime() {
		return getDate("leavetime");
	}

	/**
	 * 耗时，单位毫秒
	 */
	public void setCost(java.lang.Long cost) {
		set("cost", cost);
	}
	
	/**
	 * 耗时，单位毫秒
	 */
	public java.lang.Long getCost() {
		return getLong("cost");
	}

	/**
	 * 1：正常记录，2：程序最终修改的记录，3、程序定时修改记录，9：初始值
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 1：正常记录，2：程序最终修改的记录，3、程序定时修改记录，9：初始值
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

}

