
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserThirdWx<M extends BaseUserThirdWx<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * user_third表的id字段
	 */
	public void setUserThirdId(java.lang.Integer userThirdId) {
		set("user_third_id", userThirdId);
	}
	
	/**
	 * user_third表的id字段
	 */
	public java.lang.Integer getUserThirdId() {
		return getInt("user_third_id");
	}

	/**
	 * 国家
	 */
	public void setCountry(java.lang.String country) {
		set("country", country);
	}
	
	/**
	 * 国家
	 */
	public java.lang.String getCountry() {
		return getStr("country");
	}

	/**
	 * 省
	 */
	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	/**
	 * 省
	 */
	public java.lang.String getProvince() {
		return getStr("province");
	}

	/**
	 * 城市
	 */
	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	/**
	 * 城市
	 */
	public java.lang.String getCity() {
		return getStr("city");
	}

}

