
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxWalletCoinItem<M extends BaseWxWalletCoinItem<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 金额
	 */
	public void setCny(java.lang.Long cny) {
		set("cny", cny);
	}
	
	/**
	 * 金额
	 */
	public java.lang.Long getCny() {
		return getLong("cny");
	}

	/**
	 * 其它费用
	 */
	public void setOthercny(java.lang.Long othercny) {
		set("othercny", othercny);
	}
	
	/**
	 * 其它费用
	 */
	public java.lang.Long getOthercny() {
		return getLong("othercny");
	}

	/**
	 * 类型：1：充值；2：体现；3：红包；4：银行卡消费；5：银行卡退款
	 */
	public void setMode(java.lang.Short mode) {
		set("mode", mode);
	}
	
	/**
	 * 类型：1：充值；2：体现；3：红包；4：银行卡消费；5：银行卡退款
	 */
	public java.lang.Short getMode() {
		return getShort("mode");
	}

	/**
	 * 收支：1：收入；2：支出；
	 */
	public void setCoinflag(java.lang.Short coinflag) {
		set("coinflag", coinflag);
	}
	
	/**
	 * 收支：1：收入；2：支出；
	 */
	public java.lang.Short getCoinflag() {
		return getShort("coinflag");
	}

	/**
	 * 状态：1：完成；2：初始化；3：处理中
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：完成；2：初始化；3：处理中
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 订单处理状态：同业务订单状态
	 */
	public void setOrderstatus(java.lang.String orderstatus) {
		set("orderstatus", orderstatus);
	}
	
	/**
	 * 订单处理状态：同业务订单状态
	 */
	public java.lang.String getOrderstatus() {
		return getStr("orderstatus");
	}

	/**
	 * 业务id
	 */
	public void setBizid(java.lang.Integer bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 业务id
	 */
	public java.lang.Integer getBizid() {
		return getInt("bizid");
	}

	/**
	 * 请求id
	 */
	public void setReqid(java.lang.String reqid) {
		set("reqid", reqid);
	}
	
	/**
	 * 请求id
	 */
	public java.lang.String getReqid() {
		return getStr("reqid");
	}

	/**
	 * 业务订单号
	 */
	public void setMerorderid(java.lang.String merorderid) {
		set("merorderid", merorderid);
	}
	
	/**
	 * 业务订单号
	 */
	public java.lang.String getMerorderid() {
		return getStr("merorderid");
	}

	/**
	 * 订单号
	 */
	public void setSerialnumber(java.lang.String serialnumber) {
		set("serialnumber", serialnumber);
	}
	
	/**
	 * 订单号
	 */
	public java.lang.String getSerialnumber() {
		return getStr("serialnumber");
	}

	/**
	 * 业务内容
	 */
	public void setBizstr(java.lang.String bizstr) {
		set("bizstr", bizstr);
	}
	
	/**
	 * 业务内容
	 */
	public java.lang.String getBizstr() {
		return getStr("bizstr");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 订单完成时间
	 */
	public void setBizcompletetime(java.lang.String bizcompletetime) {
		set("bizcompletetime", bizcompletetime);
	}
	
	/**
	 * 订单完成时间
	 */
	public java.lang.String getBizcompletetime() {
		return getStr("bizcompletetime");
	}

	/**
	 * 订单创建时间
	 */
	public void setBizcreattime(java.lang.String bizcreattime) {
		set("bizcreattime", bizcreattime);
	}
	
	/**
	 * 订单创建时间
	 */
	public java.lang.String getBizcreattime() {
		return getStr("bizcreattime");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

