
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProvincial<M extends BaseProvincial<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public void setPrimary(String primary) {
		set("primary", primary);
	}

	/**
	 * 名称
	 */
	public String getPrimary() {
		return getStr("primary");
	}


}

