
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxFriendApplyItems<M extends BaseWxFriendApplyItems<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * fromuserid，发起添加好友请求的userid
	 */
	public void setFromuid(java.lang.Integer fromuid) {
		set("fromuid", fromuid);
	}
	
	/**
	 * fromuserid，发起添加好友请求的userid
	 */
	public java.lang.Integer getFromuid() {
		return getInt("fromuid");
	}

	/**
	 * 添加谁为好友
	 */
	public void setTouid(java.lang.Integer touid) {
		set("touid", touid);
	}
	
	/**
	 * 添加谁为好友
	 */
	public java.lang.Integer getTouid() {
		return getInt("touid");
	}

	/**
	 * 申请内容
	 */
	public void setGreet(java.lang.String greet) {
		set("greet", greet);
	}
	
	/**
	 * 申请内容
	 */
	public java.lang.String getGreet() {
		return getStr("greet");
	}

	/**
	 * 处理：1：通过；2：申请中；3：过期/拒绝
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 处理：1：通过；2：申请中；3：过期/拒绝
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 自动加人标识：1：是；2：否
	 */
	public void setAutoflag(java.lang.Short autoflag) {
		set("autoflag", autoflag);
	}
	
	/**
	 * 自动加人标识：1：是；2：否
	 */
	public java.lang.Short getAutoflag() {
		return getShort("autoflag");
	}

	/**
	 * 处理时间
	 */
	public void setReplytime(java.util.Date replytime) {
		set("replytime", replytime);
	}
	
	/**
	 * 处理时间
	 */
	public java.util.Date getReplytime() {
		return getDate("replytime");
	}

	/**
	 * 处理时的ip
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * 处理时的ip
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

