
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSmsLog<M extends BaseSmsLog<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 短信验证码
	 */
	public void setSmscode(java.lang.String smscode) {
		set("smscode", smscode);
	}
	
	/**
	 * 短信验证码
	 */
	public java.lang.String getSmscode() {
		return getStr("smscode");
	}

	/**
	 * 模板code
	 */
	public void setTempcode(java.lang.String tempcode) {
		set("tempcode", tempcode);
	}
	
	/**
	 * 模板code
	 */
	public java.lang.String getTempcode() {
		return getStr("tempcode");
	}

	/**
	 * 发送ip
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 发送ip
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public void setErrormsg(java.lang.String errormsg) {
		set("errormsg", errormsg);
	}
	
	public java.lang.String getErrormsg() {
		return getStr("errormsg");
	}

	/**
	 * 电话24小时统计
	 */
	public void setPhone24count(java.lang.Integer phone24count) {
		set("phone24count", phone24count);
	}
	
	/**
	 * 电话24小时统计
	 */
	public java.lang.Integer getPhone24count() {
		return getInt("phone24count");
	}

	/**
	 * ip24小时统计
	 */
	public void setIp24count(java.lang.Integer ip24count) {
		set("ip24count", ip24count);
	}
	
	/**
	 * ip24小时统计
	 */
	public java.lang.Integer getIp24count() {
		return getInt("ip24count");
	}

	/**
	 * 设备发送数
	 */
	public void setDevicecount(java.lang.Integer devicecount) {
		set("devicecount", devicecount);
	}
	
	/**
	 * 设备发送数
	 */
	public java.lang.Integer getDevicecount() {
		return getInt("devicecount");
	}

	public void setSessionid(java.lang.String sessionid) {
		set("sessionid", sessionid);
	}
	
	public java.lang.String getSessionid() {
		return getStr("sessionid");
	}

	public void setReferer(java.lang.String referer) {
		set("referer", referer);
	}
	
	public java.lang.String getReferer() {
		return getStr("referer");
	}

	/**
	 * 设备cookie值
	 */
	public void setCookiekey(java.lang.String cookiekey) {
		set("cookiekey", cookiekey);
	}
	
	/**
	 * 设备cookie值
	 */
	public java.lang.String getCookiekey() {
		return getStr("cookiekey");
	}

	/**
	 * 发送状态：1:成功；2：失败
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 发送状态：1:成功；2：失败
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

