
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxApp<M extends BaseWxApp<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 版本号
	 */
	public void setVersion(java.lang.String version) {
		set("version", version);
	}
	
	/**
	 * 版本号
	 */
	public java.lang.String getVersion() {
		return getStr("version");
	}

	/**
	 * 版本名称内容
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 版本名称内容
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 更新模式：1：正常更新；2：强制更新
	 */
	public void setUpdatemode(java.lang.Short updatemode) {
		set("updatemode", updatemode);
	}
	
	/**
	 * 更新模式：1：正常更新；2：强制更新
	 */
	public java.lang.Short getUpdatemode() {
		return getShort("updatemode");
	}

	/**
	 * 类型：1：安卓；2：ios
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 类型：1：安卓；2：ios
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 包大小
	 */
	public void setPackagesize(java.lang.Double packagesize) {
		set("packagesize", packagesize);
	}
	
	/**
	 * 包大小
	 */
	public java.lang.Double getPackagesize() {
		return getDouble("packagesize");
	}

	/**
	 * 包名称
	 */
	public void setPackagename(java.lang.String packagename) {
		set("packagename", packagename);
	}
	
	/**
	 * 包名称
	 */
	public java.lang.String getPackagename() {
		return getStr("packagename");
	}

	/**
	 * 文件路径
	 */
	public void setFileurl(java.lang.String fileurl) {
		set("fileurl", fileurl);
	}
	
	/**
	 * 文件路径
	 */
	public java.lang.String getFileurl() {
		return getStr("fileurl");
	}

	/**
	 * 手动下载路径
	 */
	public void setManualOperationUrl(java.lang.String ManualOperationUrl) {
		set("manual_operation_url", ManualOperationUrl);
	}

	/**
	 * 手动下载路径
	 */
	public java.lang.String getManualOperationUrl() {
		return getStr("manual_operation_url");
	}

	/**
	 * 状态:1:发布；2：下架/初始化
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态:1:发布；2：下架/初始化
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 操作用户
	 */
	public void setMguid(java.lang.Integer mguid) {
		set("mguid", mguid);
	}
	
	/**
	 * 操作用户
	 */
	public java.lang.Integer getMguid() {
		return getInt("mguid");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

