
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxWalletBackRedPacketItems<M extends BaseWxWalletBackRedPacketItems<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 红包id
	 */
	public void setRid(java.lang.Integer rid) {
		set("rid", rid);
	}
	
	/**
	 * 红包id
	 */
	public java.lang.Integer getRid() {
		return getInt("rid");
	}

	/**
	 * 请求id
	 */
	public void setReqid(java.lang.String reqid) {
		set("reqid", reqid);
	}
	
	/**
	 * 请求id
	 */
	public java.lang.String getReqid() {
		return getStr("reqid");
	}

	/**
	 * 商户id
	 */
	public void setMerid(java.lang.String merid) {
		set("merid", merid);
	}
	
	/**
	 * 商户id
	 */
	public java.lang.String getMerid() {
		return getStr("merid");
	}

	/**
	 * 商户订单号-转账
	 */
	public void setMerorderid(java.lang.String merorderid) {
		set("merorderid", merorderid);
	}
	
	/**
	 * 商户订单号-转账
	 */
	public java.lang.String getMerorderid() {
		return getStr("merorderid");
	}

	/**
	 * 钱包id
	 */
	public void setWalletid(java.lang.String walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 钱包id
	 */
	public java.lang.String getWalletid() {
		return getStr("walletid");
	}

	/**
	 * 附属钱包id
	 */
	public void setSubwalletid(java.lang.String subwalletid) {
		set("subwalletid", subwalletid);
	}
	
	/**
	 * 附属钱包id
	 */
	public java.lang.String getSubwalletid() {
		return getStr("subwalletid");
	}

	/**
	 * 退回金额
	 */
	public void setCny(java.lang.Long cny) {
		set("cny", cny);
	}
	
	/**
	 * 退回金额
	 */
	public java.lang.Long getCny() {
		return getLong("cny");
	}

	/**
	 * 类型：1：普通红包；2：手气红包；
	 */
	public void setMode(java.lang.Short mode) {
		set("mode", mode);
	}
	
	/**
	 * 类型：1：普通红包；2：手气红包；
	 */
	public java.lang.Short getMode() {
		return getShort("mode");
	}

	/**
	 * 状态：1：完成；2：初始化；3：转账中；4：失败
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：完成；2：初始化；3：转账中；4：失败
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 退回红包数量
	 */
	public void setNum(java.lang.Short num) {
		set("num", num);
	}
	
	/**
	 * 退回红包数量
	 */
	public java.lang.Short getNum() {
		return getShort("num");
	}

	/**
	 * 退回时间
	 */
	public void setBacktime(java.util.Date backtime) {
		set("backtime", backtime);
	}
	
	/**
	 * 退回时间
	 */
	public java.util.Date getBacktime() {
		return getDate("backtime");
	}

	/**
	 * 处理时间
	 */
	public void setDealtime(java.util.Date dealtime) {
		set("dealtime", dealtime);
	}
	
	/**
	 * 处理时间
	 */
	public java.util.Date getDealtime() {
		return getDate("dealtime");
	}

	/**
	 * 完成时间
	 */
	public void setCompletetime(java.util.Date completetime) {
		set("completetime", completetime);
	}
	
	/**
	 * 完成时间
	 */
	public java.util.Date getCompletetime() {
		return getDate("completetime");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

