
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserMsg<M extends BaseUserMsg<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 消息id
	 */
	public void setMsgid(java.lang.Integer msgid) {
		set("msgid", msgid);
	}
	
	/**
	 * 消息id
	 */
	public java.lang.Integer getMsgid() {
		return getInt("msgid");
	}

	/**
	 * 状态：1：已读；2：未读；3：删除
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：已读；2：未读；3：删除
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 该记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 该记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

