
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCircleArticle<M extends BaseCircleArticle<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 用户头像
	 */
	public void setAvatar(String avatar) {
		set("avatar", avatar);
	}

	/**
	 * 用户头像
	 */
	public String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 圈子id
	 */
	public void setCircleId(Integer circleId) {
		set("circle_id", circleId);
	}

	/**
	 * 圈子id
	 */
	public Integer getCircleId() {
		return getInt("circle_id");
	}

	/**
	 * 文字描述
	 */
	public void setContent(String content) {
		set("content", content);
	}

	/**
	 * 文字描述
	 */
	public String getContent() {
		return getStr("content");
	}

	/**
	 * 视频链接
	 */
	public void setVideoUrl(String videoUrl) {
		set("video_url", videoUrl);
	}

	/**
	 * 视频链接
	 */
	public String getVideoUrl() {
		return getStr("video_url");
	}

	/**
	 * 图片链接
	 */
	public void setImgUrl(String imgUrl) {
		set("img_url", imgUrl);
	}

	/**
	 * 图片链接
	 */
	public String getImgUrl() {
		return getStr("img_url");
	}

	/**
	 * 城市id
	 */
	public void setCityId(Integer cityId) {
		set("city_id", cityId);
	}

	/**
	 * 城市id
	 */
	public Integer getCityId() {
		return getInt("city_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

}

