
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxChatItems<M extends BaseWxChatItems<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户uid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户uid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 聊天模式：1：私聊；2：群聊
	 */
	public void setChatmode(java.lang.Short chatmode) {
		set("chatmode", chatmode);
	}
	
	/**
	 * 聊天模式：1：私聊；2：群聊
	 */
	public java.lang.Short getChatmode() {
		return getShort("chatmode");
	}

	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public void setBizid(java.lang.Long bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public java.lang.Long getBizid() {
		return getLong("bizid");
	}

	/**
	 * 关联关系id：群：群用户id；私聊：好友id
	 */
	public void setLinkid(java.lang.Long linkid) {
		set("linkid", linkid);
	}
	
	/**
	 * 关联关系id：群：群用户id；私聊：好友id
	 */
	public java.lang.Long getLinkid() {
		return getLong("linkid");
	}

	/**
	 * 好友组合uid的key-twouid
	 */
	public void setFidkey(java.lang.String fidkey) {
		set("fidkey", fidkey);
	}
	
	/**
	 * 好友组合uid的key-twouid
	 */
	public java.lang.String getFidkey() {
		return getStr("fidkey");
	}

	/**
	 * 角色：1：群主；2：成员
	 */
	public void setBizrole(java.lang.Short bizrole) {
		set("bizrole", bizrole);
	}
	
	/**
	 * 角色：1：群主；2：成员
	 */
	public java.lang.Short getBizrole() {
		return getShort("bizrole");
	}

	/**
	 * 群头像/好友头像
	 */
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	/**
	 * 群头像/好友头像
	 */
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	/**
	 * 是否是有效连接（是否是有效的聊天信息）：1：是；2：否
	 */
	public void setLinkflag(java.lang.Short linkflag) {
		set("linkflag", linkflag);
	}
	
	/**
	 * 是否是有效连接（是否是有效的聊天信息）：1：是；2：否
	 */
	public java.lang.Short getLinkflag() {
		return getShort("linkflag");
	}

	/**
	 * 状态：1：正常；2：封停
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：正常；2：封停
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 群名称/私聊名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 群名称/私聊名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 会话人数
	 */
	public void setJoinnum(java.lang.Short joinnum) {
		set("joinnum", joinnum);
	}
	
	/**
	 * 会话人数
	 */
	public java.lang.Short getJoinnum() {
		return getShort("joinnum");
	}

	/**
	 * 是否置顶：1：是；2：否
	 */
	public void setTopflag(java.lang.Short topflag) {
		set("topflag", topflag);
	}
	
	/**
	 * 是否置顶：1：是；2：否
	 */
	public java.lang.Short getTopflag() {
		return getShort("topflag");
	}

	/**
	 * 从哪个消息开始有阅读权限-废弃
	 */
	public void setStartmsgid(java.lang.Long startmsgid) {
		set("startmsgid", startmsgid);
	}
	
	/**
	 * 从哪个消息开始有阅读权限-废弃
	 */
	public java.lang.Long getStartmsgid() {
		return getLong("startmsgid");
	}

	/**
	 * 是否免打扰：1：是；2：否
	 */
	public void setMsgfreeflag(java.lang.Short msgfreeflag) {
		set("msgfreeflag", msgfreeflag);
	}
	
	/**
	 * 是否免打扰：1：是；2：否
	 */
	public java.lang.Short getMsgfreeflag() {
		return getShort("msgfreeflag");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

