
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUserFavorites<M extends BaseWxUserFavorites<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 类型：同消息类型
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 类型：同消息类型
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 消息来源会话类型
	 */
	public void setChatmode(java.lang.Short chatmode) {
		set("chatmode", chatmode);
	}
	
	/**
	 * 消息来源会话类型
	 */
	public java.lang.Short getChatmode() {
		return getShort("chatmode");
	}

	/**
	 * 消息id
	 */
	public void setMid(java.lang.Long mid) {
		set("mid", mid);
	}
	
	/**
	 * 消息id
	 */
	public java.lang.Long getMid() {
		return getLong("mid");
	}

	/**
	 * 路径或者内容
	 */
	public void setBizstr(java.lang.String bizstr) {
		set("bizstr", bizstr);
	}
	
	/**
	 * 路径或者内容
	 */
	public java.lang.String getBizstr() {
		return getStr("bizstr");
	}

	public void setMsgtext(java.lang.String msgtext) {
		set("msgtext", msgtext);
	}
	
	public java.lang.String getMsgtext() {
		return getStr("msgtext");
	}

	/**
	 * 状态：1：正常
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：正常
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 上传时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 上传时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

