
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCircleMemberApply<M extends BaseCircleMemberApply<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 申请人uid
	 */
	public void setUid(Integer uid) {
		set("uid", uid);
	}

	/**
	 * 申请人uid
	 */
	public Integer getUid() {
		return getInt("uid");
	}


	/**
	 * 审核人uid
	 */
	public void setExamineUid(Integer examineUid) {
		set("examine_uid", examineUid);
	}

	/**
	 * 审核人uid
	 */
	public Integer getExamineUid() {
		return getInt("examine_uid");
	}

	/**
	 * 圈子id
	 */
	public void setCircleId(Integer circleId) {
		set("circle_id", circleId);
	}

	/**
	 * 圈子id
	 */
	public Integer getCircleId() {
		return getInt("circle_id");
	}

	/**
	 * 邀请码(逗号隔开)
	 */
	public void setInviteCode(String inviteCode) {
		set("invite_code", inviteCode);
	}

	/**
	 * 邀请码(逗号隔开)
	 */
	public String getInviteCode() {
		return getStr("invite_code");
	}

	/**
	 * 圈子状态
	 */
	public void setStatus(Integer status) {
		set("status", status);
	}

	/**
	 * 圈子状态
	 */
	public Integer getStatus() {
		return getInt("status");
	}


	/**
	 * 拒绝理由
	 */
	public void setRefuseReason(String refuseReason) {
		set("refuse_reason", refuseReason);
	}

	/**
	 * 拒绝理由
	 */
	public String getRefuseReason() {
		return getStr("refuse_reason");
	}


	/**
	 * 审核人昵称
	 */
	public void setExamineNick(String examineNick) {
		set("examine_nick", examineNick);
	}

	/**
	 * 审核人昵称
	 */
	public String getExamineNick() {
		return getStr("examine_nick");
	}

	public void setContentType(Integer contentType) {
		set("content_type", contentType);
	}

	public Integer getContentType() {
		return getInt("content_type");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

}

