
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCircleMember<M extends BaseCircleMember<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	public void setCircleId(Integer circleId) {
		set("circle_id", circleId);
	}

	public Integer getCircleId() {
		return getInt("circle_id");
	}

	public void setUid(Integer uid) {
		set("uid", uid);
	}

	public Integer getUid() {
		return getInt("uid");
	}

	public void setInviteUid(Integer inviteUid) {
		set("invite_uid", inviteUid);
	}

	public Integer getInviteUid() {
		return getInt("invite_uid");
	}

	/**
	 * 用户头像
	 */
	public void setAvatar(String avatar) {
		set("avatar", avatar);
	}

	/**
	 * 用户头像
	 */
	public String getAvatar() {
		return getStr("avatar");
	}

	public void setNick(String nick) {
		set("nick", nick);
	}

	public String getNick() {
		return getStr("nick");
	}

	public void setRole(Integer role) {
		set("role", role);
	}

	public Integer getRole() {
		return getInt("role");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}

}

