
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCircleMemberInviteCode<M extends BaseCircleMemberInviteCode<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}


	public void setCircleId(Integer circleId) {
		set("circle_id", circleId);
	}

	public Integer getCircleId() {
		return getInt("circle_id");
	}

	/**
	 * 创建者的uid
	 */
	public void setCreateUid(Integer createUid) {
		set("create_uid", createUid);
	}

	/**
	 * 创建者的uid
	 */
	public Integer getCreateUid() {
		return getInt("create_uid");
	}

	/**
	 * 使用者的uid
	 */
	public void setUseUid(Integer useUid) {
		set("use_uid", useUid);
	}

	/**
	 * 使用者的uid
	 */
	public Integer getUseUid() {
		return getInt("use_uid");
	}

	/**
	 * 邀请码
	 */
	public void setInviteCode(String inviteCode) {
		set("invite_code", inviteCode);
	}

	/**
	 * 邀请码
	 */
	public String getInviteCode() {
		return getStr("invite_code");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	/**
	 * 创建时间
	 */
	public java.util.Date geCreateTime() {
		return getDate("create_time");
	}

	/**
	 * 更新时间
	 */
	public void setUseTime(java.util.Date useTime) {
		set("use_time", useTime);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUseTime() {
		return getDate("use_time");
	}


	public void setIsDel(Integer isDel) {
		set("is_del", isDel);
	}

	public Integer getIsDel() {
		return getInt("is_del");
	}


	public void setIsUse(Integer isUse) {
		set("is_use", isUse);
	}

	public Integer getIsUse() {
		return getInt("is_use");
	}

}

