
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCity<M extends BaseCity<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 名称
	 */
	public void setCity(String city) {
		set("city", city);
	}

	/**
	 * 名称
	 */
	public String getCity() {
		return getStr("city");
	}

	/**
	 * 首拼
	 */
	public void setShoupin(String shoupin) {
		set("shoupin", shoupin);
	}

	/**
	 * 首拼
	 */
	public String getShoupin() {
		return getStr("shoupin");
	}

	/**
	 * 是否推荐
	 */
	public void setIsRecommend(Integer isRecommend) {
		set("is_recommend", isRecommend);
	}

	/**
	 * 是否推荐
	 */
	public Integer getIsRecommend() {
		return getInt("is_recommend");
	}
}

