
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxFriendDelLog<M extends BaseWxFriendDelLog<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 主人的userid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 主人的userid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 好友的userid
	 */
	public void setFrienduid(java.lang.Integer frienduid) {
		set("frienduid", frienduid);
	}
	
	/**
	 * 好友的userid
	 */
	public java.lang.Integer getFrienduid() {
		return getInt("frienduid");
	}

	/**
	 * 删除好友时的ip信息
	 */
	public void setIpid(java.lang.Integer ipid) {
		set("ipid", ipid);
	}
	
	/**
	 * 删除好友时的ip信息
	 */
	public java.lang.Integer getIpid() {
		return getInt("ipid");
	}

	/**
	 * 更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

}

