
package org.tio.mg.service.model.main.base;

import org.tio.jfinal.plugin.activerecord.IBean;
import org.tio.mg.service.jf.TioModel;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUserCoinLocal<M extends BaseWxUserCoinLocal<M>> extends TioModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}
	
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 钱包余额
	 */
	public void setCny(Long cny) {
		set("cny", cny);
	}
	
	/**
	 * 钱包余额
	 */
	public Long getCny() {
		return getLong("cny");
	}

	/**
	 * 体现余额
	 */
	public void setWithdrawcny(Long withdrawcny) {
		set("withdrawcny", withdrawcny);
	}
	
	/**
	 * 体现余额
	 */
	public Long getWithdrawcny() {
		return getLong("withdrawcny");
	}

	/**
	 * 接受红包
	 */
	public void setAcceptredpacket(Long acceptredpacket) {
		set("acceptredpacket", acceptredpacket);
	}
	
	/**
	 * 接受红包
	 */
	public Long getAcceptredpacket() {
		return getLong("acceptredpacket");
	}

	/**
	 * 发送红包
	 */
	public void setSendpacket(Long sendpacket) {
		set("sendpacket", sendpacket);
	}
	
	/**
	 * 发送红包
	 */
	public Long getSendpacket() {
		return getLong("sendpacket");
	}

	/**
	 * 消费密码
	 */
	public void setCostpwd(String costpwd) {
		set("costpwd", costpwd);
	}
	
	/**
	 * 消费密码
	 */
	public String getCostpwd() {
		return getStr("costpwd");
	}

	/**
	 * 钱包id
	 */
	public void setWalletid(String walletid) {
		set("walletid", walletid);
	}

	/**
	 * 钱包id
	 */
	public String getWalletid() {
		return getStr("walletid");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

