
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxGroupApply<M extends BaseWxGroupApply<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 群id
	 */
	public void setGroupid(java.lang.Long groupid) {
		set("groupid", groupid);
	}
	
	/**
	 * 群id
	 */
	public java.lang.Long getGroupid() {
		return getLong("groupid");
	}

	/**
	 * 申请人uid
	 */
	public void setOperuid(java.lang.Integer operuid) {
		set("operuid", operuid);
	}
	
	/**
	 * 申请人uid
	 */
	public java.lang.Integer getOperuid() {
		return getInt("operuid");
	}

	/**
	 * 申请信息
	 */
	public void setApplymsg(java.lang.String applymsg) {
		set("applymsg", applymsg);
	}
	
	/**
	 * 申请信息
	 */
	public java.lang.String getApplymsg() {
		return getStr("applymsg");
	}

	/**
	 * 申请状态：1：已处理；2：申请中；3：已驳回
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 申请状态：1：已处理；2：申请中；3：已驳回
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 *  群创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 *  群创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 *  群资料更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 *  群资料更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

