
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxChatItemsMeta<M extends BaseWxChatItemsMeta<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户uid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户uid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 聊天模式：1：私聊；2：群聊
	 */
	public void setChatmode(java.lang.Short chatmode) {
		set("chatmode", chatmode);
	}
	
	/**
	 * 聊天模式：1：私聊；2：群聊
	 */
	public java.lang.Short getChatmode() {
		return getShort("chatmode");
	}

	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public void setBizid(java.lang.Long bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 业务id；私聊：touid；群聊：groupid
	 */
	public java.lang.Long getBizid() {
		return getLong("bizid");
	}

	/**
	 * 有效链接：1：是；2：否
	 */
	public void setLinkflag(java.lang.Short linkflag) {
		set("linkflag", linkflag);
	}
	
	/**
	 * 有效链接：1：是；2：否
	 */
	public java.lang.Short getLinkflag() {
		return getShort("linkflag");
	}

	/**
	 * 展示状态（是否显示列表，该状态下跟激活状态不同的是，有特殊情况激活而不显示）：1：是；2：否
	 */
	public void setViewflag(java.lang.Short viewflag) {
		set("viewflag", viewflag);
	}
	
	/**
	 * 展示状态（是否显示列表，该状态下跟激活状态不同的是，有特殊情况激活而不显示）：1：是；2：否
	 */
	public java.lang.Short getViewflag() {
		return getShort("viewflag");
	}

	/**
	 * 会话id
	 */
	public void setChatlinkid(java.lang.Long chatlinkid) {
		set("chatlinkid", chatlinkid);
	}
	
	/**
	 * 会话id
	 */
	public java.lang.Long getChatlinkid() {
		return getLong("chatlinkid");
	}

	/**
	 * 对方是否已读自己的消息（私聊）：1：是；2：否
	 */
	public void setToreadflag(java.lang.Short toreadflag) {
		set("toreadflag", toreadflag);
	}
	
	/**
	 * 对方是否已读自己的消息（私聊）：1：是；2：否
	 */
	public java.lang.Short getToreadflag() {
		return getShort("toreadflag");
	}

	/**
	 * 是否已读：1：是；2：否
	 */
	public void setReadflag(java.lang.Short readflag) {
		set("readflag", readflag);
	}
	
	/**
	 * 是否已读：1：是；2：否
	 */
	public java.lang.Short getReadflag() {
		return getShort("readflag");
	}

	/**
	 * 焦点标识：1：是；2：否
	 */
	public void setFocusflag(java.lang.Short focusflag) {
		set("focusflag", focusflag);
	}
	
	/**
	 * 焦点标识：1：是；2：否
	 */
	public java.lang.Short getFocusflag() {
		return getShort("focusflag");
	}

	/**
	 * 未读数
	 */
	public void setNotreadcount(java.lang.Integer notreadcount) {
		set("notreadcount", notreadcount);
	}
	
	/**
	 * 未读数
	 */
	public java.lang.Integer getNotreadcount() {
		return getInt("notreadcount");
	}

	/**
	 * 未读开始的消息id
	 */
	public void setNotreadstartmsgid(java.lang.Long notreadstartmsgid) {
		set("notreadstartmsgid", notreadstartmsgid);
	}
	
	/**
	 * 未读开始的消息id
	 */
	public java.lang.Long getNotreadstartmsgid() {
		return getLong("notreadstartmsgid");
	}

	/**
	 * @是否已读：1：是；2：否
	 */
	public void setAtreadflag(java.lang.Short atreadflag) {
		set("atreadflag", atreadflag);
	}
	
	/**
	 * @是否已读：1：是；2：否
	 */
	public java.lang.Short getAtreadflag() {
		return getShort("atreadflag");
	}

	/**
	 * @未读的条数
	 */
	public void setAtnotreadcount(java.lang.Short atnotreadcount) {
		set("atnotreadcount", atnotreadcount);
	}
	
	/**
	 * @未读的条数
	 */
	public java.lang.Short getAtnotreadcount() {
		return getShort("atnotreadcount");
	}

	/**
	 * @未读的起始消息id
	 */
	public void setAtnotreadstartmsgid(java.lang.Long atnotreadstartmsgid) {
		set("atnotreadstartmsgid", atnotreadstartmsgid);
	}
	
	/**
	 * @未读的起始消息id
	 */
	public java.lang.Long getAtnotreadstartmsgid() {
		return getLong("atnotreadstartmsgid");
	}

	/**
	 * 累计会话消息数
	 */
	public void setMsgcount(java.lang.Integer msgcount) {
		set("msgcount", msgcount);
	}
	
	/**
	 * 累计会话消息数
	 */
	public java.lang.Integer getMsgcount() {
		return getInt("msgcount");
	}

	/**
	 * 聊天最后的消息id
	 */
	public void setLastmsgid(java.lang.Long lastmsgid) {
		set("lastmsgid", lastmsgid);
	}
	
	/**
	 * 聊天最后的消息id
	 */
	public java.lang.Long getLastmsgid() {
		return getLong("lastmsgid");
	}

	/**
	 * 聊天最后的消息发送者
	 */
	public void setLastmsguid(java.lang.Integer lastmsguid) {
		set("lastmsguid", lastmsguid);
	}
	
	/**
	 * 聊天最后的消息发送者
	 */
	public java.lang.Integer getLastmsguid() {
		return getInt("lastmsguid");
	}

	/**
	 * 最后消息的昵称
	 */
	public void setFromnick(java.lang.String fromnick) {
		set("fromnick", fromnick);
	}
	
	/**
	 * 最后消息的昵称
	 */
	public java.lang.String getFromnick() {
		return getStr("fromnick");
	}

	/**
	 * 最后的消息缩略
	 */
	public void setMsgresume(java.lang.String msgresume) {
		set("msgresume", msgresume);
	}
	
	/**
	 * 最后的消息缩略
	 */
	public java.lang.String getMsgresume() {
		return getStr("msgresume");
	}

	/**
	 * 消息类型：同消息
	 */
	public void setMsgtype(java.lang.Short msgtype) {
		set("msgtype", msgtype);
	}
	
	/**
	 * 消息类型：同消息
	 */
	public java.lang.Short getMsgtype() {
		return getShort("msgtype");
	}

	/**
	 * 最后一条是否是系统消息：1：是；2：否
	 */
	public void setSysflag(java.lang.Short sysflag) {
		set("sysflag", sysflag);
	}
	
	/**
	 * 最后一条是否是系统消息：1：是；2：否
	 */
	public java.lang.Short getSysflag() {
		return getShort("sysflag");
	}

	/**
	 * 消息模板key值
	 */
	public void setSysmsgkey(java.lang.String sysmsgkey) {
		set("sysmsgkey", sysmsgkey);
	}
	
	/**
	 * 消息模板key值
	 */
	public java.lang.String getSysmsgkey() {
		return getStr("sysmsgkey");
	}

	/**
	 * 操作者昵称
	 */
	public void setOpernick(java.lang.String opernick) {
		set("opernick", opernick);
	}
	
	/**
	 * 操作者昵称
	 */
	public java.lang.String getOpernick() {
		return getStr("opernick");
	}

	/**
	 * 发送者昵称列表
	 */
	public void setTonicks(java.lang.String tonicks) {
		set("tonicks", tonicks);
	}
	
	/**
	 * 发送者昵称列表
	 */
	public java.lang.String getTonicks() {
		return getStr("tonicks");
	}

	/**
	 * 发送时间
	 */
	public void setSendtime(java.util.Date sendtime) {
		set("sendtime", sendtime);
	}
	
	/**
	 * 发送时间
	 */
	public java.util.Date getSendtime() {
		return getDate("sendtime");
	}

	/**
	 * 会话更新时间
	 */
	public void setChatuptime(java.util.Date chatuptime) {
		set("chatuptime", chatuptime);
	}
	
	/**
	 * 会话更新时间
	 */
	public java.util.Date getChatuptime() {
		return getDate("chatuptime");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

