
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUserWallet<M extends BaseWxUserWallet<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 请求id
	 */
	public void setReqid(java.lang.String reqid) {
		set("reqid", reqid);
	}
	
	/**
	 * 请求id
	 */
	public java.lang.String getReqid() {
		return getStr("reqid");
	}

	/**
	 * 商户业务id
	 */
	public void setBizid(java.lang.String bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 商户业务id
	 */
	public java.lang.String getBizid() {
		return getStr("bizid");
	}

	/**
	 * 钱包id
	 */
	public void setWalletid(java.lang.String walletid) {
		set("walletid", walletid);
	}
	
	/**
	 * 钱包id
	 */
	public java.lang.String getWalletid() {
		return getStr("walletid");
	}

	/**
	 * 运行商状态：1：认证；2：未认证；
	 */
	public void setOperatorstatus(java.lang.Short operatorstatus) {
		set("operatorstatus", operatorstatus);
	}
	
	/**
	 * 运行商状态：1：认证；2：未认证；
	 */
	public java.lang.Short getOperatorstatus() {
		return getShort("operatorstatus");
	}

	/**
	 * 实名认证：1：认证；2：未认证
	 */
	public void setRealnamestatus(java.lang.Short realnamestatus) {
		set("realnamestatus", realnamestatus);
	}
	
	/**
	 * 实名认证：1：认证；2：未认证
	 */
	public java.lang.Short getRealnamestatus() {
		return getShort("realnamestatus");
	}

	/**
	 * 状态：1：正常；2：禁用
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：正常；2：禁用
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}

	/**
	 * 同步状态：1：初始化；2：未完成；3：完成
	 */
	public void setCoinsyn(java.lang.Short coinsyn) {
		set("coinsyn", coinsyn);
	}
	
	/**
	 * 同步状态：1：初始化；2：未完成；3：完成
	 */
	public java.lang.Short getCoinsyn() {
		return getShort("coinsyn");
	}

	/**
	 * 异常同步：1：已处理：2：未处理
	 */
	public void setExcepsyn(java.lang.Short excepsyn) {
		set("excepsyn", excepsyn);
	}
	
	/**
	 * 异常同步：1：已处理：2：未处理
	 */
	public java.lang.Short getExcepsyn() {
		return getShort("excepsyn");
	}

	/**
	 * 发起的ip
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * 发起的ip
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public void setDevice(java.lang.Short device) {
		set("device", device);
	}
	
	/**
	 * 发起的设备类型（DeviceType），1：PC，2：安卓，3：IOS
	 */
	public java.lang.Short getDevice() {
		return getShort("device");
	}

	/**
	 * 发起的app版本号
	 */
	public void setAppversion(java.lang.String appversion) {
		set("appversion", appversion);
	}
	
	/**
	 * 发起的app版本号
	 */
	public java.lang.String getAppversion() {
		return getStr("appversion");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

