
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxReadAck<M extends BaseWxReadAck<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户uid
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户uid
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 对方uid
	 */
	public void setTouid(java.lang.Integer touid) {
		set("touid", touid);
	}
	
	/**
	 * 对方uid
	 */
	public java.lang.Integer getTouid() {
		return getInt("touid");
	}

	/**
	 * 会话id
	 */
	public void setChatlinkid(java.lang.Long chatlinkid) {
		set("chatlinkid", chatlinkid);
	}
	
	/**
	 * 会话id
	 */
	public java.lang.Long getChatlinkid() {
		return getLong("chatlinkid");
	}

	/**
	 * 类型：1：ack；2：发送
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 类型：1：ack；2：发送
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 设备类型
	 */
	public void setDevicetype(java.lang.Short devicetype) {
		set("devicetype", devicetype);
	}
	
	/**
	 * 设备类型
	 */
	public java.lang.Short getDevicetype() {
		return getShort("devicetype");
	}

	/**
	 *  群创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 *  群创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 *  群资料更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 *  群资料更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

