
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAudio<M extends BaseAudio<M>> extends TioModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 上传者
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 上传者
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 上传业务id
	 */
	public void setBizid(java.lang.Long bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 上传业务id
	 */
	public java.lang.Long getBizid() {
		return getLong("bizid");
	}

	/**
	 * 文件名
	 */
	public void setFilename(java.lang.String filename) {
		set("filename", filename);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getFilename() {
		return getStr("filename");
	}

	/**
	 * 音频url
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * 音频url
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * 来源。1、wx上传
	 */
	public void setFrom(java.lang.Short from) {
		set("from", from);
	}
	
	/**
	 * 来源。1、wx上传
	 */
	public java.lang.Short getFrom() {
		return getShort("from");
	}

	/**
	 * 时长（秒）
	 */
	public void setSeconds(java.lang.Integer seconds) {
		set("seconds", seconds);
	}
	
	/**
	 * 时长（秒）
	 */
	public java.lang.Integer getSeconds() {
		return getInt("seconds");
	}

	/**
	 * 文件大小，单位字节
	 */
	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	/**
	 * 文件大小，单位字节
	 */
	public java.lang.Long getSize() {
		return getLong("size");
	}

	/**
	 * 状态：1：不可公开浏览；2：可公开浏览；3：禁止在任何场景显示
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：不可公开浏览；2：可公开浏览；3：禁止在任何场景显示
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 上传时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 上传时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 修改时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

