
package org.tio.mg.service.model.main.base;

import org.tio.mg.service.jf.TioModel;
import org.tio.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWxUserRedPacket<M extends BaseWxUserRedPacket<M>> extends TioModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 用户id
	 */
	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	/**
	 * 金额
	 */
	public void setCny(java.lang.Double cny) {
		set("cny", cny);
	}
	
	/**
	 * 金额
	 */
	public java.lang.Double getCny() {
		return getDouble("cny");
	}

	/**
	 * 类型：1：普通红包；2：手气红包；3：红包退回
	 */
	public void setMode(java.lang.Short mode) {
		set("mode", mode);
	}
	
	/**
	 * 类型：1：普通红包；2：手气红包；3：红包退回
	 */
	public java.lang.Short getMode() {
		return getShort("mode");
	}

	/**
	 * 状态：1：完成；2：初始化
	 */
	public void setStatus(java.lang.Short status) {
		set("status", status);
	}
	
	/**
	 * 状态：1：完成；2：初始化
	 */
	public java.lang.Short getStatus() {
		return getShort("status");
	}

	/**
	 * 类型：1：发送；2：接受
	 */
	public void setType(java.lang.Short type) {
		set("type", type);
	}
	
	/**
	 * 类型：1：发送；2：接受
	 */
	public java.lang.Short getType() {
		return getShort("type");
	}

	/**
	 * 发送手气红包个数
	 */
	public void setNum(java.lang.Short num) {
		set("num", num);
	}
	
	/**
	 * 发送手气红包个数
	 */
	public java.lang.Short getNum() {
		return getShort("num");
	}

	/**
	 * 接受红包的业务id
	 */
	public void setBizid(java.lang.Integer bizid) {
		set("bizid", bizid);
	}
	
	/**
	 * 接受红包的业务id
	 */
	public java.lang.Integer getBizid() {
		return getInt("bizid");
	}

	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 记录创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}

	/**
	 * 该记录更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 该记录更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}

}

